### ISSUE TITLE
Sky Sport News HD - offline

### ISSUE THREAD

**Issue by bernd19781** [jnk22/kodinerds-iptv#101]
Zuerst einmal VIELEN DANK für diese gute Arbeit. Einfach TOP!
Das Problem: Sky Sport News HD ist unter dem bisherigen URL nicht mehr erreichbar.
Geht das zu fixen? Danke

**Comment by herrTravolta** [comment]
Die haben wohl die URL auf https://  gewechselt:

https://eventhlshttps-i.akamaihd.net/hls/live/263645/ssn-hd-https/index.m3u8
