### ISSUE TITLE
Streams für weitere IPTV Kanäle (International, Lokal, Österreich)

### ISSUE THREAD

**Issue by asciidisco** [jnk22/kodinerds-iptv#106]
Ich habe noch mal weitere Streams (wie der Titel schon sagt, viel lokales, internationales & eine paar aus Österreich) rausgesucht. Ich habe jetzt keine weiteren Infos (EPG id, Logo) rausgesucht, weil ich erstmal gerne klären wollte, ob das wirklich alles so übernommen werden kann/soll, da ja ne Menge davon "special interest" ist.

Mit dem Proxy Addon könnten Nutzer in Zukunft die ungewünschten Kanäle ausblenden & sollte eine Gruppierung (wie in https://github.com/jnk22/kodinerds-iptv/issues/47 beschrieben) möglich sein, hätte ich da weniger schmerzen auch den ganzen lokalen Kram reinzubringen...

Liste: https://gist.github.com/asciidisco/9ccfb8e05f54c88b21d4061a0fb3da03

P.s.: Alle streams natürlich ohne Geoblock & von mir getestet.

**Comment by tzwn** [comment]
Für die internationalen Sender haben wir ja eine Liste. Bzgl. der vielen lokalen Sender ist das eine gute Frage - evtl in die "Extras-Liste" mit Einpflegen oder eine neue für lokale Sender Erstellen?
