### ISSUE TITLE
EPG / xmltv dokumentieren

### ISSUE THREAD

**Issue by azrdev** [jnk22/kodinerds-iptv#116]
Mit den hier gepflegten m3us bekomme ich im PVR/IPTV-simple addon Fernsehsender rein, danke dafür!

EPG funktioniert allerdings nicht -- es ist ja auch keine XMLTV URL dabei. Die [Installationsanleitung im Thread](https://www.kodinerds.net/index.php/Thread/56713-Fertige-Liste-mit-freien-IPTV-Kanälen-IPTV-Video-Anleitung) sagt nur `EPG herunterladen
    Anleitung folgt...
` 
In einem [anderen Thread](https://www.kodinerds.net/index.php/Thread/56588-PVR-IPTV-Simple-Client-EPG-channels-not-found-Kodi-17-1/?postID=379304#post379304) heißt es `die fertige Liste inkl. kompletten EPG läuft`, aber nicht wie.

**Comment by tzwn** [comment]
Du findest eine kurze Anleitung für die Einrichtung des "Rytec EPG Downloaders" in der Video-Anleitung des von dir verlinkten [https://www.kodinerds.net/index.php/Thread/56713-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len-IPTV-Video-Anleitung/?postID=381328#post381328](Threads).

**Comment by jnk22** [comment]
Habe das mal angepasst und an der Stelle auf das Video verwiesen, ich denke da kann man das ganze am besten sehen.

**Comment by azrdev** [comment]
Ah, ich dachte rytec geht gar nicht mehr, nicht genau gelesen. Danke!
Wie im Video funktionierts, um dem nächsten meine Verwirrung zu ersparen, nehmt doch einfach noch ne textuelle Beschreibung mit auf:

5. EPG konfigurieren: **Auf die Reihenfolge achten!**
    - Das kodinerds repository installieren
        - Hauptmenü > Einstellungen > System > Addons > "Unbekannte Quellen" aktivieren
        - Das [repository.kodinerds.zip](https://github.com/kodinerds/repo/raw/master/repository.kodinerds.zip) herunterladen & speichern
        - Hauptmenü > Addons > Herunterladen > .. > Aus ZIP-Datei installieren > die `repository.kodinerds.zip` auswählen
    - Den ["Rytec EPG Downloader"](https://www.kodinerds.net/index.php/Thread/45285) installieren
        - (Hauptmenü > Addons > Herunterladen > .. ) > Aus Repository installieren > kodinerds.net Add-ons > Dienste > "Rytec EPG Downloader" auswählen
        - Das addon installieren & die addon-Konfiguration öffnen
    - Den Rytec EPG Downloader konfigurieren
        - Settings > Download Folder: setzen und merken
        - Settings > Activation Code: Eingeben, findet ihr im thread zum addon
        - XMLTV Rytec > XMLTV Rytec 1: Eine liste auswählen (welche passt zu welcher m3u?)
        - Settings > Manual Download: einmal ausführen
        - Das addon aktivieren (falls es noch nicht ist)
    - das PVR IPTV Simple addon mit dem vom Rytec EPG Downloader heruntergeladenen EPG konfigurieren
        - Hauptmenü > Addons > Benutzer-Addons > PVR-Clients > "PVR IPTV Simple Client" konfigurieren
        - EPG-Einstellungen > Ort: auf "Lokaler Pfad" setzen
        - EPG-Einstellungen > XMLTV-Pfad: hier zum oben gewählten "Download Folder" navigieren & die .gz Datei auswählen
        - EPG-Einstellungen > EPG Zeitversetzung (Stunden): 1.00
        - EPG-Einstellungen > Zeitversetzung für alle Kanäle übernehmen: ja

**Comment by jnk22** [comment]
Danke für die Anleitung, mache ich dann die Tage :)

**Comment by azrdev** [comment]
@jnk22 ok, sehr gut. Die Info, welche Rytec liste zu welcher m3u passt, fehlt mir (und der Anleitung) halt noch.

**Comment by jnk22** [comment]
Sofern sich da nichts geändert hat wäre das meines Wissens nach nur die deutsche (also inkl. Österreich und Schweiz), habe das aber nie aktiv benutzt und liegt auch schon etwas weiter zurück.

Habe den Startpost jetzt mal aktualisiert, hoffe das passt so :)

**Comment by jnk22** [comment]
Werde für das größere Update die gesamte Struktur der Dokumentation etc. eh nochmal überarbeiten müssen, falls das mit dem EPG so aktuell noch nicht ganz passt, schaue ich dann auch da nochmal drüber.
