### ISSUE TITLE
Internationale Nachrichten-Sender

### ISSUE THREAD

**Issue by jnk22** [jnk22/kodinerds-iptv#119]
London Live
http://bcoveliveios-i.akamaihd.net/hls/live/217434/3083279840001/master.m3u8

Three
http://mediaworks-i.akamaihd.net/hls/live/220435/3812193411001/3news_live/master.m3u8

ALBUK 2
http://188.138.17.8:1935/albuk/albukplus.stream/playlist.m3u8

Arirang World
http://amdlive.ctnd.com.edgesuite.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8

BBC World News
http://hlslive.lcdn.une.net.co/v1/AUTH_HLSLIVE/BBCW/tu1_1.m3u8

BFM TV
http://csm-e.dai.bfmtv.com/csm/live/109797390.m3u8

Bloomberg TV Europe
http://cdn-videos.akamaized.net/btv/desktop/akamai/europe/live/primary.m3u8

Channel News Asia
http://imtcnai-lh.akamaihd.net/i/cnai_main@334572/master.m3u8

CHCH
http://52.86.189.59:1935/live/news/chunklist_w479079800.m3u8

France 24
http://static.france24.com/live/F24_EN_LO_HLS/live_web.m3u8

KTVU Fox 2
http://play-prod1.live.anvato.net/server/play/ktvutestctg/master.m3u8

MSNBC
http://tvemsnbc-lh.akamaihd.net/i/nbcmsnbc_1@122532/index_4296_av-p.m3u8

Newsmax
http://ooyalahd2-f.akamaihd.net/i/newsmax02_delivery@119568/index_2528_av-p.m3u8

Press TV
http://178.32.255.199:1935/live/ptven/playlist.m3u8

Rai News 24
http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=489110&dem=3

RT Espanol
http://rt.ashttp14.visionip.tv/live/RT_en_Espanol-HD/chunklist.m3u8

RT Global
http://rt.ashttp14.visionip.tv/live/rt-global-live-HD/playlist.m3u8

RTE News
http://wmsrtsp1.rte.ie/live/android.sdp/playlist.m3u8

Sky News
http://skydvn-nowtv-atv-prod.skydvn.com/atv/skynews/1404/live/04.m3u8
http://skydvn-nowtv-atv-prod.skydvn.com/atv/skynews/1404/live/06.m3u8

TRT World
http://trtcanlitv-lh.akamaihd.net/i/TRTWORLD_1@321783/master.m3u8

WGN Chicago
http://wgntribune-lh.akamaihd.net/i/WGNPrimary_1@304622/master.m3u8

**Comment by wellivea1** [comment]
The MSNBC link no longer works.
