### ISSUE TITLE
Änderung rbb Event-Kanäle

### ISSUE THREAD

**Issue by herrTravolta** [jnk22/kodinerds-iptv#136]
Beim Event-Kanal(en) des rbb (ÖR) eventuell eine Änderung:
siehe radioeins.de - aktuell von 7-10 Uhr der Live-Webstream.
Die benutzen dafür einen rbb-Eventkanal. Und zwar diesen hier:

#EXTINF:-1 tvg-name="RBB Event 1" tvg-id="RBBEvent1.de" group-title="Extra" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/rbb.png",RBB Event 1
_http://rbbevent01-lh.akamaihd.net/i/rbbevent01_nongeo@22155/index_2692_av-p.m3u8_

Nennt sich also ..event01.. Schreibweise ist ähnlich der bisherigen.
Dort läuft außerhalb des Livestream auch ein Dia - für Testzwecken hilfreich.

**Comment by jnk22** [comment]
@herrTravolta
Habe die Stream URLs jetzt ausgetauscht. Der alte Stream hat zumindest während meinem Test nicht mehr funktioniert.
Alter Stream ist jetzt auf der "tv_broken" Liste.
