### ISSUE TITLE
ÖR rbb Sender mit 720p Stream

### ISSUE THREAD

**Issue by herrTravolta** [jnk22/kodinerds-iptv#144]
Die beiden ÖR Sender der rbb (Berlin u. Brandenburg) haben nun endlich auch einen 720p Stream.

#EXTINF:-1 tvg-name="rbb HD Berlin" tvg-id="rbbBerlin.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/rbbhd.png" group-title="IPTV",rbb Berlin HD
https://rbblive-lh.akamaihd.net/i/rbb_berlin@144674/index_8_av-p.m3u8

#EXTINF:-1 tvg-name="rbb HD Brandenburg" tvg-id="rbbBrandenburg.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/rbbhd.png" group-title="IPTV",rbb Brandenburg
http://rbblive-lh.akamaihd.net/i/rbb_brandenburg@349369/index_8_av-p.m3u8

**Comment by Cris--** [comment]
rbblive doesn't work anymore.. :(
