### ISSUE TITLE
Fernsehsender "Dubai One" offline

### ISSUE THREAD

**Issue by jnk22** [jnk22/kodinerds-iptv#147]
Fernsehsender "Dubai One" scheint offline zu sein, daher ggf. entfernen.

**Comment by mttronc** [comment]
Neue URL: `http://dmithrvll.cdn.mangomolo.com/dubaione/smil:dubaione.smil/playlist.m3u8`

**Comment by jnk22** [comment]
Perfekt, danke!

Habe jetzt mal testweise den hochauflösenden Stream eingetragen.
http://dmithrvll.cdn.mangomolo.com/dubaione/smil:dubaione.smil/chunklist_b1800000.m3u8
