### ISSUE TITLE
Skandinavische Sender

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#158]
Finland
TV1 : http://yletvhdliveworld-lh.akamaihd.net/i/yletv1hdworld_1@187592/master.m3u8
TV2: http://yletvhdliveworld-lh.akamaihd.net/i/yletv2hdworld_1@187593/master.m3u8

Island
RUV: http://ruvruverl-live.hls.adaptive.level3.net/ruv/ruverl/index.m3u8

Dänemark
TV2 Bornholm: http://live.tv2bornholm.dk/stream/live/master.m3u8
TV2 News: http://tv2danmark-tv2news-live.hls.adaptive.level3.net/tv2danmark/tv2news/master3200kbps.m3u8
TV4 Event: http://tv4events3-lh.akamaihd.net/i/EXTRAEVENT14_1@324065/master.m3u8

**Comment by bjoerns1983** [comment]
TV1 wird hinzugefügt, TV2 ist Geoblocked, TV2Bornholm zeigt Bildefehler. Restlichen Links sind nicht mehr aktuell.
Falls diese Sender hinzugefügt werden sollen bitte PR.
