### ISSUE TITLE
USA-Sender

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#159]
Kiro 7: http://cmghlslive-i.akamaihd.net/hls/live/224708/KIRO/904k/prog.m3u8
CBS Los Angeles: http://play-prod1.live.anvato.net/server/play/cbslocal-kcbsx-dfp/master.m3u8
CBS Sacramento: http://play-prod1.live.anvato.net/server/play/cbslocal-kmax-dfp/master.m3u8
CBS San Francisco: http://play-prod1.live.anvato.net/server/play/cbslocal-kpix-dfp/master.m3u8
CBS 47: http://cmghlslive-i.akamaihd.net/hls/live/224714/WJAX/904k/prog.m3u8
NBC Jacksonville: http://knbclive-f.akamaihd.net/i/knbca1_1@13988/master.m3u8
NBC Golf: http://live-trl102.abweb.com/liveabtrl102/ngrp:golfchannel.stream_bis/chunklist_b2096000.m3u8
MiamiTV: http://usaserver.miamitvchannel.com/miamitv/smil:miamitv/playlist.m3u8
C-Span1: http://cspan1-lh.akamaihd.net/i/cspan1_1@304727/index_1000_av-p.m3u8?sd=10&rebase=on
C-Span2: http://cspan2-lh.akamaihd.net/i/cspan2_1@304728/index_1000_av-p.m3u8?sd=10&rebase=on
C-Span3: http://cspan3-lh.akamaihd.net/i/cspan3_1@304729/index_1000_av-p.m3u8?sd=10&rebase=on
RevN: http://dcunilive16-lh.akamaihd.net/i/dclive_1@305811/master.m3u8
MeTV: http://video.metv.com/metv/index.m3u8
Fox30: http://cmghlslive-i.akamaihd.net/hls/live/224710/WFOX/904k/prog.m3u8
Fox25: http://cmghlslive-i.akamaihd.net/hls/live/224671/WFXT/904k/prog.m3u8
Fox23: http://cmghlslive-i.akamaihd.net/hls/live/224709/KOKI/904k/prog.m3u8
Fox5: https://api.new.livestream.com/accounts/2363281/events/1763520/live.m3u8
Pentagon Channel: http://dmatpclivestream-lh.akamaihd.net/i/dodnews1_1@75655/master.m3u8
Country Network: https://dcunilive2-lh.akamaihd.net/i/dclive_1@390829/master.m3u8
WXIA: https://wxia-lh.akamaihd.net/i/WXIALive_1@342562/master.m3u8
KNTV: https://kntvlive-f.akamaihd.net/i/kntvb2_1@15530/master.m3u8
KNTV Traffic: https://kntvlive-f.akamaihd.net/i/kntvb1_1@15530/master.m3u8
WXXV25: https://api.new.livestream.com/accounts/22998687/events/6864865/live.m3u8
Town of Vienna: https://granicusliveus2-a.akamaihd.net/vienna-va/G1359_003/playlist.m3u8
NBC 10: https://kten-lh.akamaihd.net/i/KTEN_1079@5589/master.m3u8
NBC 4: https://wnbclive-f.akamaihd.net/i/wnbca1_1@13992/master.m3u8
WRCTV: https://wrclive-f.akamaihd.net/i/wrcb1_1@46880/master.m3u8
WRCTV WhiteHouse: https://wrclive-f.akamaihd.net/i/wrcb2_1@46880/master.m3u8
Olympics Channel 1: https://live.olympicchannel.com/ocs/channel01b/master.m3u8
Olympics Channel 2: https://live.olympicchannel.com/ocs/channel02b/master.m3u8
Olympics Channel 3: https://live.olympicchannel.com/ocs/channel03b/master.m3u8
Olympics Channel 4: https://live.olympicchannel.com/ocs/channel04b/master.m3u8
Olympics Channel 5: https://live.olympicchannel.com/ocs/channel05b/master.m3u8

**Comment by marcandrebrandt** [comment]
Country Network: https://dcunilive2-lh.akamaihd.net/i/dclive_1@390829/master.m3u8

**Comment by EmBeEins** [comment]
CMC USA: http://cmctv.ios.internapcdn.net/cmctv_vitalstream_com/live_1/CMCUSA/CMCUSA.m3u8

**Comment by EmBeEins** [comment]
#EXTINF:0,Olympics Channel
https://live.olympicchannel.com/ocs/channel01b/master.m3u8
#EXTINF:0,Olympics Channel 2
https://live.olympicchannel.com/ocs/channel02b/master.m3u8
#EXTINF:0,Olympics Channel 3
https://live.olympicchannel.com/ocs/channel03b/master.m3u8
#EXTINF:0,Olympics Channel 4
https://live.olympicchannel.com/ocs/channel04b/master.m3u8
#EXTINF:0,Olympics Channel 5
https://live.olympicchannel.com/ocs/channel05b/master.m3u8

**Comment by bjoerns1983** [comment]
Stichprobenartig geprüft, die meisten Links sind nach so langer Zeit.
Falls das ganze noch hinzugefügt werden soll bitte als PR einreichen.
