### ISSUE TITLE
weitere BibelTV-Streams

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#160]
Bibel-TV Impuls: http://bibeltv02.iptv-playoutcenter.de/bibeltv02/bibeltv02.stream_1/playlist.m3u8
Bibel-TV Musik: http://bibeltv03.iptv-playoutcenter.de/bibeltv03/bibeltv03.stream_1/playlist.m3u8

**Comment by freddii** [comment]
fixed in https://github.com/jnk22/kodinerds-iptv/pull/330
