### ISSUE TITLE
Event-Streams

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#161]
Tagesschau24 Event1: http://tagesschau-lh.akamaihd.net/i/tagesschau_2@119232/master.m3u8
SR Event: http://live_sr-lh.akamaihd.net/i/sr_universal01@105663/master.m3u8
SR Landtag: http://sr_landtag-lh.akamaihd.net/i/sr_landtag@166846/master.m3u8
Ran 1: http://ran01de-live.hls.adaptive.level3.net/sevenone/ran01de/ipad.m3u8
Ran 2: http://ran02de-live.hls.adaptive.level3.net/sevenone/ran02de/ipad.m3u8
Ran 3: http://ran03dach-live.hls.adaptive.level3.net/sevenone/ran03dach/ipad.m3u8
Ran 4: http://ran04dach-live.hls.adaptive.level3.net/sevenone/ran04dach/ipad.m3u8
BILD.de 1: http://bildlivehls-lh.akamaihd.net/i/Bildlive_1@107601/master.m3u8
BILD.de 2: http://bildlivehls-lh.akamaihd.net/i/redcarpet_1@107601/master.m3u8
DFB 1: https://dfbliveuniversal-lh.akamaihd.net/i/dfb_live_1_1@180340/index_2000_av-b.m3u8?sd=10&b=0-10000
DFB 2: https://dfbliveuniversal-lh.akamaihd.net/i/dfb_live_2_1@180341/index_2000_av-b.m3u8?sd=10&b=0-10000

**Comment by bjoerns1983** [comment]
Links down. Falls die Sender aufgenommen werden sollen bitte PR einreichen.
