### ISSUE TITLE
Internationale Sender

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#163]
Türkei
TRT1: http://trtcanlitv-lh.akamaihd.net/i/TRT1HD_1@181842/master.m3u8
TRT Spor: http://sol.trtcdn.com/tv/trtspor/smil:trtspor.smil/HasBahCa.m3u8
CNN Turk: http://live.netd.com.tr/S1/HLS_LIVE/cnn_turk/1000/prog_index.m3u8

Niederlande
Omroep Gelderland: http://web.omroepgelderland.nl/live/livetv.m3u8
Limburg: http://urtmpkal-f.akamaihd.net/i/1ef9833b4_1@128347/index_1_av-p.m3u8
Zeeland: http://livestream.zeelandnet.nl:1935/live/omroepzeeland_tv_1500k.sdp/playlist.m3u8
RTV Drente: http://stream.rtvdrenthe.nl/tv/tvstream1/playlist.m3u8
Radio Veronica: http://b2b.rr.kpnstreaming.nl/hls/live/b2b/skyradio/live/skyradio/veronica/1600.m3u8

Irland
RTE1: https://cdn.rasset.ie/hls-live/_definst_/rte1/rte1-360.m3u8
RTE2: https://cdn.rasset.ie/hls-live/_definst_/rte2/rte2-360.m3u8
RTE Jr: https://cdn.rasset.ie/hls-live/_definst_/rtejr/rtejr-360.m3u8

Italien
Rai Premium: http://b2everyrai-lh.akamaihd.net/i/raipremium_1@181837/master.m3u8
Rai Storia: http://everyrai-lh.akamaihd.net/i/raistoria_1@308058/master.m3u8
Rai Yoyo: http://b2everyrai-lh.akamaihd.net/i/raiyoyo_1@191405/master.m3u8
Sky TG24: http://skyianywhere2-i.akamaihd.net/hls/live/200275/tg24/playlist.m3u8

Norwegen
MTV: http://unilivemtveu-lh.akamaihd.net/i/mtvno_1@346424/master.m3u8

Belgien
TV Limburg: http://urtmpkal-f.akamaihd.net/i/1ef9833b4_1@128347/master.m3u8

Kanada
Weather Channel: https://weather-lh.akamaihd.net/i/twc_1@92006/master.m3u8

VAE
Dubai TV: http://dmi.mangomolo.com:1935/dubaitv/smil:dubaitv.smil/gmswf.m3u8
Al Jazeera Doc: http://aljazeera-doc-apple-live.adaptive.level3.net/apple/aljazeera/hq-doc/800kStream.m3u8

Portugal
TVI24: http://video-live.iol.pt:1935/live_tvi24/smil:LIVE_TVI24/playlist.m3u8

Frankreich 
Grand Lille: http://str82.creacast.com/grandlilletv/smil:grandlilletv.smil/f1tv.m3u8

Deutschland
Souvenirs from earth: http://live.streaming.rngd.cloud/sfe/live/playlist.m3u8

**Comment by EmBeEins** [comment]
Belgien
TV Limburg: http://urtmpkal-f.akamaihd.net/i/1ef9833b4_1@128347/master.m3u8

Kanada
Weather Channel: https://weather-lh.akamaihd.net/i/twc_1@92006/master.m3u8

VAE
Dubai TV: http://dmi.mangomolo.com:1935/dubaitv/smil:dubaitv.smil/gmswf.m3u8
Al Jazeera Doc: http://aljazeera-doc-apple-live.adaptive.level3.net/apple/aljazeera/hq-doc/800kStream.m3u8

Portugal
TVI24: http://video-live.iol.pt:1935/live_tvi24/smil:LIVE_TVI24/playlist.m3u8

Frankreich 
Grand Lille: http://str82.creacast.com/grandlilletv/smil:grandlilletv.smil/f1tv.m3u8

Deutschland
Souvenirs from earth: http://live.streaming.rngd.cloud/sfe/live/playlist.m3u8

**Comment by MarioChemtz** [comment]
Südafrika
CMTV (Cape Media TV): http://video1.qac.ro:1935/live/live-vbr.smil/chunklist_w520878631_b996000_sleng.m3u8

**Comment by EmBeEins** [comment]
Schweiz5: http://194.29.5.2:1935/live/myStream/playlist.m3u8

**Comment by bjoerns1983** [comment]
Links down. Falls die Sender aufgenommen werden sollen bitte PR einreichen.
