### ISSUE TITLE
Regional-Programme RTL/SAT1 

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#165]
RTL West (18:00-18:30): http://rtlwest-i.akamaihd.net/hls/live/220067/rtlwest/master.m3u8
RTL Nord (18:00-18:30): http://l2117.insinceurope.net/ilive2117/stream_01.stream/playlist.m3u8

SAT1 Bayern: http://stream.sat1bayern.de:1935/live/Sat1Schedule_01//playlist.m3u8
SAT1 Hamburg: http://llnw.insinceurope.net/sat1hh/loop_hh/playlist.m3u8
SAT1 Hannover: http://llnw.insinceurope.net/sat1ha/loop_ha/playlist.m3u8

**Comment by bjoerns1983** [comment]
Links down. Falls die Sender aufgenommen werden sollen bitte PR einreichen.
