### ISSUE TITLE
Radio NRW - Genre

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#168]
Deine Lounge: http://rnrw.cast.addradio.de/rnrw-0159/deinlounge/high/stream.mp3?ar-purpose=web
80er: http://rnrw.cast.addradio.de/rnrw-0185/dein80er/high/stream.mp3
90er: http://rnrw.cast.addradio.de/rnrw-0185/dein90er/high/stream.mp3
Rock: http://rnrw.cast.addradio.de/rnrw-0185/deinrock/high/stream.mp3
Schlager: http://rnrw.cast.addradio.de/rnrw-0185/deinschlager/high/stream.mp3
Deutschpop: http://rnrw.cast.addradio.de/rnrw-0185/deindeutschpop/high/stream.mp3
Top40: http://rnrw.cast.addradio.de/rnrw-0185/deintop40/high/stream.mp3
Urban: http://rnrw.cast.addradio.de/rnrw-0185/deinurban/high/stream.mp3
Weihnachten: http://rnrw.cast.addradio.de/rnrw-0185/deinevent/high/stream.mp3

**Comment by bjoerns1983** [comment]
Stream sind identisch mit denen die Radio Köln sendet und die mit #622 hinzugefügt wurden.
