### ISSUE TITLE
UK TV

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#169]
Hillsong Channel: http://acaooyalahd2-lh.akamaihd.net/i/TBN02_delivery@186240/master.m3u8
Chelsea TV: http://ooyalahd2-f.akamaihd.net/i/chelsea02_delivery@145821/master.m3u8
BBC Arabia: http://bbcwshdlive01-lh.akamaihd.net/i/atv_1@61433/master.m3u8
MTV Music24: http://unilivemtveu-lh.akamaihd.net/i/mtvmusic24_1@134926/master.m3u8

**Comment by EmBeEins** [comment]
MTV Music24: http://unilivemtveu-lh.akamaihd.net/i/mtvmusic24_1@134926/master.m3u8

**Comment by bjoerns1983** [comment]
Links funktionieren nicht mehr
