### ISSUE TITLE
Local TV

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#170]
FRF1: http://62.113.221.100/friesischerRundfunk-live/_definst_/mp4:livestream/playlist.m3u8
EV1: http://62.113.221.6/ev1tv-live/_definst_/mp4:livestream/playlist.m3u8
Tide Hamburg : http://62.113.210.8/tide-rtplive/mp4:liveplayout.stream/chunklist_w1838803172.m3u8

**Comment by MarioChemtz** [comment]
Hier noch 2 polnische lokale Sender:

Sfera TV: http://stream.sferatv.pl:1935/sferalive/smil:sferalive.smil/playlist.m3u8
Telewizja WTK: https://redir.cache.orange.pl/jupiterecdn/o2-cl3//live/wtk-b-wtktv/live.m3u8

**Comment by bjoerns1983** [comment]
FRF1: https://583548fa0d82b.streamlock.net/friesischerRundfunk-live/_definst_/mp4:friesischerrundfunk/playlist.m3u8
EmsTV: https://5889e7d0d6e28.streamlock.net/ev1tv-live/_definst_/mp4:livestream/playlist.m3u8
Tide TV: https://5889e7d0d6e28.streamlock.net/tide-live/_definst_/smil:livestream.smil/playlist.m3u8

Sfera TV: http://stream.sferatv.pl:1935/sferalive/smil:sferalive.smil/playlist.m3u8

WTK funktioniert nicht mehr
