### ISSUE TITLE
Visual Radio

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#171]
Niederlande 🇳🇱 
NPO1: http://livestreams.omroep.nl/live/npo/visualradio/radio1/radio1.isml/radio1.m3u8?hash=749c8354dc5b6ed4e0d0b4f91fbf2579&protection=url
NPO2: http://livestreams.omroep.nl/live/npo/visualradio/radio2/radio2.isml/radio2.m3u8?hash=749c8354dc5b6ed4e0d0b4f91fbf2579&protection=url
NPO3: http://livestreams.omroep.nl/live/npo/visualradio/3fm/3fm.isml/3fm.m3u8?hash=749c8354dc5b6ed4e0d0b4f91fbf2579&protection=url
NPO4: http://livestreams.omroep.nl/live/npo/visualradio/radio4/radio4.isml/radio4.m3u8?hash=749c8354dc5b6ed4e0d0b4f91fbf2579&protection=url
NPOfunX: http://livestreams.omroep.nl/live/npo/visualradio/funx/funx.isml/funx.m3u8?hash=749c8354dc5b6ed4e0d0b4f91fbf2579&protection=url
Radio Veronica: http://b2b.rr.kpnstreaming.nl/hls/live/b2b/skyradio/live/skyradio/veronica/1600.m3u8
Q-Music: https://102793ooyala-lh.akamaihd.net/i/depers02_delivery@381748/master.m3u8
Radio 538: http://538hls.lswcdn.triple-it.nl/content/538webcam/538webcam_0.m3u8
Slam: http://hls.slam.nl/streaming/hls/SLAM!/med_1500000/playlist.m3u8

Frankreich 🇫🇷 
Funradio: http://stream-03.ix7.dailymotion.com/54/dm/3/xxtuy6/live-4.m3u8

Deutschland 🇩🇪 
SWR3: http://swr3visual-lh.akamaihd.net/i/swr3visual_live@6410/master.m3u8
DasDing: http://swrdasding-lh.akamaihd.net/i/dasdingvisual_live@6416/master.m3u8
UnserDing: https://srunserding-lh.akamaihd.net/i/visualradio_ud@197013/master.m3u8

Argentinien 🇦🇷 
Cool 103.7: http://ar.solumedia.com.ar:1935/cool/hd/playlist.m3u8

Österreich 🇦🇹 
Ö3: http://apasfiisl.apa.at/ipad/oe3hdfb/orf.sdp

**Comment by gsantner** [comment]
Ö3 funktioniert nicht (AT IP)

**Comment by EmBeEins** [comment]
Bei mir geht das 😉

**Comment by gsantner** [comment]
komisch.. welcher user-agent? Habs mit vlc und mplayer verducht

**Comment by EmBeEins** [comment]
Direkt im Safari Browser geöffnet

**Comment by gsantner** [comment]
ok. Kann man dash auch irgendwie in m3u8 geben?

**Comment by gsantner** [comment]
btw: <http://apasfiisl.apa.at/ipad/oe3sd/orf.sdp/playlist.m3u8> ;)

**Comment by gsantner** [comment]
Ah, ok, das ist der studio tream, leider nicht jener den ich gesucht habe :D. BTW: hier ist der m3u8 link dazu <http://apasfiisl.apa.at/ipad/oe3hdfb/orf.sdp/playlist.m3u8>

**Comment by bjoerns1983** [comment]
Bitte als PR einreichen wenn es hinzugefügt werden soll.
