### ISSUE TITLE
Europa Parlament 

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#172]
EbS: http://ott.ec.streamcloud.be/live/disk1/EBS/hls_or/EBS.m3u8
EbS+: http://ott.ec.streamcloud.be/live/disk1/EBSplus/hls_or/EBSplus.m3u8

Parlamentsfernsehen Österreich 🇦🇹 : http://parlament.sf.apa.at/parlament_live1/parlament.smil/playlist.m3u8 

Niederländisches Parlament 🇳🇱 : http://tweedekamerlive.download.kpnstreaming.nl/plenairezaal/index.m3u8

**Comment by EmBeEins** [comment]
Parlamentsfernsehen Österreich: http://parlament.sf.apa.at/parlament_live1/parlament.smil/playlist.m3u8

**Comment by EmBeEins** [comment]
Niederländisches Parlament: http://tweedekamerlive.download.kpnstreaming.nl/plenairezaal/index.m3u8

**Comment by bjoerns1983** [comment]
Neue Links:
EbS: https://euc-live.fl.freecaster.net/live/eucom/ebs-audio_int=96000-video=2600000.m3u8
EbS+: https://euc-live.fl.freecaster.net/live/eucom/ebsp-audio_int=96000-video=2600000.m3u8
