### ISSUE TITLE
Radiosender PL

### ISSUE THREAD

**Issue by MarioChemtz** [jnk22/kodinerds-iptv#174]
Radio ESKA: http://waw.ic.smcdn.pl/t042-1.aac?timestamp=1507380750&hash=5d0d14a9038fbb82453d7e0a25d1d928

Radio WAWA: http://waw.ic.smcdn.pl/t050-1.aac?timestamp=1507381818&hash=f88be5a0718ca2eb00a594d08c8200a6

**Comment by herrTravolta** [comment]
Beide Sender verlangen HTTP-Authentication (login)
Getestet mit VLC und Firefox jeweils unter Android

**Comment by MarioChemtz** [comment]
Bei beiden Sendern wird eine Authentication über Timestamp und Hash.
Diese hat sich hat sich geändert, anbei die aktuellen Links.

Radio ESKA: http://waw.ic.smcdn.pl/t042-1.aac?timestamp=1508569242&hash=8264c61b9048b6ce56213609ba6ff130

Radio WAWA: http://waw.ic.smcdn.pl/t050-1.aac?timestamp=1508570173&hash=f4be8d9515eb6da5585eccd45790cb65

Ich beobachte mal die nächsten Wochen, ob sich der Login bleibt oder sich regelmäßig ändert.
