### ISSUE TITLE
Änderungen Lokalsender Bayern, Berlin

### ISSUE THREAD

**Issue by herrTravolta** [jnk22/kodinerds-iptv#176]
Geänderte Lokal-TV Streams:
a.tv (www.augsburg.tv) -aktuell nur noch SD Stream-
https://586c13b083c0d.streamlock.net/augsburgtv/augsburgtv.stream_2/playlist.m3u8

münchen.tv -HD Stream 720p-
https://586c13b083c0d.streamlock.net/muenchentv/muenchentv.stream_1/playlist.m3u8

tv.berlin -HD Stream 720p-
https://sdn-global-live-http-cache.3qsdn.com/live/_definst_/mp4:6119_Q7XY8ZNm9PBKywV/playlist.m3u8

**Comment by plata** [comment]
@herrTravolta am Besten die Änderungen direkt als Pull Request einreichen, dann kann @jnk22 sie leichter übernehmen.

**Comment by freddii** [comment]
urls are outdated
