### ISSUE TITLE
Magenta Music 360

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#177]
HD

- https://streaming-magenta-music-360.akamaized.net/hls/live/504581/magentamusik1/index.m3u8 

- https://streaming-magenta-music-360.akamaized.net/hls/live/504582/magentamusik2/index.m3u8 

360 Grad

- https://streaming-magenta-music-360.akamaized.net/hls/live/504583/mm360_vr1/index.m3u8

- https://streaming-magenta-music-360.akamaized.net/hls/live/504584/mm360_vr2/index.m3u8 

- https://streaming-magenta-music-360.akamaized.net/hls/live/504585/mm360_vr3/index.m3u8

- https://streaming-magenta-music-360.akamaized.net/hls/live/504586/mm360_vr4/index.m3u8

**Comment by bjoerns1983** [comment]
Links nicht mehr aktuell.
