### ISSUE TITLE
Franken Fernsehen https

### ISSUE THREAD

**Issue by herrTravolta** [jnk22/kodinerds-iptv#183]
FF jetzt mit https Stream ( https://www.frankenfernsehen.tv/livestream/ ) 
https://586dce1287bfd.streamlock.net/frankentv/frankentv.stream_1/playlist.m3u8

**Comment by plata** [comment]
@herrTravolta am Besten die Änderungen direkt als Pull Request einreichen, dann kann @jnk22 sie leichter übernehmen.

**Comment by freddii** [comment]
fixed in  #327
