### ISSUE TITLE
Playlists should stay rfc compilant (when using the extended info format)

### ISSUE THREAD

**Issue by LipkeGu** [jnk22/kodinerds-iptv#184]
* When Playlists are utf-8 encoded, then they should have the Extension "m3u8" instead of "m3u" (see RFC)
* The Playlists contains Extended informations so the Playlist should be "m3u8"
* Many Players expecting "m3u8"

So we should rename them... to m3u8

**Comment by bjoerns1983** [comment]
Thx for your input.
