### ISSUE TITLE
ZDF stream not working on Kodi (with fix)

### ISSUE THREAD

**Issue by tobiasneumann** [jnk22/kodinerds-iptv#190]
The link: http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_3096_av-p.m3u8
Doesn't work (at least on my) Kodi (raspberry PI 2 with openELEC) but works on my Laptop (Fedora 27) with VLC.

It's also one of the few links without SSL.

I changed it to (SSL + ?sd=10&rebase=on) which then also works on Kodi:
https://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_3096_av-p.m3u8?sd=10&rebase=on

**Comment by jnk22** [comment]
The new URL uses SSL, so this should probably be working again.
Otherwise feel free to reopen this issue.
