### ISSUE TITLE
Bloomberg geänderte Streams

### ISSUE THREAD

**Issue by herrTravolta** [jnk22/kodinerds-iptv#191]
Bloomberg Europe & US
(Stream in der Playlist läuft nicht mehr)
EU:
https://bblive-liveprodeuwest.hs.llnwd.net/btv/desktop/eu_live.m3u8
US:
https://liveproduseast.global.ssl.fastly.net/btv/desktop/us_live.m3u8

**Comment by plata** [comment]
@herrTravolta am Besten die Änderungen direkt als Pull Request einreichen, dann kann @jnk22 sie leichter übernehmen.

**Comment by freddii** [comment]
fixed in #199
