### ISSUE TITLE
Änderung WDR TV Livestream

### ISSUE THREAD

**Issue by herrTravolta** [jnk22/kodinerds-iptv#193]
http://wdrfsgeo-lh.akamaihd.net/i/wdrfs_geogeblockt@530016/index_3776_av-p.m3u8
funktioniert nicht mehr. 

siehe  https://www.kodinerds.net/index.php/Thread/56713-Kodinerds-IPTV-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len/?postID=451982#post451982

**Comment by jnk22** [comment]
Habe das gestern wieder geändert nach dem Bericht auf kodinerds.net.

https://github.com/jnk22/kodinerds-iptv/commit/576b30a64e732f12e1b660b5eedc906b6a3f4b9a

Sollte eigtl. so funktionieren. Geht's noch nicht wieder bei dir?

**Comment by herrTravolta** [comment]
Funktioniert alles, #193 kann geschlossen werden.
