### ISSUE TITLE
Radio Bob Onlinestreams

### ISSUE THREAD

**Issue by stguenth** [jnk22/kodinerds-iptv#197]
Radio Bob Harte Saite: http://streams.radiobob.de/bob-hartesaite/mp3-192/mediaplayer
Radio Bob Alternative: http://streams.radiobob.de/bob-alternative/mp3-192/mediaplayer
Radio Bob Best of Rock: http://streams.radiobob.de/bob-bestofrock/mp3-192/mediaplayer
Radio Bob Rockhits: http://streams.radiobob.de/bob-rockhits/mp3-192/mediaplayer
Radio Bob Classicrock: http://streams.radiobob.de/bob-classicrock/mp3-128/mediaplayer
Radio Bob Wacken: http://streams.radiobob.de/bob-wacken/mp3-192/mediaplayer

**Comment by herrTravolta** [comment]
Hab mal durchgetestet, alle radiobob-Streams sind auch als https://-Stream verfügbar.

**Comment by herrTravolta** [comment]
Hab mal durchgetestet, alle radiobob-Streams sind auch als https://-Stream verfügbar und Kodi kann diese auch abspielen.

**Comment by stguenth** [comment]
Ich habe die einfach mal aus meinem "radiotray" hier reinkopiert. Da stehen die schon länger so drin - Habe gar nicht über verschlüsselt oder oder unverschlüsselt nachgedacht... Wäre aber super, wenn die Streams in die Liste aufgenommen werden!
