### ISSUE TITLE
NDR Event-Kanäle

### ISSUE THREAD

**Issue by herrTravolta** [jnk22/kodinerds-iptv#200]
Während des ESC wurden vom NDR neue Event-Kanäle benutzt:

NDR Event 1
https://ndrevent-lh.akamaihd.net/i/ndrevent_1@409066/master.m3u8
NDR Event 2
https://ndrevent-lh.akamaihd.net/i/ndrevent_2@429805/master.m3u8

**Comment by freddii** [comment]
fixed in  #334
