### ISSUE TITLE
Pflege der Liste(n)

### ISSUE THREAD

**Issue by kdeiss** [jnk22/kodinerds-iptv#203]
Erst mal ganz herzlichen Dank für diese Arbeit. Danach habe ich schon längere Zeit gesucht!
Mir war aufgefallen das doch eine größere Anzahl von Streams nicht arbeitet. Ich habe deshalb ein kleines Script gebaut mit welchem man einen online check der m3u Datei vornehmen kann.

Das Script habe ich getestet mit Linux Mint 17.x und einem aktuellen Raspian. Voraussetzung ist ein aktueller vlc. Die Arbeitsweise des Scriptes ist einfach

•	Download einer aktuellen Liste von "https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/iptv/kodi/kodi_tv.m3u"
•	Extrahieren der URL's aus dieser Datei und Übergabe an den vlc, der den Stream in eine Datei speichern soll
•	Überwachung der vom VLC erzeugten Datei auf Wachstum. Findet das statt wird der Link als OK angenommen, ansonsten als offline
•	Sammeln der online Links in einer neuen Datei / Erzeugung eines Logs, sowie diverse Statistikdateien

Mir sind die Probleme mit den Eventstreams bekannt, da kann man natürlich nichts machen, aber da sind eine ganze Reihe von Streams die dauerhaft offline sind. Vielleicht kann man das Script als Arbeitsansatz benutzen um ein paar Leichen abzufischen.......

Das Script kann man hier laden, ist nicht gerade hohe Programmierkunst, aber effektiv. 
[m3ucheck.zip](https://github.com/jnk22/kodinerds-iptv/files/2115355/m3ucheck.zip)

Ich kann das gerne erweitern (z.B. Black/Whitelisten) womit man dann die Eventstreams immer drin halten könnte, egal ob online oder offline. In jedem Fall könnte man so eine Liste generieren, die immer nur die online stehenden Streams abbildet.

Wenn ich alle Eventstreams rausnehme bleiben mehr als 50 Stück ziemlich dauerhaft offline.

Zum Beispiel:

Mon Jun 18 13:10:02 CEST 2018
24 Vesti http://37.187.158.217:8081/24vesti/24vesti/playlist.m3u8
ALBUK TV http://188.138.17.8:1935/albuk/albuk.stream/playlist.m3u8
Alfa http://37.187.158.217:8081/alfa/tvalfa2/playlist.m3u8
a.tv http://atvhd.iptv-playoutcenter.de/atvHD/ngrp:atvhd.stream_all/playlist.m3u8
BBC World News http://hlslive.lcdn.une.net.co/v1/AUTH_HLSLIVE/BBCW/tu1_1.m3u8
BFMTV http://csm-e.dai.bfmtv.com/csm/live/109797390.m3u8
Capital TV http://ooyalahd2-f.akamaihd.net/i/globalradio01_delivery@156521/index_1500_av-b.m3u8
center.tv Düsseldorf https://sdn-global-live-http-cache.3qsdn.com/live/_definst_/smil:3045-mbr.smil/playlist.m3u8
Channel NewsAsia http://imtcnai-lh.akamaihd.net/i/cnai_main@334572/index_4_av-b.m3u8
CHCH https://bcovlive-a.akamaihd.net/45a29af6ec4341539ddd3dd505c4b669/us-west-2/5644964886001/playlist.m3u8
Create & Craft TV http://live.cc.simplestreamcdn.com/live/isd_sdi4/bitrate1.isml/bitrate1-audio_track=64000-video=1500000.m3u8
Das Erste HD https://derste247livede.akamaized.net/hls/live/658317/daserste_de/caf607e336145f45de615e6894b7d811/index_7.m3u8
DJing Electro Rock https://www.djing.com/tv/session_electro-rock.m3u8
DJing French touch https://www.djing.com/tv/session_french-touch.m3u8
DJing Hedonist https://www.djing.com/tv/session_hedonist.m3u8
DJing Summer Vibes https://www.djing.com/tv/session_summer-vibes.m3u8
DJing Wild EDM http://www.djing.com/tv/session_wild-edm.m3u8
eRtv https://sdn-global-live-http-cache.3qsdn.com/live/_definst_/mp4:5679_nYMRJQdgpK3WDGr/playlist.m3u8
EWTN katholisches TV http://ewtn-hs.mi-cdn.io/ewtn-live-7/_definst_/smil:gerg.smil/chunklist_b900000.m3u8
France 24 http://f24hls-i.akamaihd.net/hls/live/221193/F24_EN_LO_HLS/master_900.m3u8
Hunt Channel https://nimble.huntchannel.tv/abr/huntchannel/playlist.m3u8
Kanal 5 http://37.187.158.217:8081/kanal5/kanal5/playlist.m3u8
KTVU Fox 2 http://play-prod1.live.anvato.net/server/play/ktvutestctg/master.m3u8
KVF http://netvarp.kringvarp.fo/uttanlands/video/playlist.m3u8
M4TV http://streaming.austria24.tv/live/stream_720p/playlist.m3u8
Mello TV http://mellotvnew.tulix.tv/live/smil:mellotv.smil/master.m3u8
MetroTV http://edge.metrotvnews.com:1935/live-edge/smil:metro.smil/chunklist_w1322909361_b1300000_sleng.m3u8
NASA TV https://nasa-i.akamaihd.net/hls/live/253565/NASA-NTV1-Public/master_2000.m3u8
NHK WORLD TV https://nhkwtv-i.akamaihd.net/hls/live/263942/nhkwtv/index_2100.m3u8
nice https://sdn-global-live-http-cache.3qsdn.com/live/_definst_/smil:4195-mbr.smil/chunklist_b2500000.m3u8
NRW TV http://streaming006.broadcast.tneg.de:1935/nrwtv-new/_definst_/smil:nrw.smil/playlist.m3u8
OK Trier http://stream-cdn.ok54.de/hls/ok54.m3u8
ORF SPORT + http://orfs.orf.cdn.ors.at/orfs/q8c.sdp/playlist.m3u8
Press TV http://178.32.255.199:1935/live/ptven/playlist.m3u8
ProTv News http://185.133.64.237/news/stream:1.stream/playlist.m3u8
QVC Beauty & Style https://d2mn03dhv5o3g8.cloudfront.net/live/qvcde_beauty_clean/bitrate1.isml/bitrate1-audio_track=64000-video=1500000.m3u8?DVR
QVC https://d2mn03dhv5o3g8.cloudfront.net/live/qvcde_main_clean/bitrate1.isml/bitrate1-audio_track=64000-video=1500000.m3u8?DVR
QVC PLUS https://d2mn03dhv5o3g8.cloudfront.net/live/qvcde_plus_clean/bitrate1.isml/bitrate1-audio_track=64000-video=1500000.m3u8?DVR
Realitatea TV http://realitatea.m247.ro/hls/live.m3u8
RiC / eoTV https://58b42f6c8c9bf.streamlock.net/live/rictv/playlist.m3u8
SDF http://livestream.goinfo.it/SDFLive/sdfrosnew1/playlist.m3u8
ServusTV HD (AT) http://hdiosstv-f.akamaihd.net/i/servustvhd_1@51229/index_2592_av-p.m3u8
Sitel http://51.255.92.232:1935/sitel/sitel.stream/playlist.m3u8
Sporttime TV 1 http://sporttimelive1.content-cdn.net/livechannel1/smil:switch1.smil/playlist.m3u8?wowzatokenhash=sUTjnxXLdal6Y8bBzs9an_zhqn7VrgWUS5uB8sckoCw=
Sporttime TV 2 http://sporttimelive1.content-cdn.net/livechannel2/smil:switch2.smil/playlist.m3u8?wowzatokenhash=qgtY96D77QocQoiJn6MCsyHbBMGla2uQoQ03XvQYkuE=
Sporttime TV 4 http://sporttimelive1.content-cdn.net/livechannel4/smil:switch4.smil/playlist.m3u8?wowzatokenhash=BhYr7Qu4cZ8LgxWiF7cuQ_hA7sxqdon5Kw0sIHJ7TpM=
Sporttime TV 5 http://live.earthtv.com:1935/edge27/TWLDE/playlist.m3u8?58a36274bbf047f6c3b5cdb1
supertennis.tv http://livetok.flash.glb.ipercast.net/supertennis.tv-live/live_490.stream/playlist.m3u8
TeleBielingue http://livevideo.infomaniak.com/streaming/livecast/telebielinguech/playlist.m3u8
Telma http://37.187.158.217:8081/telma/telma_360pp/playlist.m3u8
TV 538 http://538hls.lswcdn.triple-it.nl/content/538tv/538tv_0.m3u8
TVNZ 1 https://tvnzioslive04-i.akamaihd.net/hls/live/267188/1924997895001/channel1/masterR_5.m3u8
TVNZ 2 https://tvnzioslive05-i.akamaihd.net/hls/live/267189/1924997895001/channel2/masterR_55.m3u8
W24 TV http://ms02.w24.at/hls-live/livepkgr/_definst_/liveevent/livestream3.m3u8

**Comment by plata** [comment]
Gibt es ein GitHub Repository für das Script, damit andere daran mitarbeiten können?

Vorschlag: Wie wäre es, das Script in einer GitHub action täglich/wöchtentlich laufen zu lassen und darüber die fehlerhaften Streams zu reporten (z.B. als status badge in der README)? Weiterhin könnte die action direkt eine Issue erstellen und den fehlerhaften Stream auskommentieren.

**Comment by bjoerns1983** [comment]
Keine Rückmeldung bzgl. des Scripts.
Deswegen vorerst geschlossen.
