### ISSUE TITLE
adultswim - http://www.adultswim.com/streams/ (rick & morty, toonami, etc.)

### ISSUE THREAD

**Issue by AdamNo** [jnk22/kodinerds-iptv#207]
### Live - stream
[tvheadend@tvheadend ~/tmp]$ curl **https://amd.cdn.turner.com/adultswim/big/streams/playlists/live-stream.v3.m3u8**
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=334400,CODECS="avc1.66.30,mp4a.40.5",RESOLUTION=416x234
https://adultswimhls-i.akamaihd.net/hls/live/238460-b/adultswim/main/1/master_Layer0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=554400,CODECS="avc1.66.30,mp4a.40.5",RESOLUTION=416x234
https://adultswimhls-i.akamaihd.net/hls/live/238460-b/adultswim/main/1/master_Layer1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=884400,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=640x360
https://adultswimhls-i.akamaihd.net/hls/live/238460-b/adultswim/main/1/master_Layer2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1445400,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=640x360
https://adultswimhls-i.akamaihd.net/hls/live/238460-b/adultswim/main/1/master_Layer3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2050400,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=852x480
https://adultswimhls-i.akamaihd.net/hls/live/238460-b/adultswim/main/1/master_Layer4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2820400,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=960x540
https://adultswimhls-i.akamaihd.net/hls/live/238460-b/adultswim/main/1/master_Layer5.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3920400,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=1280x720
https://adultswimhls-i.akamaihd.net/hls/live/238460-b/adultswim/main/1/master_Layer6.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5570400,CODECS="avc1.4d4028,mp4a.40.5",RESOLUTION=1920x1080
https://adultswimhls-i.akamaihd.net/hls/live/238460-b/adultswim/main/1/master_Layer7.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=140800,CODECS="mp4a.40.2"
https://adultswimhls-i.akamaihd.net/hls/live/238460-b/adultswim/main/1/master_Layer8.m3u8

### Williams - stream
[tvheadend@tvheadend ~/tmp]$ curl https://adultswim-vodlive.cdn.turner.com/live/williams-stream/stream.m3u8#EXTM3U
#EXT-X-VERSION:5
#EXT-X-STREAM-INF:BANDWIDTH=1236000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/williams-stream/stream_3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=236000,CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/williams-stream/stream_0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=436000,CODECS="avc1.42c014,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/williams-stream/stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=736000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/williams-stream/stream_2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1736000,CODECS="avc1.42c01f,mp4a.40.2",RESOLUTION=852x480
https://adultswim-vodlive.cdn.turner.com/live/williams-stream/stream_4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540
https://adultswim-vodlive.cdn.turner.com/live/williams-stream/stream_5.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720
https://adultswim-vodlive.cdn.turner.com/live/williams-stream/stream_6.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5000000,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080
https://adultswim-vodlive.cdn.turner.com/live/williams-stream/stream_7.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"
https://adultswim-vodlive.cdn.turner.com/live/williams-stream/stream_8.m3u8

### The Eric Andre Show - stream (-marathon)
[tvheadend@tvheadend ~/tmp]$ curl https://adultswim-vodlive.cdn.turner.com/live/eric-andre/stream.m3u8
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-STREAM-INF:BANDWIDTH=1236000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/eric-andre/stream_3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=236000,CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/eric-andre/stream_0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=436000,CODECS="avc1.42c014,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/eric-andre/stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=736000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/eric-andre/stream_2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1736000,CODECS="avc1.42c01f,mp4a.40.2",RESOLUTION=852x480
https://adultswim-vodlive.cdn.turner.com/live/eric-andre/stream_4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540
https://adultswim-vodlive.cdn.turner.com/live/eric-andre/stream_5.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720
https://adultswim-vodlive.cdn.turner.com/live/eric-andre/stream_6.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5000000,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080
https://adultswim-vodlive.cdn.turner.com/live/eric-andre/stream_7.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"
https://adultswim-vodlive.cdn.turner.com/live/eric-andre/stream_8.m3u8

### The Venture Bros. - stream (-marathon)
[tvheadend@tvheadend ~/tmp]$ curl https://adultswim-vodlive.cdn.turner.com/live/venture-bros/stream.m3u8
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-STREAM-INF:BANDWIDTH=1236000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/venture-bros/stream_3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=236000,CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/venture-bros/stream_0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=436000,CODECS="avc1.42c014,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/venture-bros/stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=736000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/venture-bros/stream_2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1736000,CODECS="avc1.42c01f,mp4a.40.2",RESOLUTION=852x480
https://adultswim-vodlive.cdn.turner.com/live/venture-bros/stream_4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540
https://adultswim-vodlive.cdn.turner.com/live/venture-bros/stream_5.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720
https://adultswim-vodlive.cdn.turner.com/live/venture-bros/stream_6.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5000000,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080
https://adultswim-vodlive.cdn.turner.com/live/venture-bros/stream_7.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"
https://adultswim-vodlive.cdn.turner.com/live/venture-bros/stream_8.m3u8

### Of The Air - stream (-marathon)
[tvheadend@tvheadend ~/tmp]$ curl https://adultswim-vodlive.cdn.turner.com/live/off-the-air/stream.m3u8
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-STREAM-INF:BANDWIDTH=1236000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/off-the-air/stream_3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=236000,CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/off-the-air/stream_0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=436000,CODECS="avc1.42c014,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/off-the-air/stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=736000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/off-the-air/stream_2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1736000,CODECS="avc1.42c01f,mp4a.40.2",RESOLUTION=852x480
https://adultswim-vodlive.cdn.turner.com/live/off-the-air/stream_4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540
https://adultswim-vodlive.cdn.turner.com/live/off-the-air/stream_5.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720
https://adultswim-vodlive.cdn.turner.com/live/off-the-air/stream_6.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5000000,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080
https://adultswim-vodlive.cdn.turner.com/live/off-the-air/stream_7.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"
https://adultswim-vodlive.cdn.turner.com/live/off-the-air/stream_8.m3u8

### Superjail! - stream (-marathon)
[tvheadend@tvheadend ~/tmp]$ curl https://adultswim-vodlive.cdn.turner.com/live/superjail/stream.m3u8
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-STREAM-INF:BANDWIDTH=1236000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/superjail/stream_3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=236000,CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/superjail/stream_0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=436000,CODECS="avc1.42c014,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/superjail/stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=736000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/superjail/stream_2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1736000,CODECS="avc1.42c01f,mp4a.40.2",RESOLUTION=852x480
https://adultswim-vodlive.cdn.turner.com/live/superjail/stream_4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540
https://adultswim-vodlive.cdn.turner.com/live/superjail/stream_5.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720
https://adultswim-vodlive.cdn.turner.com/live/superjail/stream_6.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5000000,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080
https://adultswim-vodlive.cdn.turner.com/live/superjail/stream_7.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"
https://adultswim-vodlive.cdn.turner.com/live/superjail/stream_8.m3u8

### Home Movies - stream (-marathon)
[tvheadend@tvheadend ~/tmp]$ curl https://adultswim-vodlive.cdn.turner.com/live/test-2/stream.m3u8
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-STREAM-INF:BANDWIDTH=1236000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/test-2/stream_3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=236000,CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/test-2/stream_0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=436000,CODECS="avc1.42c014,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/test-2/stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=736000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/test-2/stream_2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1736000,CODECS="avc1.42c01f,mp4a.40.2",RESOLUTION=852x480
https://adultswim-vodlive.cdn.turner.com/live/test-2/stream_4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540
https://adultswim-vodlive.cdn.turner.com/live/test-2/stream_5.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720
https://adultswim-vodlive.cdn.turner.com/live/test-2/stream_6.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5000000,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080
https://adultswim-vodlive.cdn.turner.com/live/test-2/stream_7.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"
https://adultswim-vodlive.cdn.turner.com/live/test-2/stream_8.m3u8

### Tim and Eric - stream (-marathon)
[tvheadend@tvheadend ~/tmp]$ curl https://adultswim-vodlive.cdn.turner.com/live/tim-and-eric/stream.m3u8
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-STREAM-INF:BANDWIDTH=1236000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/tim-and-eric/stream_3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=236000,CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/tim-and-eric/stream_0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=436000,CODECS="avc1.42c014,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/tim-and-eric/stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=736000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/tim-and-eric/stream_2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1736000,CODECS="avc1.42c01f,mp4a.40.2",RESOLUTION=852x480
https://adultswim-vodlive.cdn.turner.com/live/tim-and-eric/stream_4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540
https://adultswim-vodlive.cdn.turner.com/live/tim-and-eric/stream_5.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720
https://adultswim-vodlive.cdn.turner.com/live/tim-and-eric/stream_6.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5000000,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080
https://adultswim-vodlive.cdn.turner.com/live/tim-and-eric/stream_7.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"
https://adultswim-vodlive.cdn.turner.com/live/tim-and-eric/stream_8.m3u8

### Toonami - stream / USA VPN needed!!!!
[tvheadend@tvheadend ~/tmp]$ curl https://amd.cdn.turner.com/adultswim/big/streams/playlists/toonami.m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=1016400,CODECS="avc1.66.30,mp4a.40.5",RESOLUTION=640x360
https://adultswimhls-i.akamaihd.net/hls/live/249295/adultswim_6/main/1/stream_Layer1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1016400,CODECS="avc1.66.30,mp4a.40.5",RESOLUTION=640x360
https://adultswimhls-i.akamaihd.net/hls/live/249295-b/adultswim_6/main/1/stream_Layer1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1650000,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=768x432
https://adultswimhls-i.akamaihd.net/hls/live/249295/adultswim_6/main/1/stream_Layer2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1650000,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=768x432
https://adultswimhls-i.akamaihd.net/hls/live/249295-b/adultswim_6/main/1/stream_Layer2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2750000,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=960x540
https://adultswimhls-i.akamaihd.net/hls/live/249295/adultswim_6/main/1/stream_Layer3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2750000,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=960x540
https://adultswimhls-i.akamaihd.net/hls/live/249295-b/adultswim_6/main/1/stream_Layer3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3850000,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=1280x720
https://adultswimhls-i.akamaihd.net/hls/live/249295/adultswim_6/main/1/stream_Layer4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3850000,CODECS="avc1.4d401f,mp4a.40.5",RESOLUTION=1280x720
https://adultswimhls-i.akamaihd.net/hls/live/249295-b/adultswim_6/main/1/stream_Layer4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=686400,CODECS="avc1.66.30,mp4a.40.5",RESOLUTION=640x360
https://adultswimhls-i.akamaihd.net/hls/live/249295/adultswim_6/main/1/stream_Layer5.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=686400,CODECS="avc1.66.30,mp4a.40.5",RESOLUTION=640x360
https://adultswimhls-i.akamaihd.net/hls/live/249295-b/adultswim_6/main/1/stream_Layer5.m3u8

### Rick and Morty - stream (-marathon) USA VPN needed!!!!
[tvheadend@tvheadend ~/tmp]$ curl https://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream.m3u8
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-STREAM-INF:BANDWIDTH=1236000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream_3.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=236000,CODECS="avc1.42c00d,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream_0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=436000,CODECS="avc1.42c014,mp4a.40.2",RESOLUTION=416x234
https://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=736000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=640x360
https://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream_2.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1736000,CODECS="avc1.42c01f,mp4a.40.2",RESOLUTION=852x480
https://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream_4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540
https://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream_5.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3500000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720
https://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream_6.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5000000,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1920x1080
https://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream_7.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"
https://adultswim-vodlive.cdn.turner.com/live/rick-and-morty/stream_8.m3u8

enjoy ;)

**Comment by bjoerns1983** [comment]
Wenn die Sachen aufgenommen werden sollen bitte PR einreichen.
