### ISSUE TITLE
Add Rockantenne Heavy Metal

### ISSUE THREAD

**Issue by ds2k5** [jnk22/kodinerds-iptv#209]
Hi,
can sombody add Rockantenne Heavy Metal to the list: http://bit.ly/kn-kodi  please ?
have found 2 url's

#EXTINF:-1 tvg-name="ROCK ANTENNE Heavy Metal" group-title="Deutschland" radio="true" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/radio/rockantenne.png",ROCK ANTENNE

http://antenneheavy.radio.de/
http://www.rockantenne.de/webradio/channels/heavy-metal.m3u

thanks

**Comment by plata** [comment]
@ds2k5 could you provide a pull request?
