### ISSUE TITLE
Liste SD-Streams

### ISSUE THREAD

**Issue by herrTravolta** [jnk22/kodinerds-iptv#210]
Ich habe eine Liste mit SD-Streams zusammengestellt. Frage kam im Forum, dürfte sicher von Interesse sein wg. mobilem Datenvolumen.
Hab eine eigene Gruppe 'SD-IPTV' dafür kreiert.

Die Idee wäre die SD Sender als Liste unterhalb kodi_tv.m3u 'einzuhängen'. 

[SD-IPTV.m3u.log](https://github.com/jnk22/kodinerds-iptv/files/2436905/SD-IPTV.m3u.log)
(nach DL die Dateiendung .log vom Anhang wieder entfernen  ;)  )

**Comment by olmet** [comment]
Vielen Dank für die Liste,
der "Das Erste" Stream zeigt seit kurzem immer das Morgenmagazin, bzw. zeitversetzt um Stunden. Hast du vielleicht einen neuen Link oder einen Tipp zum Suchen eines SD Streams.
