### ISSUE TITLE
Deutschlandfunk etc. OGG-Streams

### ISSUE THREAD

**Issue by hurzl** [jnk22/kodinerds-iptv#213]
Die OGG-Streams klingen viel besser, kann man die nicht vielleicht auch integrieren?
https://www.deutschlandradio.de/unsere-streaming-adressen-im-einzelnen.3236.de.html

**Comment by bjoerns1983** [comment]
Ich würde es eher favorisieren die wesentlich besseren AAC Streams aufzunehmen.
