### ISSUE TITLE
ORF

### ISSUE THREAD

**Issue by Schaussi** [jnk22/kodinerds-iptv#214]
Hi,

the Austrian ORF streams are not working at the moment.
It seems like URLs have changed if you call https://tvthek.orf.at/live.
Using the Kodi ORF TVThek addon, all streams are working, maybe you could update the URLs?

Thank you,
Regards
Daniel

**Comment by herrTravolta** [comment]
ORF 2 (ORF 1 & 3 jeweils äquivalent)
master / manifest
https://**orf2**.cdn.ors.at/out/u/**orf2**/qxb/manifest.m3u8

720p
https://orf2.cdn.ors.at/out/u/orf2/qxb/manifest_5.m3u8

540p
https://orf2.cdn.ors.at/out/u/orf2/qxb/manifest_3.m3u8

360p
https://orf2.cdn.ors.at/out/u/orf2/qxb/manifest_2.m3u8

**Comment by gsantner** [comment]
@herrTravolta some more recent iptv changes that I can include in pull request?

**Comment by herrTravolta** [comment]
Yes this one
https://github.com/jnk22/kodinerds-iptv/issues/218
