### ISSUE TITLE
Radio Bremen TV

### ISSUE THREAD

**Issue by PalminX** [jnk22/kodinerds-iptv#217]
Sorry wenn das eine doofe Frage ist, aber warum gibt es bei den NDR-Sendern nicht die Radio Bremen-Lokalvariante, sondern nur NDR Niedersachsen, NDR Schleswig-Holstein, NDR Mecklenburg-Vorpommern und NDR Hamburg?

Danke & Gruß,
    Bernd

**Comment by EmBeEins** [comment]
Radio Bremen TV-Stream: 
https://rbfs-lh.akamaihd.net/i/rb_fs@438960/master.m3u8

**Comment by freddii** [comment]
fixed in:
https://github.com/jnk22/kodinerds-iptv/commit/43527708fe6ed83920c24fc90e25d3e793d9479b
