### ISSUE TITLE
KLein

### ISSUE THREAD

**Issue by buers** [jnk22/kodinerds-iptv#219]
Statt tvg-id="anixeserie.de" besser "AnixeHD.de" nutzen. Funktioniert zumindest mit EPG Daten aus https://github.com/sunsettrack4/xmltv_epg/

Dito, statt tvg-id="nick.de" besser "Nickelodeon.de"

URL für ServusTV HD scheint nicht mehr zu funktionieren, statt http://hdiosstv-f.akamaihd.net/i/servustvhd_1@51229/index_2592_av-p.m3u8 funktioniert hier
https://liveservustv-i.akamaihd.net/hls/live/271000/ServusTV_DE/master_fb82192.m3u8 oder auch "darüber liegend" https://liveservustv-i.akamaihd.net/hls/live/271000/ServusTV_DE/master.m3u8

**Comment by buers** [comment]
https://liveservustv-i.akamaihd.net/hls/live/271000/ServusTV_DE/master_fb82192.m3u8  funktioniert auch schon nicht mehr. https://liveservustv-i.akamaihd.net/hls/live/271000/ServusTV_DE/master.m3u8 geht, der "deep link" direkt zur hohen Auflösung heißt nun: https://liveservustv-i.akamaihd.net/hls/live/271000/ServusTV_DE/master_rtz2192.m3u8 Ich denke, den sollte man normalerweise nicht nutzen. 

(Ausnahme: vlc funktioniert bei Start einer Aufnahme über Kommandozeile leider nicht mit master.m3u8 - scheint, vlc kommt da mit dem Wechsel der Auflösung nach ein paar Sekunden nicht zurecht.)

**Comment by bjoerns1983** [comment]
TVG-ID's auf das Format von EasyEPG bzw. Rytec geändert. Servus TV Streams funktionieren aktuell.
