### ISSUE TITLE
Deutsche Öffentlich-rechtliche Radiosender funktionieren nicht

### ISSUE THREAD

**Issue by buers** [jnk22/kodinerds-iptv#220]
Zumindest bei mir scheinen Kodi 17.6 (Android und Windows) nicht mit den URLs zurecht zu kommen. Die URLs funktionieren im Browser. Es gibt jeweils einen redirect zu einer anderen Lokation. Nutze ich die URL aus dem Redirect, funktionieren die Radio-Sender.

Beispiel:

#EXTINF:-1 tvg-name="Deutschlandfunk" group-title="Deutschland" radio="true" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/radio/deutschlandfunk.png",Deutschlandfunk
http://st01.dlf.de/dlf/01/128/mp3/stream.mp3

Funktioniert nicht, die redirected URL

http://dg-dradio-http-dus-dtag-cdn.ca…dlf/01/128/mp3/stream.mp3

Ich nehme and "dus" steht für Düsseldorf. Ich erhalte auch andere ähnliche redirects, z.B.

http://dg-swr-http-fra-dtag-cdn.cast.addradio.de/swr/swr1/bw/mp3/128/stream.mp3

bei SWR Rheinland-Württemberg. "fra" sicherlich für Frankfurt, statt "dus" oben. 

Wenn es hilft, kann ich gerne eine Liste aller redirects generieren, die ich hier bekomme. Es ist allerdings zu vermuten, dass die URLs dynamisch sind, und von der Lokation abhängen. Da kann dann die kodinerds-Liste nichts mehr machen. Kodi müsste mit den redirects zurecht kommen. Aber so wie die Einträge jetzt sind, funktionieren sie nicht. Oder ist das nur bei mir so?

**Comment by bjoerns1983** [comment]
Besteht das Problem immer noch?
