### ISSUE TITLE
Das Erste doesn’t work

### ISSUE THREAD

**Issue by Pazu** [jnk22/kodinerds-iptv#221]
The German channel Das Erste hasn't been working for several months. Tested with both v17.6 and v18RC1.

**Comment by deboerk** [comment]
Jetzt funktioniert der HD-Channel nicht. https://mcdn.daserste.de/daserste/de/profile7/playlist.m3u8 liefert einen 404er.

**Comment by SkyBird1980** [comment]
https://mcdn.daserste.de/daserste/de/master_3744.m3u8 < HD 1280 x 720 Falls das wer einbauen mag.

**Comment by gibso** [comment]
habe die URL ausgetauscht :-)

**Comment by deboerk** [comment]
Dieser pull request scheint sich der Sache auch anzunehmen: https://github.com/jnk22/kodinerds-iptv/pull/231

**Comment by hauk92** [comment]
Ich hab bei meinem pull request einfach nur die vorherige URL genommen, ohne mir groß Gedanken zu machen.
Der Stream mit der URL von SkyBird1980 in gibsos pull request hat um einiges weniger Verzögerung, von daher würde ich den pull request meinem vor ziehen.

**Comment by SkyBird1980** [comment]
@gibso wohl nicht in allen Dateien. in den VLC Streams ist er ausgetauscht, in den Simple IPTV Dateien aber noch nicht.
