### ISSUE TITLE
ServusTV_DE isn't opening

### ISSUE THREAD

**Issue by dieter-wilhelm** [jnk22/kodinerds-iptv#222]
This is not working, I guess at least, since 2 weeks, I've checked it with VLC today again and it says:
VLC is unable to open the MRL 'https://liveservustv-i.akamaihd.net/hls/live/271000/ServusTV_DE/master_fb82192.m3u8'. Check the log for details.

Thank you
    Dieter

**Comment by buers** [comment]
https://liveservustv-i.akamaihd.net/hls/live/271000/ServusTV_DE/master.m3u8 is working here. Issue #219 . (It seems, jnk22 is busy with other things, recently. Did not see any comment of him, since a while).

**Comment by dieter-wilhelm** [comment]
Thank you very much, it's working for me as well

**Comment by jnk22** [comment]
Should be working right now, otherwise feel free to reopen this issue.
