### ISSUE TITLE
Servus TV Hockey Night

### ISSUE THREAD

**Issue by DaGrisa** [jnk22/kodinerds-iptv#226]
Hallo,

es wäre super, wenn der "Servus TV Hockey Night" Stream verfügbar wäre.

Er greift auf folgende Playlist zu: https://liveservustv-i.akamaihd.net/hls/live/562517/Eishockey2017/master.m3u8

Allerdings wird da Audio und Video in einem separaten Stream bereitgestellt:
`#EXTM3U
#EXT-X-VERSION:4
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio",LANGUAGE="deu",NAME="Deutsch",AUTOSELECT=YES,DEFAULT=YES,URI="https://liveservustv-i.akamaihd.net/hls/live/562517/Eishockey2017/master_de_360.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio",LANGUAGE="eng",NAME="Stadion",AUTOSELECT=YES,DEFAULT=NO,URI="https://liveservustv-i.akamaihd.net/hls/live/562517/Eishockey2017/master_st_360.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=387200,AVERAGE-BANDWIDTH=396000,CODECS="avc1.66.30,mp4a.40.2",RESOLUTION=320x180,FRAME-RATE=25.000,AUDIO="program_audio",CLOSED-CAPTIONS=NONE
https://liveservustv-i.akamaihd.net/hls/live/562517/Eishockey2017/master_20190106_200.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=651200,AVERAGE-BANDWIDTH=671000,CODECS="avc1.4d4015,mp4a.40.2",RESOLUTION=426x240,FRAME-RATE=25.000,AUDIO="program_audio",CLOSED-CAPTIONS=NONE
https://liveservustv-i.akamaihd.net/hls/live/562517/Eishockey2017/master_20190106_450.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1020800,AVERAGE-BANDWIDTH=1056000,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=25.000,AUDIO="program_audio",CLOSED-CAPTIONS=NONE
https://liveservustv-i.akamaihd.net/hls/live/562517/Eishockey2017/master_20190106_800.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1760000,AVERAGE-BANDWIDTH=1826000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=25.000,AUDIO="program_audio",CLOSED-CAPTIONS=NONE
https://liveservustv-i.akamaihd.net/hls/live/562517/Eishockey2017/master_20190106_1500.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3555200,AVERAGE-BANDWIDTH=3696000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=25.000,AUDIO="program_audio",CLOSED-CAPTIONS=NONE
https://liveservustv-i.akamaihd.net/hls/live/562517/Eishockey2017/master_20190106_3200.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=5456000,AVERAGE-BANDWIDTH=5676000,CODECS="avc1.4d4028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=25.000,AUDIO="program_audio",CLOSED-CAPTIONS=NONE
https://liveservustv-i.akamaihd.net/hls/live/562517/Eishockey2017/master_20190106_5000.m3u8`

Gibt es eine Möglichkeit, den Stream trotzdem hier in die Liste aufzunehmen?

Danke und Gruß

**Comment by bjoerns1983** [comment]
Event dürfte inzwischen vorbei sein.
