### ISSUE TITLE
pipe-list funktioniert nicht mit tvheadend unter LibreElec 9

### ISSUE THREAD

**Issue by juestres** [jnk22/kodinerds-iptv#230]
Seit Version 9 ist ffmpeg nicht mehr integraler Bestandteil von LibreElec  und muss über ffmpeg-tools-Addon nachinstalliert werden. Dadurch ändert sich der Pfad zu ffmpeg 
von 
//usr/bin/ffmpeg
auf
//storage/.kodi/addons/tools.ffmpeg-tools/bin/ffmpeg

Das führt dazu, dass die hier gepflegten pipe-Listen (pipe_tv.m3u und davon abgeleitete) mit tvheadend nicht mehr funktionieren. In den pipe-Listen müsste die oben beschriebene Pfadänderung durchgeführt werden, daher:
pipe:///usr/bin/ffmpeg
ändern zu
pipe:///storage/.kodi/addons/tools.ffmpeg-tools/bin/ffmpeg

Ich würde diese Änderung auch vornehmen, habe aber keine Ahnung, ob die pipe-Listen auch in anderen Umgebungen verwendet werden, wo der bisherige Pfad weiter benötigt wird.
Gibt es Gründe, die gegen diese vorgeschlagene Änderung sprechen?

Siehe auch:
https://www.kodinerds.net/index.php/Thread/63061-Kodinerds-IPTV-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len-l%C3%A4uft-nicht-unter-LE9/?postID=490974#post490974
oder 
https://www.kodinerds.net/index.php/Thread/63226-IPTV-tvheadend-findet-keine-services-wizard-mit-IPTV-Url-aus-dem-Forum/

**Comment by CvH** [comment]
https://github.com/LibreELEC/LibreELEC.tv/pull/3163

Ich hatte schon im Forum mehrfach darum geworben das sich "betroffene" melden aber da tat sich leider nichts.

**Comment by juestres** [comment]
Hallo CvH,


danke für den Hinweis. Habe deinen push request approved. Hoffe, das hilft den merge voranzubringen. Kenne die Gepflogenheiten auf github noch nicht – habe mich heute erst auf github angemeldet.

 

Aber wenn es so ist, wie du in deinem push request schreibst, dass ffmpeg auf anderen Systemen (Synology) weiter unter usr/bin/ffmpeg installiert ist, dann stehen die Chancen für meinen Vorschlag, den Pfad in der pipe-tv.m3u-Liste zu ändern, natürlich schlecht…

 

Micha

 

Von: CvH [mailto:notifications@github.com] 
Gesendet: Dienstag, 19. März 2019 21:16
An: jnk22/kodinerds-iptv <kodinerds-iptv@noreply.github.com>
Cc: juestres <juestres@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [jnk22/kodinerds-iptv] pipe-list funktioniert nicht mit tvheadend unter LibreElec 9 (#230)

 

LibreELEC/LibreELEC.tv#3163 <https://github.com/LibreELEC/LibreELEC.tv/pull/3163> 

Ich hatte schon im Forum mehrfach darum geworben das sich "betroffene" melden aber da tat sich leider nichts.

**Comment by hmeine** [comment]
Man könnte eine weitere Version online stellen, in der der Pfad `/storage/.kodi/addons/tools.ffmpeg-tools/bin/ffmpeg` lautet, oder einfach das `/usr/bin/` wegnehmen; dann reicht es offensichtlich, ffmpeg-tools zu installieren, weil ffmpeg dann im Pfad ist. Ist das nicht ohnehin viel besser?

**Comment by hmeine** [comment]
Ich habe zwei Branches online gestellt, um dies auszuprobieren:
* https://github.com/hmeine/kodinerds-iptv/tree/libreelec9 (ohne Pfad)
* https://github.com/hmeine/kodinerds-iptv/tree/ffmpeg-tools (absoluter Pfad zu ffmpeg-tools)

**Comment by jugi80** [comment]
Beide Listen funktionieren.

**Comment by jnk22** [comment]
Habe es auch nochmal auf meinem System unter Tvheadend getestet, funktioniert auch da wenn man nur pipe://ffmpeg benutzt (macht ja auch Sinn, wenn ffmpeg sauber system-weit installiert wurde).

Denke das wäre auch der sauberste Weg.

Sofern es keinen in den nächsten Tagen Einwand gibt, werde ich das dann gerne so übernehmen.

**Comment by hmeine** [comment]
FWIW, bei mir läuft es auch.

**Comment by CvH** [comment]
cool das es auch funktioniert, das wäre ja die noch saubere Lösung :) 

bzw kann man testen indem man `which ffmpeg` eingibt und das muss dann einen Pfad zurückgeben
