### ISSUE TITLE
NTV nicht erreichbar

### ISSUE THREAD

**Issue by mr2017x** [jnk22/kodinerds-iptv#233]
Hi,

ntv scheint nicht (mehr) zu gehen? Kann das jemand verifizieren?

Außerdem, gibt es einen Weg Pro7, Sat1 usw in die Liste zu packen?

Danke vorab

**Comment by SkyBird1980** [comment]
Die Privaten bieten keine Free Streams an. Nur illegal kommt man da ran und diese Streams hätten nichts in diesem Angebot zu suchen. NTV geht wirklich nicht mehr.

**Comment by mr2017x** [comment]
Schade, ok, dann weiss ich Bescheid. NTV lässt sich fixen oder geht das auch nicht mehr?

Danke

**Comment by SkyBird1980** [comment]
Ich glaube die haben das selber noch nicht gemerkt. Deren eigener Webplayer zeigt auch nur Schwarz.

**Comment by gsantner** [comment]
hab denen vor einigen monaten gemailt. nie ne antwort bekommen.

**Comment by mr2017x** [comment]
@gsantner so wie ich das mittlerweile sehe ist der NTV Livestream in Welt TV aufgegangen?

**Comment by gsantner** [comment]
@mr2017x 
Soweit ich weiß waren  N24 und n-tv unterschiedliche sender (und sind noch immer). n-tv ist von der RTL gruppe, N24 (das jetzt WELT heißt) von der Pro7 gruppe.
