### ISSUE TITLE
Welt der Wunder stream funktioniert nicht mehr

### ISSUE THREAD

**Issue by gsantner** [jnk22/kodinerds-iptv#235]
Der Welt der Wunder stream funktioniert nicht mehr, die scheinen vom normalen stream auf einen live stream auf youtube channel umgestellt zu haben: <http://www.weltderwunder.de/videos/live>

Gibts eine m3u8 alternative?

**Comment by schelmo** [comment]
die benutzen jetzt einen youtube livestream
da lässt sich wohl keine dauerhafte m3u8 rausziehen
