### ISSUE TITLE
Mazedonische TVSender

### ISSUE THREAD

**Issue by stareye72** [jnk22/kodinerds-iptv#240]
Die Url von mazedonische TV Sender hat sich geändert.
Die Streams laufen auf tvstanici.net.
Von 24 Vesti die Url lautet: https://hls.telekabel.com.mk:1936/live/11/playlist.m3u8

**Comment by jnk22** [comment]
Beide Links funktionieren bei mir aktuell nicht.

Funktioniert der neue bei dir immer noch?
Möglicherweise Geoblocking?

**Comment by stareye72** [comment]
bei mir geht kein stream die gehen auf web wenn mann mit tvheadend die url einfügt dann gehen die.

**Comment by bjoerns1983** [comment]
Link funktioniert nicht.
