### ISSUE TITLE
Freie (private) Webradios: Einbindung in die Radiolisten

### ISSUE THREAD

**Issue by LipkeGu** [jnk22/kodinerds-iptv#242]
Mal von Kommerziellen Radios abgesehen könnte man doch auch freie private Webradios einbinden.
Viele Webradios haben ein Sendeprogramm und AutoDJ.

Da ich selbst Mitglied und Techniker eines Webradios bin und weiß, dass andere sowie unseres um Hörer kämpfen. Werbung meistens nur durch Facebook etc. gemacht wird, Möchte Ich vorschlagen,
Hier mal diverse mit einzubinden. Das erweitert die Vielfalt und Hörergewinn gibts gleich noch dazu.

Da wir bei Kodinerds freie IPTV-Sender (TV u. Radio) verteilen, Warum nicht auch Webradios. Webradios sollten daher folgendes vorraussetzen erfüllen:

- GEMA und GVL vertreten sein und es auch nachweisen können.
- Angemessendes Klima und Atmosphere.
- Einen Stream (Shoutcast / IceCast) - Livestream haben.
- Eine Erreichbarkeit in der Sendezeit von min. 80% und mindestens einen vom System nativen decodierbares Streamformat haben (Player-Nativ).
- "Ihren eigenen Stream" streamen. Nicht das eines anderen Radios. 
- Eine Webseite in Ihrer jeweiligen Sprache und auch legitim sein (Impressum, Datenschutz (DGVO), Haftungsausschluss).
- Moderator(en) sollten vorhanden sein, und auch das Webradio sollte aktiv sein.
- Ein Senderlogo haben (Den Banner der Webseite zb).  
Daher poste Ich gleich mal 2 wo ich es von Mir aus sagen kann, dass Sie jene Vorraussetzungen erfüllen.

```
#EXTINF:-1 tvg-name="The Radio Fire and Ice" group-title="Deutschland" radio="true" tvg-logo="http://the-radio-fire-and-ice.de/themes/BlueDelirium/images/banner.png",The Radio Fire and Ice
http://the-radio-fire-and-ice.de:8000/stream/main/
#EXTINF:-1 tvg-name="Radio Hexenkessel" group-title="Deutschland" radio="true" tvg-logo="http://www.hexenkesselradio.de/themes/Lernvid_gored_ultra_v702/images/header.jpg",Radio Hexenkessel
http://streamplus50.leonex.de:10768/
```

**Comment by bjoerns1983** [comment]
Du kannst gerne einen dementsprechenden PR einreichen.
