### ISSUE TITLE
Deutsche Welle [en] Stream URL

### ISSUE THREAD

**Issue by sigma67** [jnk22/kodinerds-iptv#243]
Der Livestream für den Sender Deutsche Welle [en] hat sich geändert. Der bisherige Stream

`https://dwstream1-lh.akamaihd.net/i/dwstream1_live@120422/index_1_av-p.m3u8`

ist nicht mehr abrufbar. Die neue URL (ausgelesen von https://www.dw.com/de/media-center/live-tv/s-100817?channel=1) lautet 

`https://dwstream4-lh.akamaihd.net/i/dwstream4_live@120422/index_1_av-p.m3u8`

**Comment by jnk22** [comment]
Scheint (wieder?) unter der alten URL zu funktionieren. Bitte nochmal testen und ggf. Issue wieder öffnen, wenn's doch noch nicht geht.
