### ISSUE TITLE
ZDF, ZDF Neo, SWR BW, SWR RP broken

### ISSUE THREAD

**Issue by Chris56** [jnk22/kodinerds-iptv#246]
The above mentioned urls don't work anymore (at least for he tvheadend list).
Are these lists actually being maintained??? This issue (with even mentioning correct urls):
 #244
has been there for more than 2 weeks but nobody seems to care.
Not even someone is assigned.

**Comment by jolabuna** [comment]
Hey guys, 
Sorry für my question nur i am Meer in Wirkung with KODi. So i using the url: http://bit.ly/kn-kodi-tv. Now ZDF, ZDFneo, ... Are Brocken. How can i implement the new url's in Kodi? Should i implement all of them? 

Thank you!!!!

**Comment by Chris56** [comment]
You can either wait for the fix to be merged (which partially has happen already) an start over.
Otherwise download http://bit.ly/kn-kodi-tv to a file, apply the patch and use that patched file insteal of http://bit.ly/kn-kodi-tv
