### ISSUE TITLE
Additional Radio Streams

### ISSUE THREAD

**Issue by dieterdeyke** [jnk22/kodinerds-iptv#249]
I want to contribute 3 additional radio streams:

#EXTINF:-1,Native Radio
http://stream.radiojar.com/cnerwwqq0rquv.pls
#EXTINF:-1,RADIO 700
http://streamserver.funkhaus.info/listen.pls
#EXTINF:-1,Radio Ton Live BW
http://live.radioton.de/rt-live-bw.m3u

**Comment by plata** [comment]
@dieterdeyke could you provide a pull request?

**Comment by bjoerns1983** [comment]
If you like them to be added please send in a PR with Logo etc.
Thanks
