### ISSUE TITLE
ZDF Neo url broken

### ISSUE THREAD

**Issue by Chris56** [jnk22/kodinerds-iptv#253]
in http://bit.ly/kn-pipe-tv
we have for ZDF Neo
[https://zdf-hls-02.akamaized.net/hls/live/2002461/de/dc55a4411a4769cf6be39da3697b3791/5/5.m3u8](url)
which does not work.

**Comment by Chris56** [comment]
[https://zdf-hls-02.akamaized.net/hls/live/2002461/de/high/master.m3u8](https://zdf-hls-02.akamaized.net/hls/live/2002461/de/high/master.m3u8)
does work.

**Comment by Chris56** [comment]
Fixed by
#254

**Comment by jnk22** [comment]
Should be fixed for good, using https://zdf-hls-02.akamaized.net/hls/live/2002461/de/veryhigh/master.m3u8 now
