### ISSUE TITLE
ZDF HD URL broken

### ISSUE THREAD

**Issue by rastamayo** [jnk22/kodinerds-iptv#255]
ich habe http://bit.ly/kn-kodi-tv und testweise auch http://bit.ly/kn-clean-tv versucht. In beiden Dateien funktioniert der ZDF HD Stream leider nicht.

**Comment by herrTravolta** [comment]
720p
https://zdf-hls-01.akamaized.net/hls/live/2002460/de/4c117178a6684d46d4f2475571edfe32/5/5.m3u8

Allerdings ändert das ZDF diese direkten Streams derzeit recht häufig.
Besser wäre wohl daher die master.m3u8
https://zdf-hls-01.akamaized.net/hls/live/2002460/de/veryhigh/master.m3u8

**Comment by jnk22** [comment]
Should be fixed for good, using https://zdf-hls-01.akamaized.net/hls/live/2002460/de/veryhigh/master.m3u8 now
