### ISSUE TITLE
ARTE HD stream not working

### ISSUE THREAD

**Issue by mbennoer** [jnk22/kodinerds-iptv#260]
In the "kodi_tv.m3u" playlist, the ARTE HD livestream (https://artelive-lh.akamaihd.net/i/artelive_de@393591/index_1_av-p.m3u8) is not working any longer. Anyone knows the updated URL so it can be fixed?

EDIT: Found a working URL on https://wiki.ubuntuusers.de/Internet-TV/Stationen:
https://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8

**Comment by herrTravolta** [comment]
Ergänzung:
index_1_a-p.m3u8 ist derzeit wohl defekt. Der zweite 720p-Stream in der master.m3u8 funktioniert aber.
https://artelive-lh.akamaihd.net/i/artelive_de@393591/index_1_av-b.m3u8

**Comment by jnk22** [comment]
Should be working again :)

**Comment by mbennoer** [comment]
Great, thx for fixing this. Much faster than through the link I came up with!
