### ISSUE TITLE
BR Fernsehen Süd + BR Fernsehen Nord -> URLs are broken

### ISSUE THREAD

**Issue by BeKermit** [jnk22/kodinerds-iptv#265]
Die beiden URLs in der aktuellen Playlist funktionieren leider nicht mehr.

BR Fernsehen Süd habe ich über folgende URL zum Laufen bekommen.
https://mcdn.br.de/bfs_sued/de/master.m3u8

Ob diese dauerhaft genutzt werden kann, keine Ahnung.

Für BR Fernsehen Nord hab ich leider nix finden können.

**Comment by Lonerider2010** [comment]
Bei mir funktionieren folgende Adressen:
BR Fernsehen Nord HD:
https://brlive-lh.akamaihd.net/i/bfsnord_germany@119898/index_1_av-b.m3u8
BR Fernsehen Süd HD:
https://brlive-lh.akamaihd.net/i/bfssued_germany@119890/index_1_av-b.m3u8
