### ISSUE TITLE
ARD-alpha: Link nicht mehr aktiv

### ISSUE THREAD

**Issue by mbennoer** [jnk22/kodinerds-iptv#266]
ARD-alpha ist seit einiger Zeit nicht erreichbar:
https://brlive-lh.akamaihd.net/i/bralpha_germany@119899/index_3776_av-p.m3u8

Da der Sender ebenfalls über den BR ausgespielt wird, besteht da vielleicht ein Zusammenhang zu #265

**Comment by Lonerider2010** [comment]
Bei mir funktioniert folgende Adresse:
https://brlive-lh.akamaihd.net/i/bralpha_germany@119899/index_1_av-b.m3u8

**Comment by mbennoer** [comment]
Danke für den Link, funktioniert bei mir auch.
