### ISSUE TITLE
VLC zeigt kein Bild bei ZDF, ZDF neo und ZDF info

### ISSUE THREAD

**Issue by BeKermit** [jnk22/kodinerds-iptv#269]
Seit gestern musste ich feststellen, dass VLC zu den ZDF Streams kein Bild mehr anzeigt.
Aufgefallen ist das am Mac mit VLC 3.0.8, am Android Tablet ist es mit VLC aber genauso.
...egal.. ob alte VLC-Liste, neue Liste oder die Kodi-Liste

Bisher war das an sich kein Problem.

Kodi am Android Tablet zeigt alles wie gewohnt.
Auch der Website-Livestream am Mac unter Safari läuft.

Ist zufällig irgendwas bekannt?
Wer weiß, vielleicht ist das ja auch nur übers Wochenende.

**Comment by ggikthuo** [comment]
Hallo,
ich habe das gleiche Problem seit kurzem. Bei ZDF geht nur noch der Ton. Bei anderen, wie z.B. Arte, läuft der Ton für etwa 20 Sekunden, dann ist ganz Schluss.
Ich verwende VLC 3.0.8 portable unter Windows 10.
Auch auf einem weiteren Notebook das gleiche Szenario.
Wäre interessant zu hören, ob jemand das Problem nicht hat?? (und welceh URL er benutzt).
Viele Grüße in die Runde

**Comment by laclaro** [comment]
Dies ist verwandt mit https://github.com/jnk22/kodinerds-iptv/issues/272. VLC schafft es nicht Bild und Tonspur richtig zusammenzufügen (aus der m8u-Datei). ffmpeg kann das.

Allerdings funktioniert es nicht den Zusammengefügten Stream an VLC zu übergeben. Da müsstet ihr nochmal selbst basteln. Mit tvheadend geht es.

**Comment by jnk22** [comment]
Seems to be working again.
https://github.com/jnk22/kodinerds-iptv/issues/272#issuecomment-623322136

**Comment by ggikthuo** [comment]
Funktioniert mit 3.0.10, soweit ich es bisher sehe.
