### ISSUE TITLE
Add new radio station for kids by WDR (Die Maus)

### ISSUE THREAD

**Issue by Flibb0** [jnk22/kodinerds-iptv#270]
https://wdrdiemaus-lh.akamaihd.net/i/wdr_diemaus@374300/master.m3u8

**Comment by freddii** [comment]
fixed in https://github.com/jnk22/kodinerds-iptv/pull/330

**Comment by plata** [comment]
@Flibb0 can this be closed?

**Comment by Flibb0** [comment]
> @Flibb0 can this be closed?

Yes! I thought it would be closed on fixing.
