### ISSUE TITLE
Solution for ZDF (neo/info) stream without video (sound only)

### ISSUE THREAD

**Issue by didux70** [jnk22/kodinerds-iptv#272]
https://www.rundfunkforum.de/viewtopic.php?f=9&t=55352&sid=ea7e3967bec3b347dc8a38e4bbcd01fd&start=345#p1527419

**Comment by laclaro** [comment]
Since ffmpeg/vlc do not play the ZDF HD streams where audio and video are separated, I wrote a python script to solve this. It is intended to be used with ffmpeg (equals pipe-list entries).

You find it here: https://github.com/laclaro/iptv-zdf/

Cheers.

**Comment by Crissov** [comment]
Has anyone filed a bug with VLC? I [cannot find any](https://trac.videolan.org/vlc/query?description=~m3u+stream&col=id&col=summary&col=status&col=owner&col=priority&col=milestone&col=component&col=version&order=priority).

**Comment by jnk22** [comment]
There is a new VLC media player version online (v3.0.10 @https://www.videolan.org/vlc)

https://www.kodinerds.net/index.php/Thread/56713-Kodinerds-IPTV-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len/?postID=587842#post587842

I have checked all ZDF channels with VLC and Tvheadend (pipe-list). Everything seems to be working again.
