### ISSUE TITLE
eoTV / wrong URL

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#279]
eoTV-URL is unvailable

**Comment by jnk22** [comment]
Could you find any replacement for the current url?

I have checked http://eotv.de and http://eotv.de/stream.php, but couldn't find any stream url.

Also, http://eotv.de/empfang/ -> "IPTV" shows only IPTV streams via Zattoo, Waipu and so on, but no IPTV stream without any of those providers anymore.

For now it seems like there won't be any stream url like before anymore.

**Comment by EmBeEins** [comment]
Try this one: https://5856e1a25f71a.streamlock.net/easycast9-live/_definst_/mp4:livestreamhd5/playlist.m3u8?scheme=m3u8?scheme=m3u8
