### ISSUE TITLE
Nicht mehr existente Lokal-Sender main.tv, intv, eRtv

### ISSUE THREAD

**Issue by patrick-hessinger** [jnk22/kodinerds-iptv#283]
Die folgenden Sender exestieren nicht mehr und könnten entfernt werden:

main.tv
seti Anfang 2020, seihe https://de-de.facebook.com/main.tv/posts/10158234848198901?__tn__=-R
intv
Seit Juni 2019: https://de.wikipedia.org/wiki/Intv 
eRtv
wohl schon seit 2017 https://forum.digitalfernsehen.de/threads/ertv-euro-regional-tv-wird-eingestellt.380136/

**Comment by freddii** [comment]
fixed in:
https://github.com/jnk22/kodinerds-iptv/commit/43527708fe6ed83920c24fc90e25d3e793d9479b
