### ISSUE TITLE
Oldenburg Eins fehlerhaft?

### ISSUE THREAD

**Issue by SDsGitHub** [jnk22/kodinerds-iptv#284]
Hallo,

ich kann bei  dem lokalen "Oldenburg Eins"  (Web-Live Stream: http://www.oeins.de/tv/live-stream/) nicht auf TV zugreifen.
Der Link aus der Senderliste (http://188.40.16.94:1935/live/studio/playlist.m3u8/) lässt sich auch nicht mit dem VLC-Player öffnen.

Danke für euren tollen Service :-)

**Comment by EmBeEins** [comment]
Das ist der aktuelle URL  https://5d9af227241aa.streamlock.net:1443/live/studio/playlist.m3u8

**Comment by SDsGitHub** [comment]
wow -das ging schnell! :-)
Der VLC-Player gibt es noch fehlerhaft wieder, liegt dann evtl. auch an VLC...

Wie ist das weitere Vorgehen zur Übernahme in die Liste? Kann ich ohne GitHub-erfahrung unterstützen?

**Comment by freddii** [comment]
fixed in #327
