### ISSUE TITLE
Schweizer Radiosender SRF

### ISSUE THREAD

**Issue by reneol** [jnk22/kodinerds-iptv#30]
Die Radiosender des SRF sind frei empfangbar und können noch der Liste hinzugefügt werden.

- Radio SRF 1: http://stream.srg-ssr.ch/drs1/mp3_128.m3u
- Radio SRF 2: http://stream.srg-ssr.ch/drs2/mp3_128.m3u
- Radio SRF 3: http://stream.srg-ssr.ch/drs3/mp3_128.m3u
- Radio SRF 4 News: http://stream.srg-ssr.ch/drs4news/mp3_128.m3u
- Radio SRF Musikwelle: http://stream.srg-ssr.ch/drsmw/mp3_128.m3u
- Radio SRF Virus: http://stream.srg-ssr.ch/drsvirus/mp3_128.m3u

Quelle: https://www.srf.ch/hilfe/hilfe-sendetechnik/sendetechnik-live-radio-im-internet

**Comment by jnk22** [comment]
Wird gemacht, danke.
