### ISSUE TITLE
ZDF group changed url

### ISSUE THREAD

**Issue by BeenThereScrewedUp** [jnk22/kodinerds-iptv#301]
ZDF

zdf-hls-01.akamaized.net/hls/l…02460/de/high/master.m3u8

ZDFneo

zdf-hls-16.akamaized.net/hls/l…16499/de/high/master.m3u8

ZDFinfo

zdf-hls-17.akamaized.net/hls/l…16500/de/high/master.m3u8

3sat

zdf-hls-18.akamaized.net/hls/l…501/dach/high/master.m3u8

phoenix

zdf-hls-19.akamaized.net/hls/l…16502/de/high/master.m3u8

**Comment by BeenThereScrewedUp** [comment]
UPS, korrektur

 ZDF
zdf-hls-15.akamaized.net/hls/l…16498/de/high/master.m3u8

ZDFinfo
zdf-hls-17.akamaized.net/hls/l…0/de/veryhigh/master.m3u8

ZDFneo
zdf-hls-16.akamaized.net/hls/l…16499/de/high/master.m3u8

**Comment by nightmare28** [comment]
> zdf-hls-15.akamaized.net/hls/l…16498/de/high/master.m3u8

Moin leider sind die links alle verkürzt... könnten noch einmal alle in voller Länge gepostet werden? Danke!

**Comment by redm123** [comment]
Ich bin mal so frei... Scheint soweit korrekt.
(von https://www.kodinerds.net/index.php/Thread/56713-Kodinerds-IPTV-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len/?postID=596208#post596208)

ZDF
https://zdf-hls-15.akamaized.net/hls/live/2016498/de/high/master.m3u8

ZDFinfo
https://zdf-hls-17.akamaized.net/hls/live/2016500/de/high/master.m3u8

ZDFneo
https://zdf-hls-16.akamaized.net/hls/live/2016499/de/high/master.m3u8

3sat
https://zdf-hls-18.akamaized.net/hls/live/2016501/dach/high/master.m3u8

phoenix
https://zdf-hls-19.akamaized.net/hls/live/2016502/de/high/master.m3u8

**Comment by Chris56** [comment]
Confirmed!!!
Please commit

**Comment by Chris56** [comment]
I have confirmed all the above links! Please commit.
If you use veryhigh instead of high tuning will be quicker because of less options in master.m3u
Chris

**Comment by redm123** [comment]
This merge only updated the 3sat URLs, right? ZDF and others are still broken...

**Comment by redm123** [comment]
Would be awesome if you could also update the main ZDF URL.. :)

**Comment by Chris56** [comment]
This has already happened !!!
http://bit.ly/kn-pipe-tv has

https://zdf-hls-15.akamaized.net/hls/live/2016498/de/veryhigh/master.m3u8

This is correct!!

**Comment by redm123** [comment]
No need to scream!!!

You are right. It was missing and nobody replied here. But apparently it got changed after I checked, some days ago. And then Simple IPTV plugin simply didn't pick up the change...
