### ISSUE TITLE
ZDF HD wrong link

### ISSUE THREAD

**Issue by Chris56** [jnk22/kodinerds-iptv#303]
http://bit.ly/kn-pipe-tv
still has
https://zdf-hls-01.akamaized.net/hls/live/2002460/de/veryhigh/master.m3u8
However it must be
https://zdf-hls-15.akamaized.net/hls/live/2016498/de/veryhigh/master.m3u8

**Comment by jnk22** [comment]
This is fixed now thanks to @schelmo 
#304
