### ISSUE TITLE
Weitere Radiosender

### ISSUE THREAD

**Issue by darkonon** [jnk22/kodinerds-iptv#31]
Ich hätte hier noch ein paar weitere Radiosender für die liste.:

Hitradio Ö3: http://mp3stream7.apasf.apa.at:8000/
Quelle: https://www.facebook.com/oe3/posts/10151643020066243

FM 4: http://mp3stream1.apasf.apa.at:8000/
Radio Wien: http://mp3stream2.apasf.apa.at:8000/
Info Radio: http://mp3stream6.apasf.apa.at:8000/
Ö1: http://mp3stream3.apasf.apa.at:8000/
Ö1 Campus: http://mp3stream4.apasf.apa.at:8000/
Ö2 Radio Niederösterreich: http://mp3stream8.apasf.apa.at:8000/
Ö2 Radio Steiermark: http://mp3stream9.apasf.apa.at:8000/
Ö2 Radio Tirol: http://mp3stream10.apasf.apa.at:8000/
Kronehit: http://onair.krone.at:80/kronehit.mp3
Kronehit Dance: http://onair.krone.at:80/kronehit-dance.mp3
Quelle: http://lawskynet.blogspot.de/2011/02/o3-mp3-http-stream.html

Radio Schwarze Welle: http://www.schwarze-welle.de/play.m3u
Quelle: http://www.schwarze-welle.com/

Hit Radio FFH: http://streams.ffh.de/radioffh/aac/hqlivestream.m3u
Quelle: https://www.ffh.de/musik/webradios/stream-adressen.html

Ich glaube das reicht erstmal. Wenn ich noch mehr finde mache ich mich wieder bemerkbar.

**Comment by jnk22** [comment]
Alles klar, danke für die Links. Kümmer mich drum sobald ich Zeit habe.

**Comment by jnk22** [comment]
@darkonon 
"Info Radio" scheint down zu sein.
http://mp3stream6.apasf.apa.at:8000/ bestätigt das, zumindest zu aktueller Zeit. Finde auch kaum Informationen bzw. Bilder zu diesem Sender.
Gibt es diesen noch?

**Comment by jnk22** [comment]
https://de.wikipedia.org/wiki/%C3%961_Inforadio

**Comment by darkonon** [comment]
Das war aus meiner Zeit dort unten. Wenns jetzt nicht mehr da ist dann ist es leider so. Hatte es nur auf der angegeben Seite wieder gefunden und dachte das wäre was.

**Comment by jnk22** [comment]
Kein Problem, Sender sind jetzt alle drin. Gerade geupdated :)
