### ISSUE TITLE
MDR / rbb Livestreams

### ISSUE THREAD

**Issue by stemaj** [jnk22/kodinerds-iptv#320]
Grüße,
es haben sich ein paar Streams verändert, bei Interesse hier die neuen Urls:

MDR Event Livestreams
https://mdrevent2hls-lh.akamaihd.net/i/livetvmdrevent2_ww@513991/master.m3u8
https://mdrevent2hls-lh.akamaihd.net/i/livetvmdrevent3_ww@513991/master.m3u8
https://mdrevent5hls-lh.akamaihd.net/i/livetvmdrevent4_ww@513996/master.m3u8

rbb Event 1
https://rbbevent01-hls.akamaized.net/hls/live/685984/rbbevent01/master.m3u8

Grüße, stemaj

**Comment by Chris56** [comment]
Confirmed all 4 streams!

**Comment by hurzl** [comment]
rbb Berlin

http://rbblive-lh.akamaihd.net/i/rbb_berlin@144674/master.m3u8

rbb Brandenburg

http://rbblive-lh.akamaihd.net/i/rbb_brandenburg@349369/master.m3u8

**Comment by plata** [comment]
@stemaj @hurzl am Besten die Änderungen direkt als Pull Request einreichen, dann kann @jnk22 sie leichter übernehmen.

**Comment by bjoerns1983** [comment]
MDR Streams waren nicht mehr aktuell. RBB Event Streams gegen aktuelle getauscht.
