### ISSUE TITLE
add ARD Sportschau LIVE

### ISSUE THREAD

**Issue by freddii** [jnk22/kodinerds-iptv#323]
ARD Sportschau LIVE
https://ardevent2.akamaized.net/hls/live/681512/ardevent2_geo/master.m3u8

**Comment by blueicehaller** [comment]
Der Sender ist bereits defekt (HTTP Error 404) als ARD Event 2 in [source.yaml](../blob/master/iptv/source.yaml) enthalten.
Was ist der Unterschied zu http://wdrardevent2-lh.akamaihd.net/i/wdrardevent2_geo@100869/master.m3u8 ?

ARD Event 1 ist auch defekt (HTTP Error 404).
http://wdrardevent1-lh.akamaihd.net/i/ardevent1_weltweit@566648/master.m3u8 

Quelle: [HarryHomepage - WEB TV](http://www.harryshomepage.de/webtv.html)

**Comment by blueicehaller** [comment]
@freddii Kann das geschlossen werden?

**Comment by freddii** [comment]
ja
