### ISSUE TITLE
BR-Radio-Streams - Neue URLs

### ISSUE THREAD

**Issue by silberjohnny** [jnk22/kodinerds-iptv#325]
Der Bayerische Rundfunk hat seine Radio-Streams auf folgende URLs umgestellt (Siehe [Info](https://www.br.de/unternehmen/inhalt/technik/livestreams-hilfe100.html)).

**Bayern 1 Mittel- und Oberfranken**
https://br-br1-franken.cast.addradio.de/br/br1/franken/mp3/mid
**Bayern 1 Mainfranken**
https://br-br1-mainfranken.cast.addradio.de/br/br1/mainfranken/mp3/mid
**Bayern 1 Oberbayern**
https://br-br1-obb.cast.addradio.de/br/br1/obb/mp3/mid
**Bayern 1 Niederbayern und Oberpfalz**
https://br-br1-nbopf.cast.addradio.de/br/br1/nbopf/mp3/mid
**Bayern 1 Schwaben**
https://br-br1-schwaben.cast.addradio.de/br/br1/schwaben/mp3/mid
**Bayern 2 Nord**
https://br-br2-nord.cast.addradio.de/br/br2/nord/mp3/mid
**Bayern 2 Süd**
https://br-br2-sued.cast.addradio.de/br/br2/sued/mp3/mid
**Bayern 3**
https://br-br3-live.cast.addradio.de/br/br3/live/mp3/mid
**BR-Klassik**
https://br-brklassik-live.cast.addradio.de/br/brklassik/live/mp3/high
**B5 aktuell**
https://br-b5aktuell-live.cast.addradio.de/br/b5aktuell/live/mp3/mid
**B5 plus**
https://br-b5plus-live.cast.addradio.de/br/b5plus/live/mp3/mid
**Bayern plus**
https://br-bayernplus-live.cast.addradio.de/br/bayernplus/live/mp3/mid
**BR Heimat**
https://br-brheimat-live.cast.addradio.de/br/brheimat/live/mp3/mid
**Puls**
https://br-puls-live.cast.addradio.de/br/puls/live/mp3/mid

Viele Grüße
Johnny

**Comment by freddii** [comment]
fixed in https://github.com/jnk22/kodinerds-iptv/pull/330

**Comment by plata** [comment]
@silberjohnny kann die Issue geschlossen werden?

**Comment by silberjohnny** [comment]
@freddii Besten Dank für die schnelle Umsetzung! @plata Vielleicht können bei Gelegenheit noch die vier weiteren Regionalstreams von Bayern 1 (neben Oberbayern) ergänzt werden.

**Comment by plata** [comment]
@silberjohnny am Besten immer direkt einen Pull Request mit den Änderungen anlegen. Dieser kann dann von @jnk22 einfach übernommen werden.

Ich habe [hier](https://github.com/jnk22/kodinerds-iptv/pull/346/files) eine kleine Anleitung verfasst.

**Comment by silberjohnny** [comment]
@plata Danke für den Hinweis!
