### ISSUE TITLE
Wrong link for "BibelTV"

### ISSUE THREAD

**Issue by Beisspiel** [jnk22/kodinerds-iptv#329]
Link for "BibelTV" (Website: https://www.bibeltv.de/livestreams/bibeltv/) in IPTV list (link in list: http://bibeltv02.iptv-playoutcenter.de/bibeltv01/bibeltv01.stream_1/playlist.m3u8) is not existent anymore...

Would be great if someone could fix this.

**Comment by blueicehaller** [comment]
https://bibeltv01.iptv-playoutcenter.de/bibeltv01/bibeltv01.stream_all/playlist.m3u8

Am Fr., 9. Okt. 2020 um 21:31 Uhr schrieb Beisspiel <notifications@github.com>:

**Comment by plata** [comment]
@Beisspiel can this be closed? The URL has been fixed.
