### ISSUE TITLE
ARTE HD changed

### ISSUE THREAD

**Issue by hurzl** [jnk22/kodinerds-iptv#336]
from https://artelive-lh.akamaihd.net/i/artelive_de@393591/index_1_av-b.m3u8
to    https://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8

**Comment by freddii** [comment]
fix is in pull request https://github.com/jnk22/kodinerds-iptv/pull/334/commits/ccf1664d85e30d6a4727546384435cf31564a305
