### ISSUE TITLE
RBB Kultur / Radio Orange

### ISSUE THREAD

**Issue by ghost** [jnk22/kodinerds-iptv#339]
Hallo,

ich würde mich freuen, wenn ihr zwei Radiosender hinzufügen könntet:

RBB Kultur 
http://www.rbbkultur.de/live.m3u (192kbit/s)

Radio Orange (Österreich)
http://stream01.kapper.net:8001/mp3.m3u (128 kbit/s)

Danke dafür!
Viele Grüße

**Comment by omski** [comment]
rbbKultur > https://github.com/jnk22/kodinerds-iptv/pull/355

**Comment by blueicehaller** [comment]
ghost ist nicht mehr auf GitHub.
Handelt es sich bei Radio Orange (Österreich) um diesen Sender?

- https://o94.at/de/player/live
- https://securestream.o94.at/live.mp3
