### ISSUE TITLE
daserste.png not found

### ISSUE THREAD

**Issue by tas2580** [jnk22/kodinerds-iptv#341]
https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/daserste.png used by ARD Event 1 and ARD Event 2

**Comment by plata** [comment]
Das Logo wurde in https://github.com/jnk22/kodinerds-iptv/commit/7c5c0a1aaeee196ff70608b39a503f7564cbd4d3#diff-7fbe51477c59de6828f15e98b344e3967dab5ff7d3d085c3a5511ced3de2a610 gelöscht.
