### ISSUE TITLE
Wartungsaufwand reduzieren

### ISSUE THREAD

**Issue by plata** [jnk22/kodinerds-iptv#345]
Die Listen kodi, clean und pipe sind inhaltlich identisch. Bei Änderungen müssen alle Listen angepasst werden. Es wäre sinnvoll, die drei Listenformate aus einer einzigen Liste zu generieren. Realisieren ließe sich dies beispielsweise mit GitHub actions.

Beispiel: https://github.com/marketplace/actions/add-commit

**Comment by jnk22** [comment]
Hallo,
ja, die Listen zu warten und aktuell zu halten ist leider wirklich nicht sehr benutzerfreundlich :/

Bin schon länger am überlegen, das ganze nochmal sauber aufzuziehen inkl. zukunftssicherer Lösung.
Vll. GitHub dann auch nur noch als Speicherort für die generierten Listen.

Bei mir ist da leider die Zeit der limitierende Faktor, daher in der nächsten Zeit leider noch nicht umsetzbar.

Die Idee mit GitHub Actions klingt aber gut, mindestens mal um die "doppelte Arbeit" vorerst auf ein Minimum zu reduzieren.
Hast du da Erfahrungen und ggf. Lust das umzusetzen?
Bin da offen für Vorschläge :)

Spontan kommt mir da die Idee, die "Listen" dann in zB. einem einzigen YAML-File (o.ä.?) zu speichern, müsste dann natürlich alle (aktuell) genutztzen Attribute unterstützen, inkl. Sender-Reihenfolge, HD/SD-Format etc.

**Comment by plata** [comment]
Ich hatte auch an JSON/YAML gedacht.

Meine Idee:
1. Script, das aus die bestehenden .m3u Dateien liest und die JSON/YAML Datei erzeugt
2. Script, das aus der JSON/YAML Datei wieder die .m3u Dateien generiert
3. GitHub action, die nach jedem commit auf master das Script aus 2. ausführt und die Änderungen commited. Das sollte weitestgehend trivial sein, da einfach nur in der verlinkten action der Scriptaufruf eingetragen werden muss.

Ich persönlich würde die Scripts mit Python schreiben, da das für mich am schnellsten ist. Vielleicht finde ich die Zeit, zumindest für einen Prototypen.

**Comment by jnk22** [comment]
Klingt gut :)

**Comment by freddii** [comment]
einfaches fixen einer geänderten url im terminal in linux:

in die .bashrc:
```
rpl-all(){
	find . -type f -exec sed -i "s|$1|$2|g" {} \;
}
```

1) Das Projekt auf Github forken
2) 
```
git clone https://github.com/YOURUSERNAME/kodinerds-iptv
cd kodinerds-iptv
rpl-all "alte-url" "neue-url"
```
3) pull request auf github erstellen.
