### ISSUE TITLE
NHK World

### ISSUE THREAD

**Issue by omski** [jnk22/kodinerds-iptv#350]
NHK World funktioniert seit einigen Tagen nicht mehr.
Eine neue URL habe ich gefunden.
https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index_4M.m3u8
Es gibt auch noch eine _2M und _1M Variante. Es wäre schön wenn die 4M eingefügt wird und nicht die 1M wie vorher - die Qualität war doch recht schlecht.

Vielen Dank und Grüße!

**Comment by jnk22** [comment]
Closed, siehe #354 

Danke :)
