### ISSUE TITLE
Please Fix stream URL for TV channel "Nickelodeon" 

### ISSUE THREAD

**Issue by CustomerJFK** [jnk22/kodinerds-iptv#367]
Hello
Since Yesterday the URL for Nickelodeon  didn't work anymore.
Could you please fix it? (maybe in SD or HD?)  My kids love the chanel!
(for German)

Thank you

**Comment by jnk22** [comment]
This is now fixed thanks to @schelmo. #366 

Unfortunately Nick has lowered their stream quality..
