### ISSUE TITLE
SWR funktioniert nicht

### ISSUE THREAD

**Issue by marcert** [jnk22/kodinerds-iptv#372]
Hallo,
von der Liste https://bit.ly/kn-kodi funktionieren die SWR Sender nicht mehr (SWR Baden-Württemberg HD und SWR Rheinland-Pfalz HD).

**Comment by blueicehaller** [comment]
Laut https://www.swrfernsehen.de/live/index.html und The Stream Detector (Browser Add-On)
müssten die neuen Adressen folgende (ggf. ohne ?set-segment-duration=responsive ) sein:
```
# SWR BW
https://swrbwhls-i.akamaihd.net/hls/live/667638/swrbwd/master.m3u8?set-segment-duration=responsive

#SWR RP
https://swrrphls-i.akamaihd.net/hls/live/667639/swrrpd/master.m3u8?set-segment-duration=responsive
```

Wenn ich diese versuche mit VLC abzuspielen sagt Meldungen:
```
mpeg4audio info: AAC channels: 2 samplerate: 48000
adaptive info: Changing stream format Unknown -> Unknown
adaptive info: Encountered discontinuity
```

Weiter hat The Stream Detector die folgenden erkannt, man sollte aber auf die `master.m3u` verlinken:
```
# SWR BW
https://swrbwhls-i.akamaihd.net/hls/live/667638/swrbwd/master-540p-1928.m3u8

#SWR RP
https://swrrphls-i.akamaihd.net/hls/live/667639/swrrpd/master-540p-1928.m3u8
```
