### ISSUE TITLE
[tvheadend] group-title

### ISSUE THREAD

**Issue by tuxiano** [jnk22/kodinerds-iptv#378]
Hallo

vielen Dank für die iptv-Liste für tvheadend.

Mich würde interessieren, ob es möglich ist die etwas kryptischen group-title von der tvheadend liste (z.B. IPTV-DE) durch die group-title aus der normalen kodi list (z.B. Vollprogramm, Musik, etc.) zu ersetzen?

Vielen Dank und Grüße

**Comment by bjoerns1983** [comment]
Bitte dafür im TVHeadend Subforum im Kodinerds Forum nachfragen.
