### ISSUE TITLE
ARD funktioniert nicht

### ISSUE THREAD

**Issue by tuxiano** [jnk22/kodinerds-iptv#379]
Hallo, seit gestern funktioniert Das Erste nicht mehr mit tvheadend.  

Stream Detector gibt folgendes zurück:

```
https://mcdn.daserste.de/daserste/de/master_3660.m3u8
https://mcdn.daserste.de/daserste/de/master_514.m3u8
https://mcdn.daserste.de/daserste/de/master.m3u8
https://mcdn.daserste.de/daserste/de/master.m3u8?arn=0
```

Der erste Link funktioniert zumindest mit VLC.

**Comment by blueicehaller** [comment]
Der dritte ist aber der richtige.

**Comment by jnk22** [comment]
@blueicehaller Ich habe die Stream-URL in deinem Pull Request nochmal angepasst in `https://mcdn.daserste.de/daserste/de/master_3660.m3u8`, da die Ladezeiten dort deutlich kürzer sind und so konsistent mit anderen Streams in den Listen sind.

**Comment by blueicehaller** [comment]
@jnk22 Legt man sich dadurch nicht auf eine bestimmte Qualität z.B. 720p fest?

**Comment by jnk22** [comment]
Richtig, das nimmt leider die Flexibilität in der Hinsicht.

Jedoch sind die Umschaltzeiten so deutlich schneller (vll. 500ms statt 2s? - _keine Messwerte_).
Man muss so dann aber auch die Streams natürlich öfter aktualisieren, da sich die fixen Streams leider öfter ändern.

Im Kodinerds Forum gab es dazu auch vor kurzem eine Diskussion:
https://www.kodinerds.net/index.php/Thread/56713-Kodinerds-IPTV-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len/?postID=625723#post625723

Die Priorität hatte ich damals beim Erstellen der Listen auf schnellere Umschaltzeiten und hohe Qualität der Streams gesetzt.

Dass die Lösung (bzw. beide Lösungen) leider nicht perfekt ist sehe ich aber auch.

Vielleicht hat sich mittlerweile aber auch was getan was die Ladezeiten der Clients angeht. Aktuell werden ja folgende "unterstützt":
- VLC media player
- Kodi IPTV Simple Client
- Tvheadend

Müsste man mal testen. Wenn die "master.m3u" Links dort genauso schnell laden, macht es natürlich Sinn, diese in Zukunft zu benutzen.

**Comment by blueicehaller** [comment]
Ich habe mit VLC getestet und da dauert es ein paar Sekunden bis die richtige Geschwindigkeit ausgehandelt wurde.
Was sind schon 2 bis 10 Sekunden anstatt das es bei einer benachteiligten Gruppe ruckelt?

Ich weiß hier geht es um Live TV aber trotzdem der Hinweis für alle die es noch nicht wussten:
Über HbbTV werden sogar von einzelnen Serien (das Traumschiff, der Bergdoktor und die Bergretter) von den öffentlich-rechtlichen in 4K mit HDR und mit VLC getestet angeboten.

Weitere Informationen in einem [Thread im Loewe Friends Forum](https://www.loewe-friends.de/viewtopic.php?f=7&t=9112) wo netterweise jemand diese Links gepostet hat.

**Comment by tuxiano** [comment]
Hallo, 

ARD hat wohl schon wieder etwas umgestellt:

`https://mcdn.daserste.de/daserste/de/master_3628.m3u8
https://mcdn.daserste.de/daserste/de/master_578.m3u8
https://mcdn.daserste.de/daserste/de/master.m3u8?arn=0
https://mcdn.daserste.de/daserste/de/master.m3u8`

Vielen Dank
