### ISSUE TITLE
HR - YOU FM Sender Club, Just Music und Sounds eingestellt

### ISSUE THREAD

**Issue by vx-i** [jnk22/kodinerds-iptv#395]
HR Radio scheint die zusätzlichen Sender gestrichen zu haben. Sowohl auf der Seite selbst (https://www.you-fm.de/index.html), als auch unter https://www.ardaudiothek.de/ ist nur YOU FM Hauptsender zu finden. Die URL's funktionieren natürlich auch nicht und sollen gelöscht werden.

Soll ich einen Pull Request einstellen?

**Comment by freddii** [comment]
Wurde verbessert in https://github.com/jnk22/kodinerds-iptv/commit/2e5a39d3b6ddcda96fd7a5501b6fee98d376662c#diff-41f0981651019263d87564922fa51547d78b93ab698ada2353286d90e78a8a6a
