### ISSUE TITLE
WDR funktioniert nicht

### ISSUE THREAD

**Issue by quirbel** [jnk22/kodinerds-iptv#399]
Der Eintrag für den WDR in der Liste "https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/iptv/clean/clean_tv_regional.m3u" funktioniert nicht mehr.

Der richtige Eintrag müsste sein:
#EXTINF:-1 tvg-name="WDR HD" tvg-id="WDR.de" group-title="IPTV-DE" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/wdrhd.png",WDR HD
https://wdrfs247.akamaized.net/hls/live/681509/wdr_msl4_fs247/master.m3u8

statt momentan
#EXTINF:-1 tvg-name="WDR HD" tvg-id="WDR.de" group-title="IPTV-DE" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/wdrhd.png",WDR HD
https://wdrfs247.akamaized.net/hls/live/681509/wdr_msl4_fs247/master_3628.m3u8

**Comment by blueicehaller** [comment]
Previous: #397 #109

**Comment by freddii** [comment]
was fixed in #392
