### ISSUE TITLE
Falsche Stream-URLs für die Schweizer Sender Radio SRF 4 News und Radio SRF Musikwelle

### ISSUE THREAD

**Issue by reneol** [jnk22/kodinerds-iptv#40]
Die Stream-URLs für die Schweizer Sender Radio SRF 4 News und Radio SRF Musikwelle verweisen fälschlicherweise auf Radio SRF Virus

Richtig wäre hier:

- Radio SRF 4 News - http://stream.srg-ssr.ch/m/drs4news/mp3_128
- Radio SRF Musikwelle - http://stream.srg-ssr.ch/m/drsmw/mp3_128

**Comment by jnk22** [comment]
Alles klar, wird gefixt. Danke
