### ISSUE TITLE
Regelmäßige Änderung der URLs von öff.-rechtl. Sendern

### ISSUE THREAD

**Issue by Chris56** [jnk22/kodinerds-iptv#400]
Ich benutze diese Liste um tvheanend damit zu füttern.
Vielen Dank dafür!
Jedoch:
regelmäßig sind die URLs wieder "kaputt" nd eine programmierte Aufnahme funktioniert nicht.
Bei Projekt mediathekview gibt es auch eine List der Streams und die ist (bisher) immer up-to-date.
Wie wäre es, für die öffentlich-rechtlichen Einträge einfach die Einträge von mediathekview täglich automatisiert zu übernehmen?
Chris

**Comment by bjoerns1983** [comment]
Wo kann man diese Liste denn finden?
