### ISSUE TITLE
Add Radio Zürisee

### ISSUE THREAD

**Issue by Zuerill** [jnk22/kodinerds-iptv#415]
I don't know if there are rules about what can be added or not, but I would appreciate Radio Zürisee getting added:

http://mp3.radio.ch/radiozuerisee128k

Logo: https://upload.wikimedia.org/wikipedia/de/8/8e/Logo_Radio_Z%C3%BCrisee.svg

**Comment by freddii** [comment]
fixed in https://github.com/jnk22/kodinerds-iptv/commit/f2e402201bdeefc06723edd795bbcdd084a84c2f
