### ISSUE TITLE
Ard Stream broken

### ISSUE THREAD

**Issue by matz585** [jnk22/kodinerds-iptv#416]
Hello,

as described the Ard Stream isnt working any more.
Sorry for not beeing able to tell the new one.

Thanks and Regards
Matz

It seems this link address would work: https://daserstehdut-lh.akamaihd.net/i/daserstehd_ut_de@629193/master.m3u8

**Comment by HartmutSt** [comment]
Hi, ard.de in a browser uses https://mcdn.daserste.de/daserste/de/master.m3u8, which also works well with VLC, but not with kodi. No clue, why not. For kodi I am currently using https://mcdn.daserste.de/daserste/de/master_1280p_3628.m3u8

**Comment by jnk22** [comment]
I have updated the URL with the one you provided @HartmutSt 
`https://mcdn.daserste.de/daserste/de/master.m3u8`

Could you check once more whether the stream is working with Kodi now - by using the default Kodi link?

**Comment by strowi** [comment]
thx, the update seems to work here ;)

**Comment by matz585** [comment]
Yes. Works like a charm.

Thanks

**Comment by jnk22** [comment]
Thank you for reporting back. I‘ll mark this as solved 🙂
