### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [jnk22/kodinerds-iptv#417]

**Comment by blueicehaller** [comment]
https://www.kodinerds.net/index.php/Thread/56713-Kodinerds-IPTV-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len/?postID=641779#post641779

**Comment by Fernsehhunter** [comment]
@blueicehaller Dort wird nur der Link zum TV-Stream genannt, aber nicht zu einem neuen Eventstream. Eventstream1 und Eventstream2 sind bekannt, allerdings wurde im Eventstream2 die Übertragung des "PVW"-Feeds beendet, daher wird ein neuer möglicher Eventstream3 oder eine andere Quelle gesucht, welcher den "PVW"-Feed oder "PGM"-Feed überträgt.

Trotzdem erst einmal danke für die Antwort. :)

Auf diesem Bild kann man die Feeds sehen: https://www.bilder-upload.eu/bild-522e13-1621251300.jpg.html

**Comment by blueicehaller** [comment]
Dein zweiter Link funktioniert doch (mit VLC am PC getestet).

**Comment by Fernsehhunter** [comment]
Früher war aber in diesem Eventstream2 der "PVW"-Feed zu sehen, jetzt aber sieht man nur das TV-Signal.
Ich suche daher einen neuen Eventstream oder einen anderen Stream, wo man den "PVW"-Feed sehen kann, wie in diesem Video: https://www.youtube.com/watch?v=N7XF5USJSmo

**Comment by blueicehaller** [comment]
Das erste ist das Bash Skript für Linux und wird als determinex.sh mit der Berechtigung ausführbar (chmod +x determinex.sh) gespeichert.
Das zweite zeigt den Aufruf des Bash Skript mit dem Parameter für den Startwert.
Der curl Befehlt schreibt in die Variable RESPONSE den Rückgabewert (404 oder 200).
Wenn in der Variable RESPONSE = 200 steht dann wurde X ermittelt.

**Comment by Fernsehhunter** [comment]
@blueicehaller Also ich habe das Skript bei "Cygwin" eingegeben, was muss ich nun tun?

**Comment by blueicehaller** [comment]
Je nachdem wo das Skript liegt muss man zunächst in das Verzeichnis z.B. Desktop wechseln:
```
cd /cygdrive/c/Users/
ls 
<Benutzername> Public
cd <Benutzername>
cd Desktop
```
Dann kann man es einfach mit einer Zahl als Parameter starten:
```
./determinex.sh 200000
```

**Comment by Fernsehhunter** [comment]
@blueicehaller Bei mir läuft das Programm ganze Zeit mit "X !=0" usw. und zählt weiter ganze Zeit.

**Comment by blueicehaller** [comment]
Hast Du eine 6-Stellige Zahl als Parameter eingegeben?

**Comment by Fernsehhunter** [comment]
@blueicehaller Wo genau muss die Zahl eingegeben werden? Das Programm hat nach dem Skript direkt angefangen zu zählen.

**Comment by Fernsehhunter** [comment]
Also muss ich das einfach so einfügen?

#!/bin/bash
clear
X=$1
RESPONSE=000

while [ $RESPONSE != 200 ]
do
    echo "X != $X"
    URL=https://eventenc04-lh.akamaihd.net/i/eventenc04_1@$X/index_1_av-p.m3u8
    # echo $URL
    RESPONSE=$(curl -k -H 'Content-Type: application/json' --silent -w %{response_code} -o /dev/null $URL )
    # echo "HTTP Code: $RESPONSE"

    if [ "$RESPONSE" = 200 ]
    then
        echo "X = $X"
        echo $URL
    fi

    X=$(( $X + 1 ))
done

root@localhost:~# chmod +x determinex.sh
root@localhost:~# ./determinex.sh 200000
X != 200000
X != 200001
...

**Comment by blueicehaller** [comment]
Nein das Skript als Neue Textdatei anlegen.

**Comment by blueicehaller** [comment]
Wie beschrieben hinter dem $ [die Kommandos](#issuecomment-842402622) einfügen und jeweils Enter / Eingabetaste.

**Comment by Fernsehhunter** [comment]
$ cd /cygdrive/c/Users/USERNAME/Desktop
$ cd /cygdrive/c/users/USERNAME/Desktop
$ ls 
<Benutzername> Public
$ cd <Benutzername>
$ cd Desktop

Also so etwa im Programm eingeben?

**Comment by blueicehaller** [comment]
Ja

**Comment by Fernsehhunter** [comment]
Habe dann das eingegeben darunter:
$ ./determinex.sh 200000
X != 200000
X != 200001

Aber nichts passiert mit Drücken der Enter-Taste.

**Comment by blueicehaller** [comment]
Vielleicht doch ein Screenshot (Snipping Tool)? Hier kann man auch Grafiken (png) direkt anhängen.

**Comment by Fernsehhunter** [comment]
Oder muss dieses "cygdrive" weg? Hab bei USERNAME nämlich den Benutzernamen hingeschrieben, wie er bei den Eigenschaften von der determinex.sh bei Pfad steht.

**Comment by Fernsehhunter** [comment]
Etwa so
![determinex](https://user-images.githubusercontent.com/84293445/118516520-ac31e480-b736-11eb-9521-c2ddca9bd31d.PNG)
![cygwin](https://user-images.githubusercontent.com/84293445/118517520-9244d180-b737-11eb-9ba9-4b10cdc955c5.PNG)

**Comment by Fernsehhunter** [comment]
Habe das im Programm geschrieben:

$ cd /cygdrive/c/Users/USERNAME/Desktop/determinex.sh
$ cd /cygdrive/c/users/USERNAME/Desktop/determinex.sh
$ ls 
<USERNAME> Public
$ cd <USERNAME>
$ ls
$ cd Desktop

**Comment by Fernsehhunter** [comment]
![cygwin 2](https://user-images.githubusercontent.com/84293445/118519183-2bc0b300-b739-11eb-8d53-33128e01c856.PNG)

**Comment by Fernsehhunter** [comment]
Hab das so eingegeben:

cd /cygdrive/c/Users/USERNAME/Desktop/determinex.sh
ls 
<USERNAME> Public
$ cd <USERNAME>
$ ls
$ cd Desktop

**Comment by blueicehaller** [comment]
`cd /cygdrive/c/Users/USERNAME/Desktop/determinex.sh` macht keinen Sinn da dies auf die Datei zeigt.
Bitte nur folgendes ohne $ eingeben und sagen was das Ergebnis ist, dann kann ich die weiteren Kommandos nennen.
```
$ cd /cygdrive/c/Users/
$ ls
```

**Comment by Fernsehhunter** [comment]
Habe mal einen Ordner am Desktop für die Datei gemacht, da im Programm alle meine Programme vom Desktop angezeigt wurden.

![cygwin 3](https://user-images.githubusercontent.com/84293445/118521146-07fe6c80-b73b-11eb-8131-422c299b66e6.PNG)

**Comment by Fernsehhunter** [comment]
Und das habe ich eingegeben:

cd /cygdrive/c/Users/#USERNAME#/Desktop/Folder
ls 
<#USERNAME#> Public
$ cd <#USERNAME#>
$ ls
$ cd Desktop

**Comment by blueicehaller** [comment]
Das ist alles nicht nötig. Es genügt `ls` um vorhandene Dateien aufzulisten.
Wenn das Skript genau so heißt dann sollte es so starten und hochzählen:
```
$ ./determinex.sh 200000
```

**Comment by Fernsehhunter** [comment]
Das Skript heißt genau "determinex.sh"

**Comment by blueicehaller** [comment]
Super und die Ausgabe zählt hoch ab 200000?

**Comment by Fernsehhunter** [comment]
Vorher einfach nur bis hierhin schreiben oder?:

cd /cygdrive/c/Users/#USERNAME#/Desktop/Folder
ls

**Comment by blueicehaller** [comment]
Wie kommst Du darauf? 
Die von mir genannten Kommandos dienten nur dazu den genauen Pfad zu ermitteln denn unter Linux wird zwischen groß- und Kleinschreibung bei Dateien und Verzeichnissen unterschieden.

Wenn man weiß wie der Pfad ist kann man im Cygwin Fenster auch direkt das Skript starten ohne $:
```
$ /cygdrive/c/Users/USERNAME/Desktop/Folder/determinex.sh 200000
```

**Comment by Fernsehhunter** [comment]
![cygwin 4](https://user-images.githubusercontent.com/84293445/118523123-1ea5c300-b73d-11eb-951a-d6fd6b96db59.PNG)

Hat nicht geklappt

**Comment by Fernsehhunter** [comment]
Habe das "#" nicht eingegeben

**Comment by blueicehaller** [comment]
Es gibt ein Problem da die Datei mit falschem Zeilenumbruch gespeichert wurde.
Bitte sagen ob dieser Befehl ohne $ zur Verfügung steht: `$ dos2unix`

**Comment by Fernsehhunter** [comment]
Nein da kommt "-bash: dos2unix: command not found"

**Comment by blueicehaller** [comment]
Bitte versuche mit dem Cygwin installer das Paket nachträglich zu installieren.
Beispiel: https://superuser.com/questions/612435/cygwin-dos2unix-command-not-found/612440

**Comment by Fernsehhunter** [comment]
Er zählt jetzt runter ab 200000.
Und jetzt warten oder wie?

**Comment by Fernsehhunter** [comment]
Habe das Skript genommen, welches du verlinkt hast.

**Comment by blueicehaller** [comment]
Super, jetzt warten und ggf. zusätzliche Cygwin Fenster öffnen und auch dort mit einem anderen Startwert starten.

**Comment by Fernsehhunter** [comment]
Wenn die richtige Zahl erwischt wird, was wird dann angezeigt?

**Comment by blueicehaller** [comment]
Angenommen 234567 ist die Zahl dann wird folgendes angezeigt:
```
$ X = 234567
$ https://eventenc04-lh.akamaihd.net/i/eventenc04_1@234567/index_1_av-p.m3u8
```

**Comment by Fernsehhunter** [comment]
Okay, vielen Dank bis hierhin. Empfiehlt es sich alle 100.000er Zahlen zu nehmen also im einem Terminal ab 200.000 und beim anderen Terminal 300.000 usw. oder kleinere Schritte? Er schafft ca. 3 bis 5 Zahlen in einer Sekunde.

**Comment by blueicehaller** [comment]
Das ist eine Möglichkeit.

Ich habe [meinen Code](#issuecomment-842292284) korrigiert da die Ausgabe einen Fehler enthielt. So ist es korrekt:
```
    if [ "$RESPONSE" = 200 ]
    then
        echo "X = $X"
        echo $URL
    else
        echo "X != $X"
    fi
```

**Comment by Fernsehhunter** [comment]
Also muss ich den Code noch korrigieren?

**Comment by blueicehaller** [comment]
Nein es funktioniert trotzdem. 
Es wird zunächst sagen X ist ungleich 234567 `$ X != 234567` obwohl die Zahl korrekt ist. Danach folgt das korrekte Ergebnis.
```
...
$ X != 234566
$ X != 234567
$ X = 234567
$ https://eventenc04-lh.akamaihd.net/i/eventenc04_1@234567/index_1_av-p.m3u8

```

**Comment by Fernsehhunter** [comment]
Erkennt das Programm eigentlich die richtige URL, weil das ist ja keine richtige Webseite sondern eine Webseite die sich nicht öffnen lässt und automatisch eine .m3u8-Datei herunterlädt?

**Comment by Fernsehhunter** [comment]
Kleiner Nachtrag: Das Programm erkennt die richtige Seite, habe das mit dem Eventstream2 getetet, wo ja bereits die URL bekannt ist. :)

**Comment by blueicehaller** [comment]
Keine Treffer:
200000 ... 258716
300000 ... 339255
379038 ... 418438
425444 ... 465125
444563 ... 484231

**Comment by Fernsehhunter** [comment]
@blueicehaller Ich überprüfe gerade noch bis 500000, dann darüber und danach ab 100000 oder noch kleiner.

**Comment by Fernsehhunter** [comment]
@blueicehaller Habe nun alle Zahlen bis 500000 überprüft von 0 an. Bislang ohne Ergebnis. Werde es noch bis 1000000 erstmal ausprobieren.

**Comment by Fernsehhunter** [comment]
@blueicehaller So habe nun alle Zahlen von 0 bis 1000000 durch und leider kein Ergebnis :/
