### ISSUE TITLE
DELUXE Radio 192 kbps

### ISSUE THREAD

**Issue by vx-i** [jnk22/kodinerds-iptv#418]
Guten Abend zusammen,

aktuell enthält die Liste nur DELUXE Radio AAC-Streams in 64 kbps, welche mein LibreElec (RPi 3B) sich weigert abzuspielen. Daher wollte ich nachfragen, ob nicht jemand diese Streams durch MP3 192 kbps ersetzen kann?

DELUXE 2000
https://audiostreams.deluxemusic.tv/2000/mp3-192/audiostreams.deluxemusic.tv/play.m3u
DELUXE EASY
https://audiostreams.deluxemusic.tv/easy/mp3-192/audiostreams.deluxemusic.tv/play.m3u
DELUXE LOUNGE RADIO
https://audiostreams.deluxemusic.tv/lounge/mp3-192/audiostreams.deluxemusic.tv/play.m3u
DELUXE MUSIC RADIO
https://audiostreams.deluxemusic.tv/music/mp3-192/audiostreams.deluxemusic.tv/play.m3u

**Comment by blueicehaller** [comment]
Hallo@jnk22 Wäre es OK beide Varianten einzubauen und in Klammer (MP3) bzw. (AAC) zu schreiben?

**Comment by jnk22** [comment]
Ich habe mal testweise den Part "aac-64" durch "mp3-192" ersetzt, das scheint zu funktionieren.

[`https://audiostreams.deluxemusic.tv/music/aac-64`](https://audiostreams.deluxemusic.tv/music/aac-64)
[`https://audiostreams.deluxemusic.tv/music/mp3-192`](https://audiostreams.deluxemusic.tv/music/mp3-192)

@vx-i Kannst du mal testen, ob LibreElec den unteren MP3-Stream abspielt?

Ich würde die AAC-Streams einfach durch die MP3-Streams ersetzen. Das passt dann auch besser zum Rest der Liste, da vorzugsweise immer MP3 statt AAC gewählt wurde.

**Comment by vx-i** [comment]
Hallo zusammen,

es tut mir leid, dass es ein wenig länger gedaurt hat. Die oben genannte Links funktionieren bei LibreElec nicht, aber wenn man diese Links kürzt, dann ist es in Ordnung.

DELUXE 2000
https://audiostreams.deluxemusic.tv/2000/mp3-192/
DELUXE EASY
https://audiostreams.deluxemusic.tv/easy/mp3-192/
DELUXE LOUNGE RADIO
https://audiostreams.deluxemusic.tv/lounge/mp3-192/
DELUXE MUSIC RADIO
https://audiostreams.deluxemusic.tv/music/mp3-192/

Eventuell hat es damit zu tun, dass diese m3u-Dateien auf hoerradar.de weiterleiten

**Comment by jnk22** [comment]
Ich habe die Streams jetzt aktualisiert - alles jetzt in MP3-192.

Die Links entsprechen denen aus deinem letzten Beitrag @vx-i

Falls das damit doch nicht funktioniert, gerne hier einfach nochmal schreiben.
