### ISSUE TITLE
Sender funktioniert nicht mehr - NDR Mecklenburg-Vorpommern HD

### ISSUE THREAD

**Issue by CustomerJFK** [jnk22/kodinerds-iptv#428]
Hallo

Es wäre schön, sofern der Sender - NDR Mecklenburg-Vorpommern HD - wieder gangbar zu machen wäre.
Leider funktioniert er aktuell nicht mehr.

Vielen Dank

**Comment by mhier** [comment]
NDR Hamburg geht ebenfalls nicht mehr...

**Comment by blueicehaller** [comment]
Gerade getestet 'https://mcdn.ndr.de/ndr/hls/ndr_fs/ndr_mv/master.m3u8' funktioniert.
'https://ndrfs-lh.akamaihd.net/i/ndrfs_hh@430231/index_3776_av-p.m3u8' funktioniert nicht aber 'https://ndrfs-lh.akamaihd.net/i/ndrfs_hh@430231/master.m3u8'.
[source.yaml](../blob/master/iptv/source.yaml)

**Comment by mhier** [comment]
Gestern endlich geschafft, mein Kodi zu übereden, seine Senderlisten zu aktualisieren. Jetzt funktioniert NDR Hamburg wieder. Vielen Dank!

**Comment by blueicehaller** [comment]
@jnk22 Status Open → Closed?

**Comment by freddii** [comment]
NDR Mecklenburg-Vorpommern HD funktioniert wieder
