### ISSUE TITLE
ARD One Link funktioniert nicht

### ISSUE THREAD

**Issue by candidel** [jnk22/kodinerds-iptv#429]
Die URL zeigt offensichtlich auf einen einzelnen Mediathek-Inhalt.
Das aktuelle Programm lässt sich damit nicht streamen.

**Comment by blueicehaller** [comment]
Getestet 'https://onelivestream-lh.akamaihd.net/i/one_livestream@568814/index_4_av-p.m3u8' funktioniert.
[source.yaml](blob/master/iptv/source.yaml)

**Comment by candidel** [comment]
Danke für die schnelle Reaktion. Der Link funktioniert, aber zeigt immer auf die selbe Sendung. Rote Rosen oder so etwas. Den aktuellen Livestream erreiche ich nicht. Weder mit vlc auf dem PC noch mit Kodi auf dem Raspberry.

**Comment by blueicehaller** [comment]
Würde dieser 'https://mcdn.one.ard.de/ardone/hls/master.m3u8' passen?

**Comment by candidel** [comment]
...dieser funktioniert!
