### ISSUE TITLE
Parlamentsfernsehen, Euronews

### ISSUE THREAD

**Issue by hedavid** [jnk22/kodinerds-iptv#44]
Ich würde mich freuen, wenn das Parlamentsfernsehen und Euronews Deutsch aufgenommen werden könnten:

#EXTINF:-1 tvg-name="Parlamentsfernsehen 1" tvg-id="Parlamentsfernsehen1.de" tvg-logo="" group-title="IPTV-Extra",Parlamentsfernsehen 1
https://c13014-l-hls.u.core.cdn.streamfarm.net/1000153copo/hk1.m3u8
#EXTINF:-1 tvg-name="Parlamentsfernsehen 2" tvg-id="Parlamentsfernsehen2.de" tvg-logo="" group-title="IPTV-Extra",Parlamentsfernsehen 1
https://c13014-l-hls.u.core.cdn.streamfarm.net/1000153copo/hk2.m3u8

Euronews ändert leider den Link zu seinem Livestream (jedenfalls in Bezug auf den, den ich gefunden hatte...)
#EXTINF:-1 tvg-name="Euronews Deutsch" tvg-id="Euronews.de" tvg-logo="" group-title="IPTV",Euronews.de
http://euronews-de-p9-cdn.hexaglobe.net/28a85b309c4eb5f59fc3d8391122bdba/593f027a/euronews/euronews-euronews-website-web-responsive-2/ewnsabrdepri_ger.smil/playlist.m3u8

Im Rahmen Regionalfernsehen würde ich mich über tv.berlin und Alex Berlin freuen:
#EXTINF:-1 tvg-name="tv.berlin" tvg-id="" tvg-logo="" group-title="IPTV",tv.berlin
http://stream.der-hauptstadt-sender.de/hls/Themeh4g.m3u8
#EXTINF:-1 tvg-name="Alex Berlin" tvg-id="" tvg-logo="" group-title="IPTV",Alex Berlin
https://alex-front.rosebud-media.de/live/smil:alexlivetv.smil/playlist.m3u8

**Comment by SkyBird1980** [comment]
Die Frage ist ob das nun nicht eher Event-Fernsehen ist 🗡

**Comment by jnk22** [comment]
euronews passt ja soweit.
Laut Wiki senden ALEX Berlin über Internet, Kabel und tv.berlin über Kabel und DVB-T. Könnte man also denke ich schon reinmachen die beiden. Was meinst du? @SkyBird1980 
Ist halt ziemlich regional, aber da haben wir auch schon ein paar andere relativ kleine regionale Kanäle drin.
Würde sich dann vll. dementsprechend demnächst anbieten mal über weitere Gruppierungen nachzudenken, aber vorerst unabhängig hier von.

Denke Parlamentsfernsehen auf jeden Fall wenn dann ein IPTV-Extra-Kanal.

**Comment by jnk22** [comment]
Sind jetzt im brachn "new" drin.
Müssten aber nochmal auf Verfügbarkeit etc. getestet werden, da kam ich noch nicht zu.

https://github.com/jnk22/kodinerds-iptv/tree/new

Hier der PR dazu: #45
