### ISSUE TITLE
RBB streams need to be fixed

### ISSUE THREAD

**Issue by ooglyhLL** [jnk22/kodinerds-iptv#445]
Current playlist m3u URLs for 
- Berlin: https://rbb-hls-berlin.akamaized.net/hls/live/2017824/rbb_berlin/index.m3u8
- Brandenburg: https://rbb-hls-brandenburg.akamaized.net/hls/live/2017825/rbb_brandenburg/index.m3u8

(The official links on their web page are not up-to-date)

**Comment by bjoerns1983** [comment]
Just confirmed that the URL's in the source.yaml are working. So no further action required.
