### ISSUE TITLE
DASH Streams

### ISSUE THREAD

**Issue by prof-membrane** [jnk22/kodinerds-iptv#46]
In den nächsten Tagen poste ich mal ein paar DASH Streams. Diese haben teilweise eine höhere Bitrate als m3u8 Streams und senden fast immer mit 50fps. 

Getestet:
ARD-Alpha - http://brdashdvbt2-i.akamaihd.net/dash/live/268335/dvbt2/manifest.mpd

Ungetestet:
RBB - http://rbbdashlive-i.akamaihd.net/dash/live/481522/berlin/manifest.mpd
HR - http://hrdash-i.akamaihd.net/dash/live/265226/hrfernsehen/manifest.mpd
BR - http://brdashdvbt2-i.akamaihd.net/dash/live/268329/dvbt2/manifest.mpd
WDR - http://wdrfsdash15-i.akamaihd.net/dash/live/275009/wdrfs/dash.mpd
SWR - http://swrdash-i.akamaihd.net/dash/live/925020/swrdash_1/dash.mpd
SWR Backup - http://swrdash-i.akamaihd.net/dash/live/925020-b/swrdash_1/dash.mpd
NDR Spezial 1 - http://ndrspezial.edgesuite.net/dash/live/923078/ndrspezial_1/spezial_1.mpd
NDR Spezial 2 - http://ndrspezial.edgesuite.net/dash/live/923079/ndrspezial_2/spezial_2.mpd
NDR Spezial 3 - http://ndrspezial.edgesuite.net/dash/live/254139/ndrspezial_3/spezial_3.mpd
NDR Spezial 4 - http://ndrspezial.edgesuite.net/dash/live/923081/ndrspezial_4/spezial_4.mpd
NDR Spezial 5 - http://ndrspezial.edgesuite.net/dash/live/926240/ndrspezial_5/spezial_5.mpd
NDR Spezial 6 - http://ndrspezial.edgesuite.net/dash/live/926241/ndrspezial_6/spezial_6.mpd

Testsender:
Das Erste - http://irtdashreference-i.akamaihd.net/dash/live/901161/bfs/manifestARD.mpd

Down:
Einsfestival - http://einfest_dash-i.akamaihd.net/dash/live/925660/rbbtest/manifest.mpd

Meiner Erfahrung nach werden DASH Streams in Zukunft eine größere Rolle spielen. Darüber werden in sicherlich auch bessere Bitraten sowie höhere fps/Auflösungen zu bekommen sein. 

Auch wenn man im Moment diese Art von Streams noch nicht nutzen kann, lohnt das sammeln von diversen Sendern.

**Comment by jnk22** [comment]
Wird das ganze denn voraussichtlich mit Kodi 18 ähnlich abspielbar sein wie du aktuellen Listen, also im Prinzip einfach "Links austauschen und fertig" oder muss dafür erst das jeweilige IPTV-Addon angepasst werden?

Wenn das ganze irgendwann funktioniert, ist das aber mit Sicherheit ne gute Alternative!
Danke schon mal.

**Comment by asciidisco** [comment]
Ich hab mich auch mal mit der Thematik beschäftigt (vorrangig um die Streams von Pro7/Sat1, sport1 & Eurosport and laufen zu bekommen)
Mit einem modifizierten IPTV Plugin und einem Python Addon als lokalem Proxy in Kodi konnte ich erste Erfolge erzielen. Ist aber alles fernab von nutzbar. Theoretisch gäbe es sogar ne Möglichkeit das über TV Headend zu ermöglichen, allerdings nur mit Zusatz software.
Vor'm Herbst werde ich wohl keine signifikante Zeit mehr darin investieren können, stehe aber gerne als Informations Quelle zur Verfügung, wenn sich dem jemand annehmen will.

**Comment by tzwn** [comment]
Bei mir sieht es bzgl. der zur Verfügung stehenden zeit leider sehr ähnlich aus. Sollte jedoch Bedarf beim Testen oder ähnliches bestehen, so kann ich sicher etwas unterstützen - sofern nötig.

**Comment by jnk22** [comment]
Zeit ist bei mir auch meist das große Problem, freut mich aber zu hören dass es da Lösungsansätze gibt!
Würde das ganze Angebot qualitativ wohl echt nochmal aufbessern.

Bin da dann auch dabei, wohl aber eher um Unterstützung zu leisten, nicht um das dann im Gesamten zu übernehmen.
Sobald das dann bereit ist und gut funktioniert, nehme ich das dann natürlich liebend gerne mit in die Listen auf!

**Comment by jnk22** [comment]
Habe jetzt mal eine neue Liste erstellt, folgende Dinge sind dabei zu beachten:

- Sender "Einsfestival" zu "one" umbenannt, aktuell down. Trotzdem testweise in der Liste
- "SWR Backup" hat gleiche tvg-id wie "SWR".
- "RBB" hat tvg-id "rbbBerlin.de", da Berlin und Brandenburg jw. nur eigene tvg-ids haben.
