### ISSUE TITLE
Gruppen für Kanäle definieren

### ISSUE THREAD

**Issue by jnk22** [jnk22/kodinerds-iptv#47]
Würde noch weitere Gruppendefinitionen vorschlagen.

Zuerst die Fernsehsender in Gruppen nach Land aufteilen, wie es bereits bei den Radiosendern der Fall ist. (Radio-DE, AT, CH, FR)

Dies ermöglicht u.a. in Kodi eine bessere Übersicht der Kanäle.

Wenn möglich dann noch mit Zweitgruppen, kategorisiert nach Sendeinhalt (zB. Vollprogramm, Regional, Sport, Kinder/Jugend, ...)

Ist dir da was bekannt @SkyBird1980 ?

**Comment by jnk22** [comment]
Gerade mal die Liste durchgegangen. Handelt sich um folgende Sender:

AT  ORF eins HD
AT  ORF 2 HD
AT  ORF III HD
AT  ORF SPORT +
AT  ServusTV HD AT
AT  gotv
FR  ARTE HD FR
IT  SDF
EU  XITE

Ist jetzt nur die Frage, ob man das so einteilen möchte, oder nicht, bzw. ob das ganze Sinn macht. Zumal sendet SDF ja glaube ich in deutscher Sprache.. Nicht dass es da noch Konflikte wegen der Einteilung gibt :D

**Comment by SkyBird1980** [comment]
Wie man das mit den Zweitgruppen macht weiß ich nicht. Aber ich würde eine Unterteilung in Länder auch sinniger Finden. Man kann ja immernoch sich alle Anzeigen lassen im Addon.

**Comment by jnk22** [comment]
Habe eine Möglichkeit gefunden, das ganze in mehrere Gruppen zu unterteilen.
Das ganze geht, indem man die Kanäle mehrfach einträgt, also je Kanal zu Gruppe dann einen Eintrag mehr.

Beispiel:
#EXTINF:-1 tvg-name="Das Erste" tvg-id="ARD.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/daserste.png" group-title="IPTV",Das Erste
http://daserste_live-lh.akamaihd.net/i/daserste_de@91204/index_2692_av-p.m3u8
#EXTINF:-1 tvg-name="Das Erste" tvg-id="ARD.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/daserste.png" group-title="IPTV-DE",Das Erste
http://daserste_live-lh.akamaihd.net/i/daserste_de@91204/index_2692_av-p.m3u8
#EXTINF:-1 tvg-name="ZDF HD" tvg-id="ZDF.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/zdfhd.png" group-title="IPTV",ZDF HD
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_3096_av-p.m3u8
#EXTINF:-1 tvg-name="ZDF HD" tvg-id="ZDF.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/zdfhd.png" group-title="IPTV-FR",ZDF HD
http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_3096_av-p.m3u8
#EXTINF:-1 tvg-name="3sat" tvg-id="3sat.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/3sat.png" group-title="IPTV",3sat
http://zdf0910-lh.akamaihd.net/i/dach10_v1@392872/index_1496_av-p.m3u8
#EXTINF:-1 tvg-name="3sat" tvg-id="3sat.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/3sat.png" group-title="IPTV-DE",3sat
http://zdf0910-lh.akamaihd.net/i/dach10_v1@392872/index_1496_av-p.m3u8
#EXTINF:-1 tvg-name="3sat" tvg-id="3sat.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/3sat.png" group-title="IPTV-FR",3sat
http://zdf0910-lh.akamaihd.net/i/dach10_v1@392872/index_1496_av-p.m3u8

Ergibt die Gruppen:
IPTV - Das Erste, ZDF HD, 3sat
IPTV-DE - Das Erste, 3sat
IPTV-FR - ZDF HD, 3sat

Funktioniert so auch ganz gut, Nachteile wären:
- PVR-Addon lädt in diesem Fall dann für 3 Sender 7 Sender
- Deutlich mehr Zeilen in den Listen, vll. etwas unübersichtlich
- Vll. nicht die "sauberste" Lösung (aber leider die einzige wie es scheint)

Könnte man aber durchaus machen, so könnte man dann auch vll. ein paar mehr internationale Sender sauber mit einfügen, wenn Bedarf besteht.

Was meinst du @SkyBird1980 ?

**Comment by SkyBird1980** [comment]
Naja, es geht ja nur um ein paar Byte, das wird schon gehn.

**Comment by asciidisco** [comment]
Wie ist denn hier der Status?
Ich frage weil ich mein Proxy Service Addon jetzt soweit am laufen habe & es ja die ursprüngliche Liste hier parsed, um die neue Kanäle erweitert (Sport1, Tele5, Eurosport) & die Möglichkeit bietet über das Kodi UI einzelne Sender auszublenden.
Sollten sich die Metaangaben (und die Anzahl der Einträge pro Sender) ändern, würde das Addon nicht mehr funktionieren & ich würde ungern eine Version releasen, die irgendwann nicht mehr mit dem Input umgehen kann.

Damit zusammenhängend, wäre es nicht schöner die Sender in Gruppen á la Sport, ÖR,

**Comment by jnk22** [comment]
Habe gerade privat recht viel um die Ohren mit Klausurenphase und so. Versuche aber wenn ich zwischendurch etwas mehr Zeit habe noch ne finale Lösung für die Sache mit den Gruppen zu finden. Sollte ja dann auch wirklich nicht mehr geändert werden und dementsprechend durchdacht sein.
Hab's nicht vergessen :)

**Comment by asciidisco** [comment]
Keine falsche Eile. Klausuren sind mal definitiv wichtiger ;)

**Comment by LipkeGu** [comment]
Soweit ich weiß unterstützt das Addon es nicht, dass man mehre Gruppen durchschleifen kann. Hab das auch schon mehrfach gelesen. :(

**Comment by jnk22** [comment]
@asciidisco @SkyBird1980 @tzwn @prof-membrane

So, habe mir jetzt nochmal paar Gedanken zu den Gruppen gemacht.

Wie erwartet würde das dann auch (sinnvollerweise) einhergehen mit ner gewissen Strukturänderung der Listen, diese sollte dann aber final sein und auch in Zukunft keiner Änderung mehr nötig haben. Also dann lieber jetzt noch einmal was verändern, um dann aber in Zukunft dabei bleiben zu können.

Hier mal meine Vorschläge:

---

# Haupt-Struktur:
```
- clean
- pipe
- kodi
- kodi2
- dash
```
- **clean** bleibt weitestgehend so wie es war, also nur _eine_ Gruppe, möglicherweise nur "IPTV" oder aber mit Länderkürzel "IPTV-DE, IPTV-FR, ...". Hintergrund ist, dass diese Liste mittlerweile ja nicht mehr nur von Nutzern für Kodi verwendet wird, sondern auch andere Clients möglich sind (VLC zB.). Nur noch eine Liste würde diese Möglichkeit nehmen.
- **pipe** bleibt auch weitestgehend so wie es war, also ebenfalls nur _eine_ Gruppe, auch wahlweise nur IPTV oder Länderkürzel. Grund ist der, dass diese Liste ja nur in Tvheadend etc. verwendet wird, doppelte Belegung wäre hier sinnlos (da Kanal-Management an anderer Stelle passiert).
- **kodi** (und möglicherweise **kodi2**) wären dann die neuen Listen, mit Unterteilung in weitere sinnvolle Gruppen (siehe unten). Dabei _könnte_ man, je nachdem wie die Gruppierungen Sinn machen, mehrere "Arten" von Gruppierungen zur Verfügung stellen, deshalb mehrere **kodi**-Gruppen.
- **dash** könnte man schon mal vorbereiten, dass der Übergang (falls irgendwann möglich) leichter ist. In #46 dazu ein paar Beispiele, was da an Inhalt möglich würde. Vll. auch für Testzwecke dann interessant.

---

# Unter-Struktur (am Beispiel "clean"):

```
- clean

-- clean_tv

--- clean_tv_main
--- clean_tv_spec
--- clean_tv_regio
--- clean_tv_local
--- clean_tv_shop
--- clean_tv_intl
--- clean_tv_extra

-- clean_radio

--- clean_radio_lang_german
--- clean_radio_lang_english
--- clean_radio_lang_french

--- clean_radio_country_germany
--- clean_radio_country_austria
--- clean_radio_country_swiss
--- clean_radio_country_france
```

Hier das Beispiel für die **clean**-Liste, wäre dann voraussichtlich auf jede andere Struktur-Datei übertragbar.

Aaaalso, die Idee dahinter ist: Die obere Datei enthält jeweils ALLE Sender der Unter-Liste, so kann ein Benutzer also selber entscheiden, wie detailliert bzw. welchen Content er gerne hätte. Müsste man dann natürlich dementsprechend detailliert beschreiben, so sind aber dann aber auch sehr individuelle Lösungen möglich.

Die **TV**-Sender wären dann unterteilt in Hauptsender (Das Erste, ZDF), Spartensender (zB. Sport1, KiKA, Nickelodeon, XITE, FashionTV...), Regionalsender, Lokalsender, Shopping-Sender, internationale Sender (Überschneidung möglich?), Extra-/Event-/Online-Sender.

Bei **Radio**-Sendern wäre das hier meine einzige Idee, wie man das etwas spezifischer einteilen kann. Könnte man also in "Sprache" unterteilen (um deutssprachige Sender aus Deutschland, Österreich, Schweiz zu gruppieren), oder aber Unterteilung in "Länder".

---

# Inhaltsgruppen für Kodi-Liste:
Diese Gruppen wären dann für die **kodi**- und **kodi2**-Listen. Wer bspw. keine Unterteilung in Gruppen möchte, könnte dann einfach auf die **clean**-Liste zurückgreifen (wie oben erwähnt, dann nur "IPTV" oder "IPTV-DE, IPTV-FR, ...")

## Idee 1
```
IPTV-DE
IPTV-FR
IPTV-US
```

## Idee 2
```
Hauptsender
Privatsender
Spartensender
Regional
Lokal
(Shopping)
International
Extra/Event/Online
```

## Idee 3
```
News/Nachrichten
Dokumentation
Kinder/Jugend
Filme/Serien
Comedy
Kultur/Musik/Kunst
Sport
Sozial/Wirtschaft/Politik
Religion
Mode
Erotik
Teleshopping
Sonstige
```

- **Idee 1** wäre dann sinnvoll, falls die **clean**-Liste keine Unterteilung in Länder bekommt (also vielleicht nicht notwendig).
- **Idee 2** wäre dann sinnvoll, wenn man die Sender grob unterteilen möchte. Überschneidungen gäbe es hierbei dann voraussichtlich nicht.
- **Idee 3** ist wohl die komplexeste, aber "nutzerfreundlichste" Unterteilung in Gruppen. Überschneidungen wären hier vorhanden und vorgesehen.

---

So, das wären jetzt mal meine Überlegungen gewesen, das ganze auch zukunftssicher zu gestalten.
Bin da aber sehr gerne für weitere Ideen und Vorschläge offen!

Das ganze lässt sich so dann natürlich nicht mehr per Hand lösen, würde mir daher dann vorher etwas basteln, was das ganze dann so automatisch wie möglich macht. Idee wäre hier ein kleines Python-Programm mit Tkinter. Auch hier sind Tipps gern gesehen, falls ich mit dem Vorhaben auf dem Holzweg sein sollte (auch falls es sinnvollere Kombinationen als Python+Tkinter gibt!).
Ab dann ist es auch kein Thema mehr, deutlich schneller neue Inhalte hinzuzufügen und obsolete Streams zu entfernen.

Ich denke am wichtigsten ist erstmal, dass man sich auf eine Struktur einigt, damit zB. @asciidisco dann die Sender wie Sport1 usw. integrieren kann. Alles weitere lässt sich dann nämlich auf dieser Idee aufbauen.

**Comment by asciidisco** [comment]
Sehr cool. Nach dem Wochenende führe ich mir das noch mal genauer zu Gemüte & geb meinen Senf dazu ab. Was ich beim überfliegen gesehen habe, gefällt mir aber schon sehr gut.

Mit meinem Proxy Addon geht´s auch langsam voran. Sport1, Tele5, Eurosport & DisneyChannel laufen auch schon drüber, ich sitze grade noch an den 7TV Sachen, die nutzen aber alle Regeln der Kunst um es so schwer wie möglich zu machen, an die Streams zu kommen. Noch bin ich zuversichtlich.

Zudem agiert das Service Addon als Nutzerfrontend. Damit kann man dann einzelne Sender oder Gruppen aus seiner Liste rauswerfen, Favoriten hinzufügen oder die Sender nach eigenem Gusto sortieren.

<img width="1440" alt="screen shot 2017-08-11 at 23 23 27" src="https://user-images.githubusercontent.com/805339/29232650-ffe36dc8-7eec-11e7-820d-fa3f4600abe1.png">
<img width="1440" alt="screen shot 2017-08-11 at 23 23 39" src="https://user-images.githubusercontent.com/805339/29232652-ffeacd98-7eec-11e7-94ef-7d4d1d0eadfa.png">
<img width="1440" alt="screen shot 2017-08-11 at 23 23 48" src="https://user-images.githubusercontent.com/805339/29232649-ffe346c2-7eec-11e7-99a2-b3becf899fac.png">
<img width="1440" alt="screen shot 2017-08-11 at 23 23 52" src="https://user-images.githubusercontent.com/805339/29232651-ffe96516-7eec-11e7-8214-d88ec9a55bbf.png">

**Comment by jnk22** [comment]
Wow, das sieht echt gut aus!

Hatte gar nicht mit so 'nem "großen" Addon gerechnet, aber das hat's scheinbar in sich! 👍 

Was genau hat es denn mit den "Netzwerkeinstellungen" auf sich? Entspricht das dem Prinzip vom Zattoo Proxy Addon?

Habe vor ein paar Monaten mal 'ne Liste für Entertain TV-Sender erstellt.
https://github.com/jnk22/entertain-iptv
https://github.com/jnk22/entertain-iptv/blob/master/clean/entertain_clean_tv.m3u

Hatte ursprünglich nicht wirklich vor, diese Liste groß weiter zu pflegen, da ich selber kein Kunde bei Telekom bin und das daher inhaltlich für mich weniger interessant ist. Kann mir aber nach den Bildern gut vorstellen, dass man die da bestimmt auch noch recht gut integrieren könnte. Dann wäre das TV-Angebot zumindest schon mal für Telekom-Kunden perfekt! Da wären dann sogar RTL, SAT.1 etc. mit drin.

Wenn ich diese Listen hier fertig habe, kann ich aber auf jeden Fall nochmal drüber nachdenken ob ich die Liste nicht doch entweder noch hier mit reinnehme oder als parallele Liste weiterführe, bzw. dann nochmal überarbeite und an die neuen Kategorien/Gruppen anpasse :)

**Comment by asciidisco** [comment]
Ja, ich hab mir gedacht, wenn ich schon dabei bin, dann bau ich auch ne ordentliche Config UI auf Kodi Seite ;)

Die Netzwerkeinstellungen sind genau das, ermöglichen die Konfiguration für externen Zugriff, so das z.B. ne TvHeadend installation die Liste (ink. der Proxied Channels) nutzen kann.

Ich bin Entertain Kunde (fällt schwer es nicht zu sein, wenn man da arbeitet, wo ich arbeite :D),
ich behalte mir das als zukünftiges Improvement mal offen.

Wie gesagt, ich schau mir morgen/die Woche noch mal die Gruppenaufteilung an & geb dann meinen Senf dazu ab. Aber es schaut, für mich, sehr gut aus soweit.

**Comment by simbhm** [comment]
@asciidisco Das sieht doch schon sehr gut aus! Also wenn Du es demnächst im kodinerds repo veröffentlichen würdest... :1st_place_medal: 
Einen kleinen Wunsch hätte ich aber noch: Eine Möglichkeit eine zusätzliche .m3u frei wählbar anzugeben, die auch gemerged wird. Grund: Ich nutze einen Fritz! DVB-C Repeater und würde darüber dann gerne einen Teil der Sender beziehen, erweitert mit der tollen Liste von @jnk22 

Eventuell könnte man hier im Repo noch eine zusätzliche Datei pflegen, z.B. JSON, die metadaten über die einzelnen m3u Playlists bereithält. Dann müsstest Du dein Addon nicht jederzeit anpassen und @jnk22 wäre flexibel was die Aufteilung der Senderlisten betrifft.

**Comment by simbhm** [comment]
Ach, bezüglich mehrerer Gruppen definieren pro Kanal: https://github.com/kodi-pvr/pvr.iptvsimple/pull/117

Das macht den Vorschlag von dir @jnk22 vom 2.Juli überflüssig. Aber wohl erst Kodi 18?

**Comment by jnk22** [comment]
Das sieht natürlich genial aus mit den mehreren Gruppen. Hatte das Gefühl dass bei dem Addon nicht mehr viel passiert, deshalb in der Richtung schon kaum mehr Hoffnung gehabt. Da hab ich mich wohl getäuscht.
Danke fürs Bescheid sagen :)

**Comment by asciidisco** [comment]
@simbhm @jnk22
Das mit dem Kodinerds Repo ist der Plan. Es wird allerdings noch 2-3 Wochen dauern,
mit dem Plugin versuche ich nämlich noch eine CI/CD Strecke anzutesten, die ich auch so beim Netflix Plugin einführen möchte.

Ich hab mal wegen dem PVR simple PR nachgefragt, momentan ist er nur im Branch für Kodi 18, aber wenn sich jemand finden würde, der ihn für Kodi 17 backported (was eigtl. kein großer Akt sein dürfte), könnte er auch da rein kommen. Allerdings fehlt mir die Zeit, mich darum zu kümmern.

Wegen der frei wählbaren M3U, den Gedanken hatte ich auch schon, aber genau wie die Entertain Anbindung würde ich das mal für die Zukunft als Enhancement mit aufnehmen.

Eine weitere Metadaten Datei halte ich für overhead, lieber löse ich das mit nem Multiselect in den Settings und nutze direkt die GitHub API, um die möglichen Listen abzufragen (Die sich ja in einzelnen Dateien befinden).

Um mal wieder auf die Ursprüngliche Diskussion einzugehen, ich finde auch Idee No. 3 am Nutzerfreundlichsten, würde die Liste allerdings noch um die Gruppe Hauptsender o.ä. erweitern.

Bei Radio Sendern sehe ich es ähnlich, da kann man es nur Länderbezogen und in Spezialfällen nach Genre machen. Länderbezogen find ich aber erstmal gut.

Ansonsten, klasse Arbeit 👍  📺

**Comment by tzwn** [comment]
@jnk22 @asciidisco 
Super Arbeit! Die Idee Nr. 3 finde ich ebenso am besten. 

Wenn ich am WE die Zeit finde, würde ich mir den PVR Simple PR mal anschauen - sieht überschaubar aus. Es sind wahrscheinlich noch genügend Leute auf Kodi 17 unterwegs, so das sich das lohnen würde. 

(Sorry für die späte Reaktion. Hab leider im Moment viel um die Ohren.)

**Comment by jnk22** [comment]
Hab nochmal drübergeschaut und das etwas erweitert/angepasst. Was @asciidisco gesagt hat bzgl. Hauptsender/Vollprogramme ist auf jeden Fall wichtig für die Übersicht, folglich sollte dann aber auch noch die Kategorie Regional/Lokal und Spartensender/Privatsender mit rein, um das sinnvoll umzusetzen.
Ggf. kann man diese beiden ja zusammenfassen.

---

## Ordner-Struktur:
```
- clean
- pipe
+ rtmp
- dash
- kodi
```
- "kodi2" nicht mehr nötig, siehe unten

---

## Datei-Struktur (am Beispiel "clean"):
```
- clean (enthält clean_tv + clean_radio)

-- clean_tv (enthält folgende...)

--- clean_tv_main
--- clean_tv_spec
--- clean_tv_regio
--- clean_tv_local
--- clean_tv_shop
--- clean_tv_intl
--- clean_tv_extra

-- clean_radio (enthält folgende...)

--- clean_radio_lang_german
--- clean_radio_lang_english
--- clean_radio_lang_french

--- clean_radio_country_germany
--- clean_radio_country_austria
--- clean_radio_country_swiss
--- clean_radio_country_france
```
- alle anderen Formate analog

---

## Kategorien für "clean", "pipe", "dash", "rtmp":

```
- IPTV-DE
- IPTV-FR
- IPTV-US
+ ...
```
- Einfachste Möglichkeit, Sender einzuteilen
- Ist identisch zur "Idee 1", weshalb nur noch eine detailierte "kodi"-Liste nötig wäre
- ermöglicht leicht weitere Konfigurationen in anderen IPTV-Empfängern/Backends/...

---

## Kategorien für "kodi":

### Idee 1
```
überflüssig, da gleich wie "clean"
```

### Idee 2
```
überflüssig, da in Idee 3 integriert
```

### Idee 3
```
+ Hauptsender / Vollprogramm
+ Spartensender / Privatsender
+ Regional
+ (Lokal)
+ International
- Nachrichten
- Dokumentation
- Kinder/Jugend
+ (Familie)
- Filme/Serien
- Comedy
+ (Unterhaltung)
- Kultur/Musik/Kunst
+ (Bildung)
- Sport
- Sozial/Wirtschaft/Politik
- Religion
- Mode
- Erotik
- Teleshopping
- (Sonstige)
+ Extra/Event/Online
```
- noch ein paar weitere Kategorien hinzugefügt (+), Kategorien in Klammern wären möglich, könnte man aber vll. jeweils in die obere Kategorie einordnen.
- 17 - 22 Kategorien

---

Im Prinzip könnte man anhand dieser Strukturen dann bereits anfangen, die Listen "clean", "pipe", "dash" und "rtmp" anzupassen, sofern die Unterteilung in die simplen Gruppen "IPTV-XY" (Land) soweit in Ordnung ist. Die "clean"-Liste würde dann die jetzt aktuellen Listen ersetzen (da ziemlich ähnlich zu aktuellem Zustand).

Vorteil wäre dann, dass man die Liste "kodi" nicht überstürzen müsste, da kann man auch gerne noch etwas anpassen.

Alles was in den Klammern steht (Idee 3) wäre theoretisch möglich auch in die jw. obere Gruppe zu integrieren. Resultat wären nach aktueller Situation dann 17 - 22 Kategorien.
(Je nachdem, welche Dateien der Benutzer benutzt, können es aber auch weniger sein!)

**Comment by jnk22** [comment]
Vielen Dank auch an @flubshi für den Backport!
https://github.com/kodi-pvr/pvr.iptvsimple/pull/153

Wenn ich das richtig verstehe ist es aber trotzdem nicht sicher, ob dieser noch seinen Weg in Kodi 17.X findet, oder?

**Comment by jnk22** [comment]
Update für die bestehenden Inhalte (clean, pipe, rtmp, dash) wäre jetzt fertig, siehe #127

Die Pfade sind allerdings nicht mehr kompatibel zu den alten Links (tinyurl.com/iptv_xxx).
Würde dann neue erstellen, diesmal bei einem Provider der es ermöglicht, die Ziele der Links anzupassen (falls es irgendwann nochmal Updates in dieser Hinsicht geben sollte).

**Comment by jnk22** [comment]
Habe jetzt ebenfalls das "Entertain IPTV"-Repo soweit vorbereitet, inkl. "clean" und "pipe"-Liste (für TVH zb, hoffe das funktioniert - nicht getestet)

Damit wären dann beide Repos nun gleich in der Struktur, werde dann auch die "kodi"-Liste für "Entertain IPTV" einpflegen, sobald diese hier fertig ist.
- https://github.com/jnk22/kodinerds-iptv/tree/structure
- https://github.com/jnk22/entertain-iptv/tree/structure

Hier die PRs:
- https://github.com/jnk22/kodinerds-iptv/pull/127
- https://github.com/jnk22/entertain-iptv/pull/5

Bevor das ganze gemerged wird, möchte ich vorher noch überlegen wie das am besten gemacht wird, da auch bestehende Links nicht mehr funktionieren würden.
Inwiefern PVR IPTV Simple Client die Listen vernünftig cached weiß ich nicht genau, andere Möglichkeit wäre aber eine temporäre Datei mit "erstem Kanal" als Hinweis inkl. Link zum Forum-Thread einzubinden, dass sich die Struktur geändert hat, und dementsprechend ein Update nötig ist. Dies trifft natürlich nur für die Leute zu, die Live-Updates erhalten, alle lokal gespeicherten Playlists natürlich nicht. Die Benutzer laden das eh selber herunter, daher irrelevant.

**Comment by asciidisco** [comment]
@jnk22 Super Arbeit. Ich bin die nächsten 1 1/2 Wochen arbeitstechnisch sehr eingespannt, wenn du damit noch so lange warten kannst, kann ich dir dann Feedback geben.

**Comment by jnk22** [comment]
Habe jetzt die "kodi"-Liste soweit fertig, also alle Kanäle schon mal grob eingeteilt. Fehlen natürlich noch einige Sender, bei denen man nochmal drüber schauen müsste, das kann aber nachträglich noch gemacht werden. Zumindest ist jetzt jeder Sender in mindestens einer Gruppe.

Hier die Listen: https://github.com/jnk22/kodinerds-iptv/tree/structure/iptv/kodi

Sieht dann in Kodi mit Standardskin etwa so aus:

Ansicht: Gruppen für TV
![groups_tv_1](https://user-images.githubusercontent.com/24391401/30125644-5a7e9b30-9339-11e7-982d-f9a28bf8dc46.jpg)
![groups_tv_2](https://user-images.githubusercontent.com/24391401/30125646-5c1e7320-9339-11e7-8b30-ed90f82ddae3.jpg)
![groups_tv_3](https://user-images.githubusercontent.com/24391401/30125648-5d6c5774-9339-11e7-97c9-fa75e03f237a.jpg)

Beispiel für Kategorie "Kinder/Jugend"
![group_tv_example](https://user-images.githubusercontent.com/24391401/30125650-5f1d4d26-9339-11e7-890e-976c727e37e4.jpg)

Ansicht: Gruppen für Radio
![groups_radio](https://user-images.githubusercontent.com/24391401/30125667-6e521632-9339-11e7-9dd4-7297321c5d8d.jpg)

(Getestet mit Kodi 18 - PVR IPTV Simple 3.3.1)

---

Dann ist ja noch die Frage mit dem Update, das habe ich jetzt so gelöst, dass ich die alten Dateien nochmal vom aktuellen Branch "structure" mit ins master ziehe, aber jeweils die ersten 3 Kanäle als "Benachrichtigung" benutze. Sieht dann so aus:

![update_msg](https://user-images.githubusercontent.com/24391401/30123690-1d5a2504-9333-11e7-98f1-f0291217a5dd.jpg)

Würde das dann in etwa so schreiben:
```
UPDATE VERFÜGBAR
tinyurl.com/link_zu_kodinerds
BITTE BIS 30.09.17 UPDATEN
```

---

Die Dateistruktur ist jetzt folgende (am Beispiel "kodi"):

```
- kodi.m3u (enthält alles)

- kodi_tv.m3u (enthält alle TV-Sender)

- kodi_tv_atch.m3u (TV: Österreich/Schweiz)
- kodi_tv_extra.m3u (TV: Extra-Sender der ÖR, div. andere)
- kodi_tv_international.m3u (TV: alle intl. Sender, die nicht AT/CH/US/UK sind)
- kodi_tv_local.m3u (TV: deutsche Lokalsender)
- kodi_tv_regional.m3u (TV: deutsche Regionalsender)
- kodi_tv_shop.m3u (TV: deutsche Teleshoppingsender)
- kodi_tv_usuk.m3u (TV: Sender aus USA/GB)

- kodi_radio.m3u (enthält alle Radio-Sender)

- kodi_radio_at.m3u (Österreich)
- kodi_radio_ch.m3u (Schweiz)
- kodi_radio_de.m3u (Deutschland)
- kodi_radio_fr.m3u (Frankfreich)
- kodi_radio_nl.m3u (Niederlande)
```

Hier gerne nochmal Feedback geben, ob das so passt und zukunftssicher ist.

---

Dann müsste ich jetzt nur noch den Thread auf kodinerds.net dementsprechend vorbereiten und neue Kurzlinks erstellen, diesmal aber nicht mit tinyurl.com, da man die im Nachhinein nicht managen kann. Da suche ich noch ne Alternative.

Sofern alles passt - also gerade auch in Bezug auf die Idee mit den Update-Benachrichtigungen - würde ich das dann vermutlich innerhalb der nächsten 4 - 5 Tage mergen.
