### ISSUE TITLE
Regionale WDR TV Sender

### ISSUE THREAD

**Issue by mezen** [jnk22/kodinerds-iptv#471]
Hi,

es wäre schön wenn auch die regionalen WDR Sender wie WDR Dortmund oder WDR Südwestfalen (Siegen) angeboten werden könnte.

**Comment by EmBeEins** [comment]
WDR Global     : https://wdrfs247.akamaized.net/hls/live/681509/wdr_msl4_fs247/master.m3u8
WDR Aachen       : https://wdrlokalzeit.akamaized.net/hls/live/2018019-b/wdrlz_aachen/master.m3u8
WDR Bonn            : https://wdrlokalzeit.akamaized.net/hls/live/2018021-b/wdrlz_bonn/master.m3u8
WDR Bergisches Land : https://wdrlokalzeit.akamaized.net/hls/live/2018028-b/wdrlz_wuppertal/master.m3u8
WDR Dortmund        : https://wdrlokalzeit.akamaized.net/hls/live/2018022-b/wdrlz_dortmund/master.m3u8
WDR Düsseldorf      : https://wdrlokalzeit.akamaized.net/hls/live/2018023-b/wdrlz_duesseldorf/master.m3u8
WDR Duisburg        : https://wdrlokalzeit.akamaized.net/hls/live/2018024-b/wdrlz_duisburg/master.m3u8
WDR Köln            : https://wdrlokalzeit.akamaized.net/hls/live/2023550-b/wdrlz_koeln/master.m3u8
WDR Münsterland     : https://wdrlokalzeit.akamaized.net/hls/live/2018025-b/wdrlz_muensterland/master.m3u8
WDR Ostwestfalen    : https://wdrlokalzeit.akamaized.net/hls/live/2018026-b/wdrlz_bielefeld/master.m3u8
WDR Südwestfalen    : https://wdrlokalzeit.akamaized.net/hls/live/2018020-b/wdrlz_siegen/master.m3u8
WDR Ruhr            : https://wdrlokalzeit.akamaized.net/hls/live/2018027-b/wdrlz_essen/master.m3u8

**Comment by bjoerns1983** [comment]
Okay sind drin.
