### ISSUE TITLE
Parlamentsfernsehen

### ISSUE THREAD

**Issue by SnejPro** [jnk22/kodinerds-iptv#472]
Scheinbar hat der Bundestag den Dienstleister gewechselt und die alten Streaming-URLs funktionieren nicht mehr,

**Comment by bjoerns1983** [comment]
Ich habe nun den Link für Parlamentsfernsehen 1 ausgetauscht da der neue eine wesentlich bessere Qualität bietet.
Leider ist Parlamentsfernsehen 2 derzeit nicht in der Mediathek drin, so das der alte, aber funktionale Link, bestehen bleibt.

**Comment by bazi-98** [comment]
Mit ...
https://bttv-live-z.r53.cdn.tv1.eu/13014bundestag-hk2/_definst_/live/video/hk2_de.smil/playlist.m3u8
habe ich auch eine Übertragung in HD vermute mal von Bundestags TV 2, Die Adresse habe mit mit blosen testen gefunden ;)

**Comment by SnejPro** [comment]
Ich habe mal beim Bundestag nach statischen Streaming-URLs und einer Systematik nach welcher die Kanäle bespielt werden gefragt: https://fragdenstaat.de/anfrage/streaming-urls/

**Comment by SnejPro** [comment]
@bjoerns1983 Mir ist aufgefallen, dass auch 3 und 4 funktioniert:
https://bttv-live-z.r53.cdn.tv1.eu/13014bundestag-hk3/_definst_/live/video/hk3_de.smil/playlist.m3u8
https://bttv-live-z.r53.cdn.tv1.eu/13014bundestag-hk4/_definst_/live/video/hk4_de.smil/playlist.m3u8

**Comment by bjoerns1983** [comment]
Danke, habe diese auch hinzugefügt
