### ISSUE TITLE
Nickelodeon = Comedy Central+1?

### ISSUE THREAD

**Issue by forenta** [jnk22/kodinerds-iptv#484]
Soll das deutsche Nickelodeon laut Liste sein, bekomme dort aber aktuell nur ein Testbild von CC+1?
https://github.com/jnk22/kodinerds-iptv/blob/master/iptv/clean/clean_tv_main.m3u#L41

**Comment by bjoerns1983** [comment]
Das kann gut sein weil Nickelodeon nur Tagüber sendet.
Derzeit sind Sie wieder auf Sendung.
