### ISSUE TITLE
Streamtest Batch Script

### ISSUE THREAD

**Issue by ReinhardHenning** [jnk22/kodinerds-iptv#493]
Gibt es eine Möglichkeit, per Script in einem Rutsch eine ganze M3U Datei auf (nicht) funktionierende Streams zu testen? Das würde doch helfen die ungültig gewordenen  Streams schnell rauszuschmeissen.

**Comment by bjoerns1983** [comment]
siehe:
https://github.com/jnk22/kodinerds-iptv/issues/407
bzw hier:
https://github.com/jnk22/kodinerds-iptv/issues/421
