### ISSUE TITLE
Samsung TV - Alle deutschen Streams

### ISSUE THREAD

**Issue by Food4Monkeys** [jnk22/kodinerds-iptv#502]
Hi,

ich habe eine M3U über Samsung TV - Alle deutschen Streams, interesse daran? Könnte sie dann per Pull-Request hinzu fügen.

Alle mit Logos.

Wenn ja, wie soll ich die m3u nennen und welchen group-title= soll ich nehmen?

**Comment by bjoerns1983** [comment]
@jnk22 irgendein Vorschlag dazu?

**Comment by jnk22** [comment]
@Food4Monkeys Gibt es da eine Übersicht, um welche Sender es sich da genau handelt?

Die Liste kannst du ja gerne hier schon mal als Code anfügen, wenn du möchtest.

**Comment by bjoerns1983** [comment]
Dürfte das gleiche Thema sein wie #527 
Wahrscheinlich eine rechtliche Grauzone genau wie bei Pluto.tv und ausserden gibt es für diese Sender bereits automatisiert erstellte Liste inkl. EPG im Netz.
Sehe keinen Grund die Sender in die Liste mit aufzunehmen.
