### ISSUE TITLE
RBB Streams not working anymore 

### ISSUE THREAD

**Issue by tomber42** [jnk22/kodinerds-iptv#519]
Hi, rbb Streams seem to be invalid now, example https://rbb-rbb888-live.cast.addradio.de/rbb/rbb888/live/mp3/mid, there is an announcement that this stream will cut off soon

**Comment by bjoerns1983** [comment]
I think i found a Solution for RBB 88.8:
https://www.rbb888.de/hilfe/live_hoeren.html
Althought for the others i have to search. If you know similiar m3u linkes help would be appriciated.

**Comment by tomber42** [comment]
Yes it seems RBB (and all other ARD Stations?) had change to rndfnk.com as streaming service provider, also see https://www.gl-systemhaus.de/blog/weitere-zusammenarbeit-mit-ard-und-zdf . The new rbb88.8 URL is http://dispatcher.rndfnk.com/rbb/rbb888/live/mp3/mid

**Comment by tomber42** [comment]
For RBB radio fritz the new one is:
#EXTM3U

#EXTINF:-1,Fritz vom rbb live hören - www.fritz.de
http://dispatcher.rndfnk.com/rbb/fritz/live/mp3/mid

**Comment by tomber42** [comment]
so it seems the new url for all rbb stations is
http://dispatcher.rndfnk.com/rbb/NAMEOFSTATION/live/mp3/mid

**Comment by bjoerns1983** [comment]
Okay cool, i will see that i update the links in the evening

**Comment by pboettcher** [comment]
> so it seems the new url for all rbb stations is http://dispatcher.rndfnk.com/rbb/NAMEOFSTATION/live/mp3/mid

Sorry, this URL returns me 404 as of 2021-12-28T13:39.

Their website: https://www.antennebrandenburg.de/hilfe/antenne-im-netz.html lists some stream redirector links:

Wenn Sie den Antenne-Livestream über externe Geräte und Anwendungen abspielen möchten, nutzen Sie die folgenden URLs

- Livestream MP3 hohe Qualität | http://www.antennebrandenburg.de/livemp3
- Livestream MP3 niedrige Qualität | http://www.antennebrandenburg.de/livemp3_s

Cottbus

- Livestream MP3 hohe Qualität | http://www.antennebrandenburg.de/cottbus/livemp3
- Livestream MP3 niedrige Qualität | http://www.antennebrandenburg.de/cottbus/livemp3_s

Frankfurt

- Livestream MP3 hohe Qualität | http://www.antennebrandenburg.de/frankfurt/livemp3
- Livestream MP3 niedrige Qualität | http://www.antennebrandenburg.de/frankfurt/livemp3_s

Perleberg

- Livestream MP3 hohe Qualität | http://www.antennebrandenburg.de/perleberg/livemp3
- Livestream MP3 niedrige Qualität | http://www.antennebrandenburg.de/perleberg/livemp3_s

Prenzlau

- Livestream MP3 hohe Qualität | http://www.antennebrandenburg.de/prenzlau/livemp3
- Livestream MP3 niedrige Qualität | http://www.antennebrandenburg.de/prenzlau/livemp3_s

An URL to which they redirect looks as follows:

http://d141.rndfnk.com/ard/rbb/antennebrandenburg/live/mp3/128/stream.mp3?sid=22ujJ3PJu2IvW3WF1XTuFz5p3Nt&token=QF4xHmgWdFX1O6raxXKTgjx2f8Z3xKnHz7jgSL8la14&tvf=QVAK6Wj-xBZkMTQxLnJuZGZuay5jb20

It uses tokens that will be obviously changed, say, once a day and therefore shouldn't be used directly.

**Comment by tomber42** [comment]
> > so it seems the new url for all rbb stations is http://dispatcher.rndfnk.com/rbb/NAMEOFSTATION/live/mp3/mid
> 
> Sorry, this URL returns me 404 as of 2021-12-28T13:39.
Yes because you have to replace NAMEOFTHESTATION :)

**Comment by pboettcher** [comment]
> Yes because you have to replace NAMEOFTHESTATION :)

Oh, my bad ... Thank you.

**Comment by bjoerns1983** [comment]
@freddii wäre es nicht vielleicht besser gewesen die links ala http://www.rbbkultur.de/live.m3u zu nehmen die man auf den Hilfe Seiten der Sender findet?
Ich gehe mal davon aus das die extrem selten geändert werden.

**Comment by freddii** [comment]
[ch denke mal das http://dispatcher.rndfnk.com/rbb/rbbkultur/live/mp3/high erstmal für längere Zeit so bleibt, aber es kann schon sein, dass die m3u die bessere Wahl wäre. 
Ich habe dazu keine genaueren Infos.
