### ISSUE TITLE
YouTube streams funktionieren nicht ohne plugin

### ISSUE THREAD

**Issue by ooglyhLL** [jnk22/kodinerds-iptv#521]
Die m3u enthält mehrere Links zu YouTube Streams der Form
`https://www.youtube.com/embed/<ID>`
Das scheint mit dem IPTV simple client nicht (mehr?) zu funktionieren.

Über eine plugin-URL der Form
`plugin://plugin.video.youtube/play/?video_id=<ID>`
kann man das fixen. Aber ist das überhaupt der richtige Ansatz? Sollte das der PVR client (oder inputstream) selbst erkennen?

**Comment by bjoerns1983** [comment]
Es sind insgesamt vier Sender die mit Youtube Links in der Liste sind:
RiC (Stream ging vorhin nicht)
RT en Espanol
Pearl TV
Sky News UK

So wie es aussieht funktionieren die Links ja nicht wenn das Youtube Addon (was afaik nicht wirklich einfach zu installieren ist) mit in Kodi installiert wird.
Ich weiss nicht wie sinnvoll es ist solche Links mit in der Liste zu haben.

@jnk22 @freddii was sagt Ihr dazu?

**Comment by blueicehaller** [comment]
Sender Nummer Fünf: MelodieTV https://youtu.be/1nHkPNp4Yc0

**Comment by bjoerns1983** [comment]
Habe ich noch garnicht mitgezählt da derzeit nicht in der source.yaml vorhanden.

**Comment by bjoerns1983** [comment]
@jnk22 @freddii irgendeine Meinung dazu wie wir mit den Youtube Links umgehen sollen?

**Comment by freddii** [comment]
Mit VLC und der clean Liste (http://bit.ly/kn-clean) funktionieren die Youtube Streams.

**Comment by bjoerns1983** [comment]
In Kodi werden Sie aber wohl ohne das youtube Plugin nicht gehen.

**Comment by bjoerns1983** [comment]
Die Links auf plugin://plugin.video.youtube umzubiegen bringt es auch nicht. Das löst das Problem wohl für Kodi macht die youtube Links aber für alle anderen Programme kaputt die diese Links unterstützen.
Ich bin erstmal dafür die Youtube Links so zu lassen wie sie sind, ggf. Sie aber alle auf eine Standardschreibweise zu bringen.

**Comment by ooglyhLL** [comment]
Die Links könnten doch beim Erzeugen der `kn-kodi-*` Playlisten gewandelt werden, oder nicht?

**Comment by bjoerns1983** [comment]
Du meinst das man die Links nur für die Kodi Liste abwandelt?

**Comment by ooglyhLL** [comment]
Ja, genau.

**Comment by bjoerns1983** [comment]
So damit sollten die Youtube Links passend für Kodi umgeschrieben werden.
