### ISSUE TITLE
[AT] ORF stream urls broken again..

### ISSUE THREAD

**Issue by gsantner** [jnk22/kodinerds-iptv#536]
Hello, the austrian ORF streams URLs don't work once again. Seems like DRM / license key is mandatory now.... - (plus GeoBlock)
 
* New URL to try:  `https://orf2.mdn.ors.at/out/u/orf2/drmqxa/manifest.mpd`
* Related addon issue: `https://github.com/s0faking/plugin.video.orftvthek/issues/118`
* Related addon change: `https://github.com/s0faking/plugin.video.orftvthek/commit/8222472b0e8fd36f69408b2dfe071ba1685efe2a`

Somebody has an URL around that works in Austria - without DRM \*\*\*\*?

**Comment by bjoerns1983** [comment]
I doubt that there is a legal DRM Free m3u if ORF decided to use a DRM.
Even there is no free Zattoo Accounts in Austria, than you could have used Telerising.

**Comment by bjoerns1983** [comment]
@jnk22 i think we should remove those links.
Seems that you could only get ORF now using a dedicated plugin for Kodi or Stuff like Telerising with Wilmaa, Teleboy etc.
Dash Streams could also be a workaround.

**Comment by gloompart** [comment]
Last time this happened ORF Streams were gone for some weeks and then came back...
for now  i'm only able to get ORF III running

https://orf3.mdn.ors.at/out/u/orf3/qxb/manifest_6.m3u8

this still works

**Comment by gsantner** [comment]
The streams are not accessible simply by URL alone anymore as far I know. Unless somebody knows otherwise?

I close this at least.
