### ISSUE TITLE
RBB is missing

### ISSUE THREAD

**Issue by rdorsch** [jnk22/kodinerds-iptv#537]
The livestream of RBB seems to be missing:

https://www.rbb-online.de/fernsehen/live/

Not sure if this is the correct URL:

https://rbb-hls-berlin.akamaized.net/hls/live/2017824/rbb_berlin/master-1080p-5128.m3u8

Thanks
Rainer

**Comment by bjoerns1983** [comment]
The streams for RBB Berlin and Brandenburg are in the list and are working.
Just checked it with VLC.

**Comment by rdorsch** [comment]
indeed, it seems a problem with my tvheadend installation, it does not report RBB for some reason anymore as service.

**Comment by bjoerns1983** [comment]
Maybe a Timeout problem?

**Comment by rdorsch** [comment]
On Mittwoch, 9. Februar 2022 07:11:29 CET bjoerns1983 wrote:
> Maybe a Timeout problem?

Do you have a pointer to the tvheadend timeout problem? A search did not show 
anything relevant.

What solved the problem for me:
In Muxes I set the status from inactive to active. The the search result went 
from error to OK.

I am wondering why I have to trigger this. On the bottom automatic updates is 
selected. 

Thanks
Rainer
