### ISSUE TITLE
Radio 90.1 MG

### ISSUE THREAD

**Issue by SkyBird1980** [jnk22/kodinerds-iptv#54]
http://edge.live.mp3.mdn.newmedia.nacamar.net/ps-radiomg/livestream.mp3

**Comment by jnk22** [comment]
Habe den Sender gestern Abend schon hinzugefügt, nur noch nicht im Thread geschrieben, sorry.
Hoffe du hast dir da jetzt noch keine Arbeit mit gemacht @SkyBird1980

Siehe #51
