### ISSUE TITLE
Neuer Schweizer Regionalsender Telebasel

### ISSUE THREAD

**Issue by reneol** [jnk22/kodinerds-iptv#55]
- Stream niedrige Qualität: 
`rtsp://xapp510394368c1000199.f.l.z.lb.core-cdn.net:1935/10096xtelebase/_definst_/1000199copo/live/app510394368/w162136077/live_de_500`
- Stream hohe Qualität: 
`rtsp://xapp510394368c1000199.f.l.z.lb.core-cdn.net:1935/10096xtelebase/_definst_/1000199copo/live/app510394368/w162136077/live_de_1500`

Quelle: https://telebasel.ch/live/

**Comment by jnk22** [comment]
Der Stream geht leider nicht, habe aber alternativ diesen hier gefunden (wenn auch nicht so gute Qualität).
http://xapp510394368c1000199.f.l.z.lb.core-cdn.net/10096xtelebase/ios_500/master.m3u8
