### ISSUE TITLE
ERF 1 URL has changed

### ISSUE THREAD

**Issue by blechma** [jnk22/kodinerds-iptv#557]
Hello,

the IPTV URL auf "ERF 1" has changed.
The new URL is 
https://bcovlive-a.akamaihd.net/8d3c5f8c76724987a30eb69d4ba6ca80/eu-central-1/6194387526001/profile_0/chunklist.m3u8
Thank you for your help in advance
Kind regards
Matthias

**Comment by blueicehaller** [comment]
We normally use the master.m3u .
`https://bcovlive-a.akamaihd.net/8d3c5f8c76724987a30eb69d4ba6ca80/eu-central-1/6194387526001/profile_0/chunklist.m3u8`

**Comment by blechma** [comment]
Thank you very much. Your link works perfectly. I am absolute beginner and tried to extract the link from the network stream.

**Comment by bjoerns1983** [comment]
Merged it but changed the URL to the playlist.m3u8 so that client could choose the resolution by itself.

**Comment by blechma** [comment]
Thank you very much. It works!
