### ISSUE TITLE
Weitere Schweizer Regionalsender, wie TeleZüri, TeleBärn, TeleM1, TVO, TeleBielingue

### ISSUE THREAD

**Issue by reneol** [jnk22/kodinerds-iptv#56]
Falls möglich, kann hier die Stream-URL aus den Playern auf den jeweiligen Seiten extrahiert und der Liste hinzugefügt werden

Quellen:
- TeleZüri: http://www.telezueri.ch/live  (EPG-ID: TeleZuri.ch)
- TeleBärn: http://www.telebaern.tv/live
- TeleM1: http://www.telem1.ch/live
- TVO: http://www.tvo-online.ch/?playlist=livestream (EPG-ID: TVO.ch)
- TeleBielingue: http://www.telebielingue.ch/de

**Comment by herrTravolta** [comment]
Stream URL & Logo für 2 CH Sender:

`#EXTINF:-1 tvg-id="TeleZuri.ch" tvg-logo="http://www.telezueri.ch/images/c8ad2f9.png" group-title="IPTV",Tele Zueri HD (720p)
http://klive-a.akamaihd.net/dc-1/live/hls/p/1719221/e/1_hoislpiz/t/Bnhb6PI9GIjiKE7UgQC_qg/index-s32.m3u8

#EXTINF:-1 tvg-id="" tvg-logo="http://www.telebaern.tv/images/886075a.png" group-title="IPTV",Tele Bärn HD (720p)
http://klive-a.akamaihd.net/dc-1/live/hls/p/1719221/e/1_0mc3z57p/sd/10000/t/XTGwenpKUhx_fbVnsiu9MQ/index-s32.m3u8`
