### ISSUE TITLE
Radio Bob outdated?

### ISSUE THREAD

**Issue by cap-blackbeard** [jnk22/kodinerds-iptv#598]
Radio Bob lässt sich nicht mehr abspielen.
Hier ist der Stream für Hessen direkt vom Radiosender:
http://streams.radiobob.de/bob-live/mp3-192/mediaplayer

oder die komplette Seite mit allen verfügbaren Streams:
https://www.radiobob.de/radiobob/empfang/livestream

**Comment by bjoerns1983** [comment]
#600
