### ISSUE TITLE
Radio Teddy Hessen

### ISSUE THREAD

**Issue by cap-blackbeard** [jnk22/kodinerds-iptv#599]
Wenn möglich, bitte Radio Teddy für die Region Hessen in die Liste aufnehmen:
streamtdy.ir-media-tec.com/sc-hessen/mp3-128/web/play.mp3

Natürlich freuen meine Kinder sich auch über weitere Stream dieses Radiosenders:
https://www.radioteddy.de/programm/radio-teddy-hoeren/Online-id533671.html

Ps.: Radio Teddy "live" ist in der Liste schon vorhanden.

**Comment by bjoerns1983** [comment]
#601
