### ISSUE TITLE
Radio Köln bitte mit aufnehmen 

### ISSUE THREAD

**Issue by Senseless-Creature** [jnk22/kodinerds-iptv#603]
Hey Leute - echt cool, was ihr hier bereitstellt - dafür erst mal ein fettes Dankeschön!!

Ich und ein paar Freunde würden uns noch riesig über Radio Köln freuen, falls das möglich wäre: https://www.radiokoeln.de/

Liebe Grüße

**Comment by bjoerns1983** [comment]
Hier sind schon mal Links, haber derzeit aber keine Zeit Sie hinzuzufügen:
Live
https://stream.lokalradio.nrw/444z7kb
80er
https://stream.lokalradio.nrw/444zgxt
90er
https://stream.lokalradio.nrw/444zkbb
2000er
https://stream.lokalradio.nrw/4456wvh
Deutschpop
https://stream.lokalradio.nrw/444znpt
Love
https://stream.lokalradio.nrw/444zwtb
Lounge
https://stream.lokalradio.nrw/444ztft
Karneval
https://stream.lokalradio.nrw/444zdhk
XMas
https://stream.lokalradio.nrw/444zr3b
Urban
https://stream.lokalradio.nrw/44528bb
Oldie
https://stream.lokalradio.nrw/44548n3
Rock
https://stream.lokalradio.nrw/444zz6t
Rockclassic
https://stream.lokalradio.nrw/44578v5
HipHop
https://stream.lokalradio.nrw/4458c6f
Country
https://stream.lokalradio.nrw/4457z6s
Singer
https://stream.lokalradio.nrw/44566w7
Top40
https://stream.lokalradio.nrw/44525xt
Dance
https://stream.lokalradio.nrw/4456jvv
Schlager
https://stream.lokalradio.nrw/44523kb
Sommer
https://stream.lokalradio.nrw/4457mts

Vielleicht findet sich da ja jemand für.

**Comment by bjoerns1983** [comment]
Hat sich natürlich keiner die Mühe gemacht also habe ich Sie hinzugefügt.
 #622
