### ISSUE TITLE
Geolocked streams für Sportschau/WDR

### ISSUE THREAD

**Issue by prof-membrane** [jnk22/kodinerds-iptv#61]
Die Übertragungen der Sportschau/WDR sind oft nur auf Deutschland begrenzt, daher läuft auf den internationalen Kanälen nichts.

Der erste Kanal (http://ardevent1.wdr.de/i/wdrardevent1_weltweit@112049/master.m3u8) überträgt in nächster zeit nur offene Streams, daher hab ich keine URL. Nur der zweite wird anscheinend als Geo-Stream genommen: http://ardevent2geo.wdr.de/i/wdrardevent2_geogeblockt@112050/master.m3u8.

Inwiefern sich die Streams zu den normalen WDR Streams unterscheiden kann ich nicht sagen. Auf jeden Fall werde ich das beobachten.

**Comment by prof-membrane** [comment]
Ich hab mich mit der Thematik mal etwas beschäftigt. Es scheint, als ob die Sportschau/ARD zwei Sender beim WDR unterhält. Fall diese ausgelastet sind, wird auf die Eventsender des WDR zurückgegriffen. Der erste ARD Stream ist weltweit empfangbar, der zweite nur in DE. 

Beim WDR ist WDR Event 1 zweifach als Stream verfügbar - weltweit und auf DE begrenzt. Ob und wie sich die Streams unterscheiden kann ich nicht sagen. Im Zweifel würde ich den DE Stream nehmen.

Hier mal eine Auflistung der bekannten Streams:
```
#EXTINF:-1 tvg-id="ARDEvent1.de" tvg-logo="ard.png",ARD Event 1 
http://ardevent1.wdr.de/i/wdrardevent1_weltweit@112049/master.m3u8
#EXTINF:-1 tvg-id="ARDEvent2.de" tvg-logo="ard.png",ARD Event 2
http://ardevent2geo.wdr.de/i/wdrardevent2_geogeblockt@112050/master.m3u8

#EXTINF:-1 tvg-id="ARDEvent1.de" tvg-logo="ard.png",ARD Event 1 AKAMAI
http://wdr_ardevent1-lh.akamaihd.net/i/wdrardevent1_weltweit@112049/master.m3u8
#EXTINF:-1 tvg-id="ARDEvent2.de" tvg-logo="ard.png",ARD Event 2 AKAMAI
http://wdr_ardevent2-lh.akamaihd.net/i/wdrardevent2_geogeblockt@112050/master.m3u8

#EXTINF:-1 tvg-id="WDREvent1.de" tvg-logo="wdr.png",WDR Event 1
http://event1geo.wdr.de/i/wdrevent1_geogeblockt@112051/master.m3u8
#EXTINF:-1 tvg-id="WDREvent2.de" tvg-logo="wdr.png",WDR Event 2
http://event2.wdr.de/i/wdrevent2_weltweit@112052/master.m3u8
#EXTINF:-1 tvg-id="WDREvent3.de" tvg-logo="wdr.png",WDR Event 3
http://event3.wdr.de/i/wdrevent3_weltweit@112053/master.m3u8
#EXTINF:-1 tvg-id="WDREvent4.de" tvg-logo="wdr.png",WDR Event 4
http://event4.wdr.de/i/wdrevent4_weltweit@112054/master.m3u8

#EXTINF:-1 tvg-id="WDREvent2.de" tvg-logo="wdr.png",WDR Event 2 AKAMAI
http://wdr_event2-lh.akamaihd.net/i/wdrevent2_weltweit@112052/master.m3u8
#EXTINF:-1 tvg-id="WDREvent3.de" tvg-logo="wdr.png",WDR Event 3 AKAMAI
http://wdr_event3-lh.akamaihd.net/i/wdrevent3_weltweit@112053/master.m3u8
#EXTINF:-1 tvg-id="WDREvent4.de" tvg-logo="wdr.png",WDR Event 4 AKAMAI
http://wdr_event4-lh.akamaihd.net/i/wdrevent4_weltweit@112054/master.m3u8
```

Es kann gut sein, dass sich die Konfiguration der Streams ändern kann (Geolock an/aus). Die IDs müssen bleiben, damit mein EPG passt. Akamai Streams sind markiert, der Zusatz kann aber gerne zurückgenommen werden.

Im übrigen würde ich es begrüßen, wenn du auch eine m3u mit den vollständigen m3u8 Playlists bereitstellen würdest. Ab und an verändern sich die Streams, manchmal kommen auch neue (bessere) hinzu.

**Comment by prof-membrane** [comment]
Kannst du die Streams bitte eintragen/berichtigen? Ich möchte in den nächsten Tagen das EPG veröffentlichen. Gerade diese Sender hier sind wichtig, da hier 75% der Sendungen laufen.

**Comment by jnk22** [comment]
Werde erstmal die AKAMAI-Streams alleine verwenden wenn das in Ordnung geht.

**Comment by prof-membrane** [comment]
Ich bin mir gerade nicht einmal sicher, ob die nicht auf die selben Quellen zeigen. Für WDR1 kenne ich den Akamai Stream leider nicht.

**Comment by jnk22** [comment]
Gerade gesehen, WDR Event 1 haben wir schon als Akamai-Stream drinnen.

Prinzipiell würde sich dann so eigtl. nichts an den WDR-Sendern ändern, wären also nur die beiden ARD-Streams neu.

Passt das so?

`#EXTINF:-1 tvg-name="WDR Event 1" tvg-id="WDREvent1.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/wdr.png" group-title="IPTV-Extra",WDR Event 1
http://wdr_ardevent1-lh.akamaihd.net/i/wdrardevent1_weltweit@112049/index_1_av-p.m3u8
#EXTINF:-1 tvg-name="WDR Event 2" tvg-id="WDREvent2.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/wdr.png" group-title="IPTV-Extra",WDR Event 2
http://wdr_event2-lh.akamaihd.net/i/wdrevent2_weltweit@112052/index_1_av-p.m3u8
#EXTINF:-1 tvg-name="WDR Event 3" tvg-id="WDREvent3.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/wdr.png" group-title="IPTV-Extra",WDR Event 3
http://wdr_event3-lh.akamaihd.net/i/wdrevent3_weltweit@112053/index_1_av-p.m3u8
#EXTINF:-1 tvg-name="WDR Event 4" tvg-id="WDREvent4.de" tvg-logo="https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/logos/tv/wdr.png" group-title="IPTV-Extra",WDR Event 4
http://wdr_event4-lh.akamaihd.net/i/wdrevent4_weltweit@112054/index_1_av-p.m3u8`

**Comment by jnk22** [comment]
Wobei WDR Event 1 dann identisch mit ARD Event 1 wäre, siehe hier:

ARD Event 1:
http://wdr_ardevent1-lh.akamaihd.net/i/wdrardevent1_weltweit@112049/index_1_av-p.m3u8

WDR Event 1:
http://wdr_ardevent1-lh.akamaihd.net/i/wdrardevent1_weltweit@112049/index_1_av-p.m3u8

Dann doch lieber erstmal den WDR-eigenen "WDR Event 1"-Stream?
http://event1geo.wdr.de/i/wdrevent1_geogeblockt@112051/master.m3u8

**Comment by prof-membrane** [comment]
So sollte es stimmen.
