### ISSUE TITLE
New Channel // MagentaMusik

### ISSUE THREAD

**Issue by EmBeEins** [jnk22/kodinerds-iptv#631]
https://streaming.magentamusik.de/csm/573870/magentamusik1/index.m3u8

https://streaming.magentamusik.de/csm/573871/magentamusik2/index.m3u8

**Comment by freddii** [comment]
fixed in https://github.com/jnk22/kodinerds-iptv/commit/73619cbb5d8475f622e94f4c670c3b37de631093

**Comment by freddii** [comment]
Der Stream spielt nur ein kurzes Video ab und streamt nicht von Wacken.
Ist das so gewollt?
