### ISSUE TITLE
ONE HD Stream funktioniert nicht 

### ISSUE THREAD

**Issue by hasifantasy** [jnk22/kodinerds-iptv#636]
Hallo,

vielen Dank für Eure Arbeit an der IPTV Stream Liste.
Leider funktioniert der ONE HD Stream nicht. Weder für Kodi, noch im iptvnator.
Könnt Ihr das bitte beheben?

Wie kann man zukünftig nachhaltig die Funktionsfähigkeit der Stream Links sichern, damit frühzeitig eine Stream-Datei Änderung auffällt?

Danke & mfG
Stefan

**Comment by bjoerns1983** [comment]
Funktiniert hier ohne Probleme in Kodi mit IPTV Simple

**Comment by hasifantasy** [comment]
Funktioniert wieder seit dem letzten DRM Prime Update. Case kann geschlossen werden. Entschuldigung für die verspätete i.O. Meldung.
