### ISSUE TITLE
TV-Sender "RTL II You" löschen

### ISSUE THREAD

**Issue by jnk22** [jnk22/kodinerds-iptv#64]
Sender stellt zum 30.6.17 Betrieb ein. Sender kann daher gelöscht werden (Links + Logo)

**Comment by SkyBird1980** [comment]
#68 
#67 
#66 
#65 
Nur noch Logos über-

**Comment by jnk22** [comment]
Super :) Werde das dann morgen Abend passend zur Einstellung des Sendebetriebs mergen, Logos kommen dann auch noch raus.

Danke dir!

**Comment by jnk22** [comment]
Ist drin.
closes #64
