### ISSUE TITLE
Kika removed

### ISSUE THREAD

**Issue by rdorsch** [jnk22/kodinerds-iptv#643]
Hi,

I see that kika got removed from the generated pipe etc. files, e.g.

https://github.com/jnk22/kodinerds-iptv/commit/48cee8ecf18677f62c89db4ec82a660a1d83aec8

I checked, https://kikageohls.akamaized.net/hls/live/2022693/livetvkika_de/master.m3u8 which is still in iptv/source.yaml works for me in mpv.

Not sure how that exactly happens, but is there a manual trigger to regenerated the pipe etc. files needed?

Thanks
Rainer

**Comment by bjoerns1983** [comment]
Can you please recheck? I think one of the last merged commits was a bit faulty.

**Comment by rdorsch** [comment]
Yes, works again perfectly.

Many thanks for the quick fix.
