### ISSUE TITLE
Verwaltungsaufwand Listenpflege

### ISSUE THREAD

**Issue by prof-membrane** [jnk22/kodinerds-iptv#80]
Wie ich sehe wird die Listenpflege sehr unübersichtlich. Wenn du möchtest kann ich ein kleines Script schreiben, was dir die manuelle Arbeit erleichtert. 

Als Ausgangsgrundlage könnten verschiedene Playlists mit folgenden Inhalten stehen:
- Öffentlich rechliche Sender DE
- Private Sender DE
- Sender CH
- Eventsender
- Lokalsender Sachsen
- Lokalsender Sachsen-Anhalt
- Lokalsender (weitere Bundesländer)
- Weitere Sender

Der User könnte dann sein individuelles Programmpaket aus den Sendegruppen zusammenklicken.

**Comment by jnk22** [comment]
Habe mir auch schon überlegt ob ich mir nicht lieber mal ein kleines Programm mit GUI schreiben soll, mit dem ich das ganze dann leichter erledigen kann. War mir nur nicht ganz sicher, welche der beiden Wege dann in Zukunft schneller sei :D

Hatte auch kaum mit so einer großen Nachfrage gerechnet. Da wird das per Hand einfügen/editieren natürlich mit mal zu mal komplizierter, v.a. wenn man wie in #47 angedeutet Sender noch in mehrere Gruppen unterteilen möchte (was ich in Anbetracht der Menge der Sender durchaus für angebracht halte). Wäre dann eigtl. wirklich nur noch mit automatischen Ablauf denkbar.

Wie in etwa stellst du dir das Skript denn vor?

**Comment by back-to** [comment]
Ich habe mir für meine Private liste ein Python script gemacht
wo ich einfach von einer **JSON** datei als quelle alles erstelle

Es wird dann nach ABC sortiert erst für Gruppen danach nach Sendernamen,
man könnte auch noch mehr sortier optionen erstellen.
Aber für mich reicht das so momentan.

https://gist.github.com/back-to/5a678cda8334c99a8d5c09374b624896

Das wird hier wohl hier nicht direkt funktionieren da ihr mehrer listen erstellen wollte,
aber einfach mal so als anregung.

**Comment by LipkeGu** [comment]
Nebenbei einer GUI könnte man auch gleich mal die Gruppen einbauen in die playlists! https://github.com/kodi-pvr/pvr.iptvsimple/pull/153

**Comment by jnk22** [comment]
Ist das denn jetzt offiziell supported in Kodi 17.4 Final?

Dann könnte man das natürlich auch noch dafür anbieten, ansonsten wäre das eh erst für Kodi 18 interessant geworden.

Gibt aber eh vorerst mal das Update bzgl. der "Gesamt-Struktur", inkl. einigen Fixes und kleineren Änderungen.
https://github.com/jnk22/kodinerds-iptv/pull/127
https://github.com/jnk22/entertain-iptv/pull/5

**Comment by flubshi** [comment]
> Ist das denn jetzt offiziell supported in Kodi 17.4 Final?

Das lässt sich für mein Verständnis nicht pauschal beantworten. Distributionen die das offizielle binary Referenz Repository verwenden sollten das integriert haben.
Also: osmc sollte es haben!
Libreelec verwaltet die Binary Addons selbst. Hier wird die entsprechende Version wohl ab Libreelec 8.2 verwendet.
In Arch Linux kann man die PVR Addons aus dem AUR separat installieren. Dort ist die entsprechende Version verfügbar.
Wie es für andere Distributionen aussieht kann ich nicht sagen.

Allerdings ist dieses Feature insofern abwärts kompatibel, als dass Clients mit älterer Version immerhin jeweils den vollen Namen (also jeweils einen langen Gruppennamen mit Semikolon pro Sender) sehen. Das ist nicht schön, würde aber nicht die gesamte Funktionalität der Programmlisten brechen.

**Comment by jnk22** [comment]
Die Struktur hat sich ja nochmal stark geändert und dadurch wurde es deutlich leichter, daran zu arbeiten.
Bis ich dazu komme dafür was zu schreiben oder sich sonst etwas ergibt, werde ich hier erstmal schließen.
