### ISSUE TITLE
Listen für RPi/Synology etc. erstellen

### ISSUE THREAD

**Issue by jnk22** [jnk22/kodinerds-iptv#90]

**Comment by tzwn** [comment]
Möchtest du die modifizierten Listen für die "scheinbar problematischen" Systeme mit in dein Master übernehmen?

**Comment by jnk22** [comment]
Wenn das für dich in Ordnung ist, wäre denke ich am einfachste das mit hier reinzunehmen, da sich das ja auf jeden Fall bewährt hat, eine Extra-Liste zu führen.

Würde dann auch demnächst mal die ganzen Anleitungen etwas anpassen wollen, da ja doch immer wieder mal das Problem auftaucht, dass jmd. nicht genau weiß was das Problem auf den Problem-Geräten ist.

**Comment by tzwn** [comment]
Na klar ist das okay. Die zusätzlich Liste entstand ja im Grunde aus der Not heraus und war ja meinem Verständnis nach als Provisorium gedacht. Die Pflege wird dadurch ja auch vereinfacht. 

Ich bin demnächst auch längere Zeit in Ausland unterwegs und kann dann leider auch nicht garantieren, die Listen aktuell zu halten. 
Sich für eine Gewisse Zeit des Übergangs - jedoch sollten dann alle Nutzer irgendwann umsteigen. 

Ich habe übrigens heute auf einem x86 mit der normalen "pipe"-Liste keine Services bekommen. Ohne den zerolatency Parameter ging es super.

**Comment by jnk22** [comment]
Alles klar! Dann schon mal viel Spaß im Ausland :)

Ich schau mir das vll. auch nochmal genauer an mit dem Parameter, ob der wirklich so viel bringt. Hatte ja selber erst vor ein paar Monaten damit angefangen und das vorerst (weils gut funktioniert hat) so für mich übernommen. Wenn das gar keinen unbedingten Mehrwert hat, könnte man das auch fast rauslassen, mal schauen.

**Comment by tzwn** [comment]
Danke.  :-)

Ich wollte mich auch bzgl. des Parameters noch ein wenig informieren, bin jedoch bisher einfach noch nicht dazu gekommen.

**Comment by tzwn** [comment]
Ich weiß nicht, ob dir der Beitrag im Forum aufgefallen ist, der diesen Link enthielt?

[https://tvheadend.org/projects/tvheadend/wiki/Custom_MPEG-TS_Input](url)

In diesem wird das "FFmpeg flag '-tune zerolatency'" erwähnt.

**Comment by Andulien** [comment]
Also wenns interessiert, ich nutze auch die IP TVs für mein DS212j, musste aber die parameter ein bisschen umschreiben damit es reibunslos funktioniert. Hier mal ein Auszug für einen Kanal. Vielleicht hilft es ja dem ein oder anderen, oder es gibt irgendwas direkt eine m3u die wir nutzen können ;)
Ich hierzu zwei Punkte mitgeben:
1. Das Logo scheint bei einem neuen Import nicht mehr richtig angezeigt werden. Wahrscheinlich Cache problem.
2. Zur Konfiguration lege ich erst ein Automatisches neues IP Netzwerk an (Name egal), und dann Füge dann eine URL zur m3u hinzu. Force Scan dann tauchen alle Muxe auf. Jedoch muss man dann noch mal alle Muxe manuel auf aktiv setzten immer so in 3-4er packs damit er diese einzeln gescannt bekommt. Mag vielleicht auch an meiner DS liegen da diese ja schon ein bisschen älter ist. Ansonsten funktioniert es dann wenn Scan Result OK anzeigt. Nun nur noch Map Service im Service Tab machen und fertig.
3. Beim FFMPEG sichergehen das ihr hier die location der neuesten FFMPEG angebt und nicht eine in DS integrierte Version da diese zu alt ist für TVH. FFMPEG muss entsprechend separat installiert werden, gibt hier ein package dafür.
Wenns noch Fragen gibt lasst mich wissen.


#EXTINF:-1 tvg-name="ZDF HD" tvg-id="ZDF.de" tvg-logo="https://raw.githubusercontent.com/3PO/Senderlogos/master/zdf%20hd.png" group-title="IPTV",ZDF HD
pipe:///volume1/@appstore/ffmpeg/bin/ffmpeg -loglevel fatal -i http://zdf1314-lh.akamaihd.net/i/de14_v1@392878/index_3096_av-b.m3u8 -vcodec copy -acodec copy -metadata service_provider=IPTV -metadata service_name=ZDF\ HD -mpegts_service_type advanced_codec_digital_hdtv -f mpegts pipe:1

**Comment by jnk22** [comment]
Habe mich da mal bisschen durchgelesen, zusammengefasst bewirkt der Parameter "-tune zerolatency" wohl, dass es durchaus zu kürzeren Latenzzeiten kommen kann. Ist wohl für Livestreams ganz sinnvoll, denke in der _Theorie_ macht das auch durchaus für Tvheadend Sinn. Allerdings handelt es sich dabei mit ziemlicher Sicherheit nur um maximal einige 100ms.

Habe das mal laienhaft per Hand gestoppt mit der Konfiguration: Tvheadend auf meinem Netzwerk-Server -> über 2 Switches -> mein PC mit Kodi-TVH-Addon.
Dabei konnte ich keinen wirklichen Unterschied feststellen, aber wie gesagt, war auch nicht professionell getestet. Wer da noch etwas mehr testen möchte, gerne. Bei meinen "Tests" lag zerolatency um <2% vorne.

Da ja letzendlich Kodi, der Tvheadend-Server selber, das Netzwerk und alles zusammen auch immer eine gewisse Latenz aufweist, hält sich der positive Effekt von zerolatency wahrscheinlich sowieso in Grenzen.

Angeblich kann zerolatency aber auch Nachteile mit sich bringen, nämlich in der Qualität des Streams selber (siehe Quellen) und auch in einem größeren Stream (also größere Datenmenge für weniger Qualität?).
Da sich der Vorteil in Grenzen hält und das ganze ja auch mit Qualitätsverlust einhergehen _kann_, würde ich fast sagen, dass man den Parameter eigtl. sogar komplett rausschmeißen könnte.

Vorteil wäre dann, dass das ganze für Anwender leichter zu dokumentieren ist, hilft bei der gesamten Übersicht und löst so auch gleich das Problem, dass es überhaupt zu solchen Fehlern (mit nicht-unterstützten ffmpeg-Versionen) kommen kann.

Was sagt ihr?

Hier noch die Quellen, die ich gefunden habe:
https://trac.ffmpeg.org/wiki/StreamingGuide#Latency
https://obsproject.com/forum/threads/x264-tunes-fastdecode-vs-zerolatency.42247/
https://superuser.com/questions/564402/explanation-of-x264-tune
https://app.zencoder.com/docs/api/encoding/h264/tuning
http://x265.readthedocs.io/en/default/presets.html#zero-latency

**Comment by tzwn** [comment]
@jnk22 
Ich kann deine Versuche bestätigen - konnte keine allzu großen Geschwindigkeitsvorteile mit dem Parameter "-tune zerolatency" feststellen. Sicher könnte man argumentieren, das jede kleine Verzögerung von Anforderung bis Auslieferung des Streams sich aufsummiert und das Gefühl des "zappens" bremst - ich würde aber zugunsten der mutmaßlich größeren Kompatibilität dieses Paramter eher wegfallen lassen. 

Ich habe leider bei meinen Versuchen versäumt die Daten / Zeiten im debug-log mitzuschneiden - könnte es aber wenn wir Zahlen sehen wollen noch einmal tun. 

(Sorry für die späte Reaktion. Hab leider im Moment viel um die Ohren.)

**Comment by jnk22** [comment]
Kein Ding, eilt ja nicht :)

Danke fürs gegentesten! Die Möglichkeit mit den Debuglogs hatte ich ganz vergessen, hatte schon überlegt wie man das am besten machen könnte. Darauf kam ich dann iwie nicht.. :D

Sofern da jetzt die nächsten 2 - 3 Tage niemand Einwende äußert, würde ich dann den Parameter auf den bestehenden Listen löschen.
